{lib, callPackage, ...}:
let
    versions = (let
        _dXBBxqih = {
            "id" = "dXBBxqih";
            "file" = "Sundial Lite v1.0.0.zip";
            "hash" = "sha512-C26GgHKDvji9WVTMRa076iyVZsRfFRoYZPXShsDDFhuclURq0IutpvyEpglU6hevrsFxAdikHnZgIltFD+jnkQ==";
        };
        _wmkJLjfZ = {
            "id" = "wmkJLjfZ";
            "file" = "Sundial Lite v1.1.0.zip";
            "hash" = "sha512-E6yrPyd0exJGXxQUzRgiH0Sa6s2MAvsh22DjDA4AyYYYlaokPPyWZHNLoXQ7DtzFGmisqsdTjwSslgZ3zhRTjA==";
        };
    in {
        "dXBBxqih" = _dXBBxqih;
        "wmkJLjfZ" = _wmkJLjfZ;
        "iris-1.8.9" = _wmkJLjfZ;
        "iris-1.12.2" = _wmkJLjfZ;
        "iris-1.14.4" = _wmkJLjfZ;
        "iris-1.15" = _wmkJLjfZ;
        "iris-1.15.1" = _wmkJLjfZ;
        "iris-1.15.2" = _wmkJLjfZ;
        "iris-1.16" = _wmkJLjfZ;
        "iris-1.16.1" = _wmkJLjfZ;
        "iris-1.16.2" = _wmkJLjfZ;
        "iris-1.16.3" = _wmkJLjfZ;
        "iris-1.16.4" = _wmkJLjfZ;
        "iris-1.16.5" = _wmkJLjfZ;
        "iris-1.17" = _wmkJLjfZ;
        "iris-1.17.1" = _wmkJLjfZ;
        "iris-1.18" = _wmkJLjfZ;
        "iris-1.18.1" = _wmkJLjfZ;
        "iris-1.18.2" = _wmkJLjfZ;
        "iris-1.19" = _wmkJLjfZ;
        "iris-1.19.1" = _wmkJLjfZ;
        "iris-1.19.2" = _wmkJLjfZ;
        "iris-1.19.3" = _wmkJLjfZ;
        "iris-1.19.4" = _wmkJLjfZ;
        "iris-1.20" = _wmkJLjfZ;
        "iris-1.20.1" = _wmkJLjfZ;
        "iris-1.20.2" = _wmkJLjfZ;
        "iris-1.20.3" = _wmkJLjfZ;
        "iris-1.20.4" = _wmkJLjfZ;
        "iris-1.20.5" = _wmkJLjfZ;
        "iris-1.20.6" = _wmkJLjfZ;
        "iris-1.21" = _wmkJLjfZ;
        "iris-1.21.1" = _wmkJLjfZ;
        "iris-1.21.2" = _wmkJLjfZ;
        "iris-1.21.3" = _wmkJLjfZ;
        "iris-1.21.4" = _wmkJLjfZ;
        "iris-1.21.5" = _wmkJLjfZ;
        "iris-1.21.6" = _wmkJLjfZ;
        "iris-1.21.7" = _wmkJLjfZ;
        "iris-1.21.8" = _wmkJLjfZ;
        "iris-1.21.9" = _wmkJLjfZ;
        "iris-1.21.10" = _wmkJLjfZ;
        "iris-1.21.11" = _wmkJLjfZ;
        "iris-26.1" = _wmkJLjfZ;
        "iris-26.1.1" = _wmkJLjfZ;
        "iris-26.1.2" = _wmkJLjfZ;
        "iris-26.2" = _wmkJLjfZ;
        "optifine-1.8.9" = _wmkJLjfZ;
        "optifine-1.12.2" = _wmkJLjfZ;
        "optifine-1.14.4" = _wmkJLjfZ;
        "optifine-1.15" = _wmkJLjfZ;
        "optifine-1.15.1" = _wmkJLjfZ;
        "optifine-1.15.2" = _wmkJLjfZ;
        "optifine-1.16" = _wmkJLjfZ;
        "optifine-1.16.1" = _wmkJLjfZ;
        "optifine-1.16.2" = _wmkJLjfZ;
        "optifine-1.16.3" = _wmkJLjfZ;
        "optifine-1.16.4" = _wmkJLjfZ;
        "optifine-1.16.5" = _wmkJLjfZ;
        "optifine-1.17" = _wmkJLjfZ;
        "optifine-1.17.1" = _wmkJLjfZ;
        "optifine-1.18" = _wmkJLjfZ;
        "optifine-1.18.1" = _wmkJLjfZ;
        "optifine-1.18.2" = _wmkJLjfZ;
        "optifine-1.19" = _wmkJLjfZ;
        "optifine-1.19.1" = _wmkJLjfZ;
        "optifine-1.19.2" = _wmkJLjfZ;
        "optifine-1.19.3" = _wmkJLjfZ;
        "optifine-1.19.4" = _wmkJLjfZ;
        "optifine-1.20" = _wmkJLjfZ;
        "optifine-1.20.1" = _wmkJLjfZ;
        "optifine-1.20.2" = _wmkJLjfZ;
        "optifine-1.20.3" = _wmkJLjfZ;
        "optifine-1.20.4" = _wmkJLjfZ;
        "optifine-1.20.5" = _wmkJLjfZ;
        "optifine-1.20.6" = _wmkJLjfZ;
        "optifine-1.21" = _wmkJLjfZ;
        "optifine-1.21.1" = _wmkJLjfZ;
        "optifine-1.21.2" = _wmkJLjfZ;
        "optifine-1.21.3" = _wmkJLjfZ;
        "optifine-1.21.4" = _wmkJLjfZ;
        "optifine-1.21.5" = _wmkJLjfZ;
        "optifine-1.21.6" = _wmkJLjfZ;
        "optifine-1.21.7" = _wmkJLjfZ;
        "optifine-1.21.8" = _wmkJLjfZ;
        "optifine-1.21.9" = _wmkJLjfZ;
        "optifine-1.21.10" = _wmkJLjfZ;
        "optifine-1.21.11" = _wmkJLjfZ;
        "optifine-26.1" = _wmkJLjfZ;
        "optifine-26.1.1" = _wmkJLjfZ;
        "optifine-26.1.2" = _wmkJLjfZ;
        "optifine-26.2" = _wmkJLjfZ;
        "pkg-1.0.0" = _dXBBxqih;
        "pkg-1.1.0" = _wmkJLjfZ;
        "default" = _wmkJLjfZ;
    });
    fn = lib.prismnix.pkgs.mkVersionedModrinthPkgFn {
        name = "sundial-lite";
        id = "2cbOUuF5";
        type = "shader";
        versions = versions;
        meta = {
            license = lib.getLicenseFromSpdxIdOr "GPL-3.0-or-later" {
                free = false;
                deprecated = false;
                redistributable = false;
                fullName = "GNU General Public License v3.0 or later";
                shortName = "GPL-3.0-or-later";
                url = null;
            };
        };
    };
in callPackage fn {}