{lib, callPackage, ...}:
let
    versions = (let
        _Y3JVSoKS = {
            "id" = "Y3JVSoKS";
            "file" = "§d§lMini-Me Totem§8§o §8v1.0.0.zip";
            "hash" = "sha512-NK/dJYVj6007SMYFsWe7cph7UXluQB4ezwHBmwSJrQuhi4yzbRvjA1B2RKmkG8eVR5eTopd+lJ6VfDvetQSnNA==";
        };
        _BjdWvaKZ = {
            "id" = "BjdWvaKZ";
            "file" = "§d§l🧍 §d§lMini-Me Totem§8§o §8v1.0.0.zip";
            "hash" = "sha512-EB0bda+aJM+5dNz5jiEBK+fWmyd9tH7C1/rj6+PRegXd7/pM6YDstvotp1VNYl2psjDTF5WVxYaZY7Ru6Bls8Q==";
        };
        _btCoJ0o1 = {
            "id" = "btCoJ0o1";
            "file" = "§d§l🧍 §d§lMini-Me Totem§8§o §8v1.0.1.zip";
            "hash" = "sha512-JUzyn/Lbrvl6JI+Ias9MtpwJIOEdh2su7ebprnIHYOott40u8qzon4aAnXfWdLMza3eJ1bTVYcJMp1aPTNizxw==";
        };
        _nESQzDah = {
            "id" = "nESQzDah";
            "file" = "§d§l🧍 §d§lMini-Me Totem§8§o §8v1.0.2.zip";
            "hash" = "sha512-Yxpah96eHXfHMQjiOgQgHIWa2GtdW8tX+/WyLjWTXC7uvGEf5lClSkUzhEjEfN2rLZfxz/IoOxCP3zgYUeIRHg==";
        };
        _kqUQIeTe = {
            "id" = "kqUQIeTe";
            "file" = "§d§l🧍 §d§lMini-Me Totem§8§o §8v1.0.2.zip";
            "hash" = "sha512-btkAI4xRr9HZ/Z/5YoL27s18GTO0I3IfeLd+iJZqpM0JblG0Wx6438mJf2j6YN4KfwO4uh4hGiASUYmWSqqiCQ==";
        };
        _6TMcOTKv = {
            "id" = "6TMcOTKv";
            "file" = "§d§l🧍 §d§lMini-Me Totem§8 Classic.zip";
            "hash" = "sha512-VgK+wnTHm5Wo6WztDTjc1VUKsMYLq3mov8+nLlCVZnxAPq2meb0SI9lZnAZccwOQJ7rdPFeeGh+3GAAwuR70mA==";
        };
        _sWb1eAKb = {
            "id" = "sWb1eAKb";
            "file" = "§d§l🧍 §d§lMini-Me Totem§8 Classic.zip";
            "hash" = "sha512-gycCcoN/nbN56fDDVHFr1HXJO9Zsj7f9wXYIW/oxUXYEQ2x6J5jnSnc7JcSfQfRa1esa58XSWD/7GE8sqDArBg==";
        };
        _Hyzd4xSg = {
            "id" = "Hyzd4xSg";
            "file" = "§d§l🧍 §d§lMini-Me Totem§8 Classic.zip";
            "hash" = "sha512-ERz4TWu9dilZN+T+CsDAjENwKbMSUYKBjczxOpz1AvHfRhcuZ1xZ1wShnp0GadVVMkUCPT0Fx50rJJIz4Q3b6Q==";
        };
        _zNugUDjl = {
            "id" = "zNugUDjl";
            "file" = "§d§l🧍 §d§lMini-Me Totem§8 Classic.zip";
            "hash" = "sha512-hR+dt3DdESyouA5wFMgQVivyDsOzGfLjZ+DHIX9vduwdAov/tjA/tTZNeBofBtlLygKkWsAZpE1sBEs+lpz58Q==";
        };
        _JEpIsZHv = {
            "id" = "JEpIsZHv";
            "file" = "§d§l🧍 §d§lMini-Me Totem§8 Classic.zip";
            "hash" = "sha512-xBL2hPaUK4kae9ly0sqF229c5rfTPEobaOVrla4xEAI9wBDQDfW+DqsXYng/kNYK/w6NwP84v6LAu5PxCU0/0g==";
        };
    in {
        "Y3JVSoKS" = _Y3JVSoKS;
        "BjdWvaKZ" = _BjdWvaKZ;
        "btCoJ0o1" = _btCoJ0o1;
        "nESQzDah" = _nESQzDah;
        "kqUQIeTe" = _kqUQIeTe;
        "6TMcOTKv" = _6TMcOTKv;
        "sWb1eAKb" = _sWb1eAKb;
        "Hyzd4xSg" = _Hyzd4xSg;
        "zNugUDjl" = _zNugUDjl;
        "JEpIsZHv" = _JEpIsZHv;
        "minecraft-1.11" = _6TMcOTKv;
        "minecraft-1.11.1" = _6TMcOTKv;
        "minecraft-1.11.2" = _6TMcOTKv;
        "minecraft-1.12" = _6TMcOTKv;
        "minecraft-1.12.1" = _6TMcOTKv;
        "minecraft-1.12.2" = _6TMcOTKv;
        "minecraft-1.13" = _sWb1eAKb;
        "minecraft-1.13.1" = _sWb1eAKb;
        "minecraft-1.13.2" = _sWb1eAKb;
        "minecraft-1.14" = _sWb1eAKb;
        "minecraft-1.14.1" = _sWb1eAKb;
        "minecraft-1.14.2" = _sWb1eAKb;
        "minecraft-1.14.3" = _sWb1eAKb;
        "minecraft-1.14.4" = _sWb1eAKb;
        "minecraft-1.15" = _Hyzd4xSg;
        "minecraft-1.15.1" = _Hyzd4xSg;
        "minecraft-1.15.2" = _Hyzd4xSg;
        "minecraft-1.16" = _Hyzd4xSg;
        "minecraft-1.16.1" = _Hyzd4xSg;
        "minecraft-1.16.2" = _Hyzd4xSg;
        "minecraft-1.16.3" = _Hyzd4xSg;
        "minecraft-1.16.4" = _Hyzd4xSg;
        "minecraft-1.16.5" = _Hyzd4xSg;
        "minecraft-1.17" = _Hyzd4xSg;
        "minecraft-1.17.1" = _Hyzd4xSg;
        "minecraft-1.18" = _Hyzd4xSg;
        "minecraft-1.18.1" = _Hyzd4xSg;
        "minecraft-1.18.2" = _Hyzd4xSg;
        "minecraft-1.19" = _Hyzd4xSg;
        "minecraft-1.19.1" = _Hyzd4xSg;
        "minecraft-1.19.2" = _Hyzd4xSg;
        "minecraft-1.19.3" = _Hyzd4xSg;
        "minecraft-1.19.4" = _Hyzd4xSg;
        "minecraft-1.20" = _Hyzd4xSg;
        "minecraft-1.20.1" = _Hyzd4xSg;
        "minecraft-1.20.2" = _zNugUDjl;
        "minecraft-1.20.3" = _zNugUDjl;
        "minecraft-1.20.4" = _zNugUDjl;
        "minecraft-1.20.5" = _zNugUDjl;
        "minecraft-1.20.6" = _zNugUDjl;
        "minecraft-1.21" = _zNugUDjl;
        "minecraft-1.21.1" = _zNugUDjl;
        "minecraft-1.21.2" = _zNugUDjl;
        "minecraft-1.21.3" = _zNugUDjl;
        "minecraft-1.21.4" = _zNugUDjl;
        "minecraft-1.21.5" = _zNugUDjl;
        "minecraft-1.21.6-pre1" = _BjdWvaKZ;
        "minecraft-1.21.6" = _zNugUDjl;
        "minecraft-1.21.7-rc1" = _BjdWvaKZ;
        "minecraft-1.21.7-rc2" = _BjdWvaKZ;
        "minecraft-1.21.7" = _zNugUDjl;
        "minecraft-1.21.8" = _zNugUDjl;
        "minecraft-25w31a" = _btCoJ0o1;
        "minecraft-25w32a" = _btCoJ0o1;
        "minecraft-25w33a" = _btCoJ0o1;
        "minecraft-25w34a" = _btCoJ0o1;
        "minecraft-25w34b" = _btCoJ0o1;
        "minecraft-25w35a" = _btCoJ0o1;
        "minecraft-25w36a" = _btCoJ0o1;
        "minecraft-25w36b" = _btCoJ0o1;
        "minecraft-25w37a" = _btCoJ0o1;
        "minecraft-1.21.9" = _JEpIsZHv;
        "minecraft-1.21.10" = _JEpIsZHv;
        "minecraft-1.21.11-pre1" = _btCoJ0o1;
        "minecraft-1.21.11-pre2" = _btCoJ0o1;
        "minecraft-1.21.11-pre3" = _btCoJ0o1;
        "minecraft-1.21.11-pre4" = _btCoJ0o1;
        "minecraft-1.21.11-pre5" = _btCoJ0o1;
        "minecraft-1.21.11-rc1" = _btCoJ0o1;
        "minecraft-1.21.11-rc2" = _btCoJ0o1;
        "minecraft-1.21.11-rc3" = _btCoJ0o1;
        "minecraft-1.21.11" = _JEpIsZHv;
        "minecraft-26.1-snapshot-1" = _btCoJ0o1;
        "minecraft-26.1-snapshot-2" = _btCoJ0o1;
        "minecraft-26.1-snapshot-3" = _btCoJ0o1;
        "minecraft-26.1-snapshot-4" = _btCoJ0o1;
        "minecraft-26.1-snapshot-5" = _btCoJ0o1;
        "minecraft-26.1-snapshot-6" = _btCoJ0o1;
        "minecraft-26.1-snapshot-7" = _btCoJ0o1;
        "minecraft-26.1-snapshot-8" = _btCoJ0o1;
        "minecraft-26.1-snapshot-9" = _btCoJ0o1;
        "minecraft-26.1-snapshot-11" = _btCoJ0o1;
        "minecraft-26.1-pre-1" = _btCoJ0o1;
        "minecraft-26.1-pre-2" = _btCoJ0o1;
        "minecraft-26.1-pre-3" = _btCoJ0o1;
        "minecraft-26.1-rc-1" = _btCoJ0o1;
        "minecraft-26.1-rc-2" = _btCoJ0o1;
        "minecraft-26.1-rc-3" = _btCoJ0o1;
        "minecraft-26.1" = _JEpIsZHv;
        "minecraft-26.1.1" = _JEpIsZHv;
        "minecraft-26.1.2" = _JEpIsZHv;
        "minecraft-22w42a" = _Hyzd4xSg;
        "minecraft-22w43a" = _Hyzd4xSg;
        "minecraft-22w44a" = _Hyzd4xSg;
        "minecraft-23w14a" = _Hyzd4xSg;
        "minecraft-23w16a" = _Hyzd4xSg;
        "minecraft-23w31a" = _kqUQIeTe;
        "minecraft-23w32a" = _kqUQIeTe;
        "minecraft-23w33a" = _kqUQIeTe;
        "minecraft-23w35a" = _kqUQIeTe;
        "minecraft-1.20.2-pre1" = _kqUQIeTe;
        "minecraft-23w42a" = _zNugUDjl;
        "minecraft-23w43a" = _zNugUDjl;
        "minecraft-23w43b" = _zNugUDjl;
        "minecraft-23w44a" = _zNugUDjl;
        "minecraft-23w45a" = _zNugUDjl;
        "minecraft-23w46a" = _zNugUDjl;
        "minecraft-24w03a" = _zNugUDjl;
        "minecraft-24w03b" = _zNugUDjl;
        "minecraft-24w04a" = _zNugUDjl;
        "minecraft-24w05a" = _zNugUDjl;
        "minecraft-24w05b" = _zNugUDjl;
        "minecraft-24w06a" = _zNugUDjl;
        "minecraft-24w07a" = _zNugUDjl;
        "minecraft-24w09a" = _zNugUDjl;
        "minecraft-24w10a" = _zNugUDjl;
        "minecraft-24w11a" = _zNugUDjl;
        "minecraft-24w12a" = _zNugUDjl;
        "minecraft-24w13a" = _zNugUDjl;
        "minecraft-24w14potato" = _zNugUDjl;
        "minecraft-24w14a" = _zNugUDjl;
        "minecraft-1.20.5-pre1" = _zNugUDjl;
        "minecraft-1.20.5-pre2" = _zNugUDjl;
        "minecraft-1.20.5-pre3" = _zNugUDjl;
        "minecraft-24w18a" = _zNugUDjl;
        "minecraft-24w19a" = _zNugUDjl;
        "minecraft-24w19b" = _zNugUDjl;
        "minecraft-24w20a" = _zNugUDjl;
        "minecraft-24w33a" = _zNugUDjl;
        "minecraft-24w34a" = _zNugUDjl;
        "minecraft-24w35a" = _zNugUDjl;
        "minecraft-24w36a" = _zNugUDjl;
        "minecraft-24w37a" = _zNugUDjl;
        "minecraft-24w38a" = _zNugUDjl;
        "minecraft-24w39a" = _zNugUDjl;
        "minecraft-24w40a" = _zNugUDjl;
        "minecraft-1.21.2-pre1" = _zNugUDjl;
        "minecraft-1.21.2-pre2" = _zNugUDjl;
        "minecraft-24w44a" = _zNugUDjl;
        "minecraft-24w45a" = _zNugUDjl;
        "minecraft-24w46a" = _zNugUDjl;
        "minecraft-26.2" = _JEpIsZHv;
        "minecraft-26.3" = _JEpIsZHv;
        "pkg-v1.0.0" = _BjdWvaKZ;
        "pkg-v1.0.1" = _btCoJ0o1;
        "pkg-v1.0.2" = _nESQzDah;
        "pkg-1.0.2" = _kqUQIeTe;
        "pkg-v1.1.0" = _JEpIsZHv;
        "default" = _JEpIsZHv;
    });
    fn = lib.prismnix.pkgs.mkVersionedModrinthPkgFn {
        name = "mini-me-totem";
        id = "3jzanPAr";
        type = "resourcepack";
        versions = versions;
        meta = {
            license = lib.getLicenseFromSpdxIdOr "LicenseRef-NotToBlame-Resource-License" {
                free = false;
                deprecated = false;
                redistributable = false;
                fullName = "LicenseRef-NotToBlame-Resource-License";
                shortName = "LicenseRef-NotToBlame-Resource-License";
                url = "https://www.nottobla.me/assets/license.md";
            };
        };
    };
in callPackage fn {}