{lib, callPackage, ...}:
let
    versions = (let
        _paSPliqj = {
            "id" = "paSPliqj";
            "file" = "Magic Anti Leak.zip";
            "hash" = "sha512-hmpwL4DIy5EZ0n7AdFXY9KPmTsYdq1iUgj+TQ0R+1J+aMXRYn4VIbVgxMDXZfGUpWss1lvMPMfykOp65CeZkJw==";
        };
        _A6Tp2EfO = {
            "id" = "A6Tp2EfO";
            "file" = "Magic-Anti-Leak.zip";
            "hash" = "sha512-+ipV29+2OFez0nz2mZHrOUVHftFdkgs69VkbOmFe8hESSQbmJ79OWBRuwlIH6BpRkumGROo6D3qIo+PnpD7iGw==";
        };
        _hZOQ71mE = {
            "id" = "hZOQ71mE";
            "file" = "Magic-Anti-Leak_1.zip";
            "hash" = "sha512-0tIDmjBmygsd2DUw1RvuxkShs8zjlKOyGhgwreONHmGiM6ItdrJDb8Q9petdbc+5N7GLN5ftc45nJSQnOvNicw==";
        };
        _gtvotn8k = {
            "id" = "gtvotn8k";
            "file" = "Magic-Anti-Leak_5.zip";
            "hash" = "sha512-cmyXxAtNdOvMMZTzr6uN8AY69CPj1/HGUKmWL9Iyop1jZEVCGMPm2OOB5MtPpTshOiehyMI8QFK/zFrR2zbtXA==";
        };
    in {
        "paSPliqj" = _paSPliqj;
        "A6Tp2EfO" = _A6Tp2EfO;
        "hZOQ71mE" = _hZOQ71mE;
        "gtvotn8k" = _gtvotn8k;
        "minecraft-1.8" = _paSPliqj;
        "minecraft-1.8.1" = _paSPliqj;
        "minecraft-1.8.2" = _paSPliqj;
        "minecraft-1.8.3" = _paSPliqj;
        "minecraft-1.8.4" = _paSPliqj;
        "minecraft-1.8.5" = _paSPliqj;
        "minecraft-1.8.6" = _paSPliqj;
        "minecraft-1.8.7" = _paSPliqj;
        "minecraft-1.8.8" = _paSPliqj;
        "minecraft-1.8.9" = _paSPliqj;
        "minecraft-1.9" = _A6Tp2EfO;
        "minecraft-1.9.1" = _A6Tp2EfO;
        "minecraft-1.9.2" = _A6Tp2EfO;
        "minecraft-1.9.3" = _A6Tp2EfO;
        "minecraft-1.9.4" = _A6Tp2EfO;
        "minecraft-1.10" = _A6Tp2EfO;
        "minecraft-1.10.1" = _A6Tp2EfO;
        "minecraft-1.10.2" = _A6Tp2EfO;
        "minecraft-1.11" = _A6Tp2EfO;
        "minecraft-1.11.1" = _A6Tp2EfO;
        "minecraft-1.11.2" = _A6Tp2EfO;
        "minecraft-1.12" = _A6Tp2EfO;
        "minecraft-1.12.1" = _A6Tp2EfO;
        "minecraft-1.12.2" = _A6Tp2EfO;
        "minecraft-1.13" = _A6Tp2EfO;
        "minecraft-1.13.1" = _A6Tp2EfO;
        "minecraft-1.13.2" = _A6Tp2EfO;
        "minecraft-1.14" = _gtvotn8k;
        "minecraft-1.14.1" = _gtvotn8k;
        "minecraft-1.14.2" = _gtvotn8k;
        "minecraft-1.14.3" = _gtvotn8k;
        "minecraft-1.14.4" = _gtvotn8k;
        "minecraft-1.15" = _gtvotn8k;
        "minecraft-1.15.1" = _gtvotn8k;
        "minecraft-1.15.2" = _gtvotn8k;
        "minecraft-1.16" = _gtvotn8k;
        "minecraft-1.16.1" = _gtvotn8k;
        "minecraft-1.16.2" = _gtvotn8k;
        "minecraft-1.16.3" = _gtvotn8k;
        "minecraft-1.16.4" = _gtvotn8k;
        "minecraft-1.16.5" = _gtvotn8k;
        "minecraft-1.17" = _gtvotn8k;
        "minecraft-1.17.1" = _gtvotn8k;
        "minecraft-1.18" = _gtvotn8k;
        "minecraft-1.18.1" = _gtvotn8k;
        "minecraft-1.18.2" = _gtvotn8k;
        "minecraft-1.19" = _gtvotn8k;
        "minecraft-1.19.1" = _gtvotn8k;
        "minecraft-1.19.2" = _gtvotn8k;
        "minecraft-1.19.3" = _gtvotn8k;
        "minecraft-1.19.4" = _gtvotn8k;
        "minecraft-1.20" = _gtvotn8k;
        "minecraft-1.20.1" = _gtvotn8k;
        "minecraft-1.20.2" = _gtvotn8k;
        "minecraft-1.20.3" = _gtvotn8k;
        "minecraft-1.20.4" = _gtvotn8k;
        "minecraft-1.20.5" = _gtvotn8k;
        "minecraft-1.20.6" = _gtvotn8k;
        "minecraft-1.21" = _gtvotn8k;
        "minecraft-1.21.1" = _gtvotn8k;
        "minecraft-24w33a" = _gtvotn8k;
        "minecraft-24w34a" = _gtvotn8k;
        "minecraft-24w35a" = _gtvotn8k;
        "minecraft-24w36a" = _gtvotn8k;
        "minecraft-24w37a" = _gtvotn8k;
        "minecraft-24w38a" = _gtvotn8k;
        "minecraft-24w39a" = _gtvotn8k;
        "minecraft-24w40a" = _gtvotn8k;
        "minecraft-1.21.2-pre1" = _gtvotn8k;
        "minecraft-1.21.2-pre2" = _gtvotn8k;
        "minecraft-1.21.2" = _gtvotn8k;
        "minecraft-1.21.3" = _gtvotn8k;
        "minecraft-24w44a" = _gtvotn8k;
        "minecraft-24w45a" = _gtvotn8k;
        "minecraft-24w46a" = _gtvotn8k;
        "minecraft-1.21.4" = _gtvotn8k;
        "minecraft-1.21.5" = _gtvotn8k;
        "minecraft-1.21.6" = _gtvotn8k;
        "minecraft-1.21.7" = _gtvotn8k;
        "minecraft-1.21.8" = _gtvotn8k;
        "minecraft-1.21.9" = _gtvotn8k;
        "minecraft-1.21.10" = _gtvotn8k;
        "minecraft-1.21.11" = _gtvotn8k;
        "minecraft-26.1" = _gtvotn8k;
        "minecraft-26.1.1" = _gtvotn8k;
        "minecraft-26.1.2" = _gtvotn8k;
        "minecraft-26.2" = _gtvotn8k;
        "minecraft-26.3-snapshot-1" = _hZOQ71mE;
        "minecraft-26.3-snapshot-2" = _hZOQ71mE;
        "minecraft-26.3-snapshot-3" = _hZOQ71mE;
        "minecraft-26.3-snapshot-4" = _hZOQ71mE;
        "minecraft-26.3-snapshot-5" = _hZOQ71mE;
        "minecraft-26.3-snapshot-6" = _hZOQ71mE;
        "minecraft-26.3-snapshot-7" = _hZOQ71mE;
        "minecraft-26.3-snapshot-8" = _hZOQ71mE;
        "minecraft-26.3-snapshot-9" = _hZOQ71mE;
        "pkg-1" = _paSPliqj;
        "pkg-2" = _A6Tp2EfO;
        "pkg-3" = _hZOQ71mE;
        "pkg-4" = _gtvotn8k;
        "default" = _gtvotn8k;
    });
    fn = lib.prismnix.pkgs.mkVersionedModrinthPkgFn {
        name = "anti-leak-texturepack";
        id = "4i8rrrVB";
        type = "resourcepack";
        versions = versions;
        meta = {
            license = lib.getLicenseFromSpdxIdOr "MIT" {
                free = false;
                deprecated = false;
                redistributable = false;
                fullName = "MIT License";
                shortName = "MIT";
                url = null;
            };
        };
    };
in callPackage fn {}