{lib, callPackage, ...}:
let
    versions = (let
        _AYSdtiGx = {
            "id" = "AYSdtiGx";
            "file" = "Dot's Crosshair.zip";
            "hash" = "sha512-jFk5CiNCfHAcTVg7dgdD5YASLwTVwjcSDluAuiyVq3/XrKDMdsNEBps1MpwGwS7+hndnqqird70mOpfxiLJrog==";
        };
    in {
        "AYSdtiGx" = _AYSdtiGx;
        "minecraft-1.20" = _AYSdtiGx;
        "minecraft-1.20.1" = _AYSdtiGx;
        "minecraft-23w31a" = _AYSdtiGx;
        "minecraft-23w32a" = _AYSdtiGx;
        "minecraft-23w33a" = _AYSdtiGx;
        "minecraft-23w35a" = _AYSdtiGx;
        "minecraft-1.20.2-pre1" = _AYSdtiGx;
        "minecraft-1.20.2" = _AYSdtiGx;
        "minecraft-23w42a" = _AYSdtiGx;
        "minecraft-23w43a" = _AYSdtiGx;
        "minecraft-23w43b" = _AYSdtiGx;
        "minecraft-23w44a" = _AYSdtiGx;
        "minecraft-23w45a" = _AYSdtiGx;
        "minecraft-23w46a" = _AYSdtiGx;
        "minecraft-1.20.3" = _AYSdtiGx;
        "minecraft-1.20.4" = _AYSdtiGx;
        "minecraft-24w03a" = _AYSdtiGx;
        "minecraft-24w03b" = _AYSdtiGx;
        "minecraft-24w04a" = _AYSdtiGx;
        "minecraft-24w05a" = _AYSdtiGx;
        "minecraft-24w05b" = _AYSdtiGx;
        "minecraft-24w06a" = _AYSdtiGx;
        "minecraft-24w07a" = _AYSdtiGx;
        "minecraft-24w09a" = _AYSdtiGx;
        "minecraft-24w10a" = _AYSdtiGx;
        "minecraft-24w11a" = _AYSdtiGx;
        "minecraft-24w12a" = _AYSdtiGx;
        "minecraft-24w13a" = _AYSdtiGx;
        "minecraft-24w14potato" = _AYSdtiGx;
        "minecraft-24w14a" = _AYSdtiGx;
        "minecraft-1.20.5-pre1" = _AYSdtiGx;
        "minecraft-1.20.5-pre2" = _AYSdtiGx;
        "minecraft-1.20.5-pre3" = _AYSdtiGx;
        "minecraft-1.20.5" = _AYSdtiGx;
        "minecraft-1.20.6" = _AYSdtiGx;
        "minecraft-24w18a" = _AYSdtiGx;
        "minecraft-24w19a" = _AYSdtiGx;
        "minecraft-24w19b" = _AYSdtiGx;
        "minecraft-24w20a" = _AYSdtiGx;
        "minecraft-1.21" = _AYSdtiGx;
        "minecraft-1.21.1" = _AYSdtiGx;
        "minecraft-24w33a" = _AYSdtiGx;
        "minecraft-24w34a" = _AYSdtiGx;
        "minecraft-24w35a" = _AYSdtiGx;
        "minecraft-24w36a" = _AYSdtiGx;
        "minecraft-24w37a" = _AYSdtiGx;
        "minecraft-24w38a" = _AYSdtiGx;
        "minecraft-24w39a" = _AYSdtiGx;
        "minecraft-24w40a" = _AYSdtiGx;
        "minecraft-1.21.2-pre1" = _AYSdtiGx;
        "minecraft-1.21.2-pre2" = _AYSdtiGx;
        "minecraft-1.21.2" = _AYSdtiGx;
        "minecraft-1.21.3" = _AYSdtiGx;
        "minecraft-24w44a" = _AYSdtiGx;
        "minecraft-24w45a" = _AYSdtiGx;
        "minecraft-24w46a" = _AYSdtiGx;
        "minecraft-1.21.4" = _AYSdtiGx;
        "minecraft-1.21.5" = _AYSdtiGx;
        "minecraft-1.21.6" = _AYSdtiGx;
        "minecraft-1.21.7" = _AYSdtiGx;
        "minecraft-1.21.8" = _AYSdtiGx;
        "minecraft-1.21.9" = _AYSdtiGx;
        "minecraft-1.21.10" = _AYSdtiGx;
        "minecraft-1.21.11" = _AYSdtiGx;
        "minecraft-26.1" = _AYSdtiGx;
        "minecraft-26.1.1" = _AYSdtiGx;
        "minecraft-26.1.2" = _AYSdtiGx;
        "minecraft-26.2-snapshot-2" = _AYSdtiGx;
        "minecraft-26.2-snapshot-3" = _AYSdtiGx;
        "minecraft-26.2-snapshot-4" = _AYSdtiGx;
        "minecraft-26.2-snapshot-5" = _AYSdtiGx;
        "minecraft-26.2-snapshot-6" = _AYSdtiGx;
        "minecraft-26.2-snapshot-7" = _AYSdtiGx;
        "minecraft-26.2-snapshot-8" = _AYSdtiGx;
        "minecraft-26.2-pre-1" = _AYSdtiGx;
        "minecraft-26.2-pre-2" = _AYSdtiGx;
        "minecraft-26.2" = _AYSdtiGx;
        "pkg-1.0" = _AYSdtiGx;
        "default" = _AYSdtiGx;
    });
    fn = lib.prismnix.pkgs.mkVersionedModrinthPkgFn {
        name = "dots-crosshair";
        id = "5ZkLLb8G";
        type = "resourcepack";
        versions = versions;
        meta = {
            license = lib.getLicenseFromSpdxIdOr "LicenseRef-All-Rights-Reserved" {
                free = false;
                deprecated = false;
                redistributable = false;
                fullName = "LicenseRef-All-Rights-Reserved";
                shortName = "LicenseRef-All-Rights-Reserved";
                url = null;
            };
        };
    };
in callPackage fn {}