{lib, callPackage, ...}:
let
    versions = (let
        _PKbK9GkJ = {
            "id" = "PKbK9GkJ";
            "file" = "Disenchantment-6.2.0.jar";
            "hash" = "sha512-LhYzTtxjocstFjiDjFBaonay6BMI6WcNhTXAVWN69Jy137frr7Ngma+ht1jhpVhCp/1F+TAmgFO/mWNRrzamgQ==";
        };
        _89zjdjT6 = {
            "id" = "89zjdjT6";
            "file" = "Disenchantment-6.2.1.jar";
            "hash" = "sha512-YAfj8LXlzzGkd3ndUsfkOGVvUcZZ3VJ60nBqOTjLcBvwmscjDS9XkCk6344iTIqXibtp3vE2rTOvoletj42NkA==";
        };
        _yz0Jnqer = {
            "id" = "yz0Jnqer";
            "file" = "Disenchantment-6.2.2.jar";
            "hash" = "sha512-n3Ru72gByPb32e8yozka/BupTxthSxd+iHXdvc1WvPV/vBo3iF50mnrHcjbPAFn+inpvAxY3hM6bwBKHrMapqA==";
        };
        _OYZufJ8P = {
            "id" = "OYZufJ8P";
            "file" = "Disenchantment-6.3.0.jar";
            "hash" = "sha512-UA9Dmu/gKtewi+cBrqSWIeMB+ZEKajo5Ru/NprnaSeTSmg6p1PNKheSDQjPO7LGdgghYlkw+JN01vJ90wdc6WQ==";
        };
        _K11I5h0F = {
            "id" = "K11I5h0F";
            "file" = "Disenchantment-6.3.1.jar";
            "hash" = "sha512-gCBOd1Hwf5a2YyM5xGoZDLfMcrWoZZpQx+l/Mv4tQPfkSvIabUEGv3xibk8Vh4X2747gWQtGux2YWI4rjqvljg==";
        };
        _1ahHZ97P = {
            "id" = "1ahHZ97P";
            "file" = "Disenchantment-6.3.2.jar";
            "hash" = "sha512-uAQKRj51DZJgb5lnr4h2Zqn4jlw0RaRoX4pq2Chvb56AKtD9deIvlZhLEjBB6t0sZOuIfF9d0zJ5l4eRl2JKpg==";
        };
        _dAeKkIzx = {
            "id" = "dAeKkIzx";
            "file" = "Disenchantment-6.3.3.jar";
            "hash" = "sha512-AAR+z0Y1u4BIZ2FzjlWIKRpc81WIbY5tOwN7ka0KMbovOApLAKsQhLxiwV2WdgTSa7dsTSoyCXiCFexsehJPzg==";
        };
        _Cv3Ozis3 = {
            "id" = "Cv3Ozis3";
            "file" = "Disenchantment-6.3.4.jar";
            "hash" = "sha512-j/0oba8iDtOR2XX1uYkkHcab4H3V7xzDpsydi+lXBHVXPjP3hYcYobLwtkk3rAmEbEFUwjv14V1nYLJaKVDTvw==";
        };
        _8WboOC2F = {
            "id" = "8WboOC2F";
            "file" = "Disenchantment-6.3.5.jar";
            "hash" = "sha512-vUJX8ZCqnop8ZMeX7R4PT+ACA6IoOj2O7iH3dslmYw0d+odbYyB/P6VyZK8yZnwoE4vhXDHLYyxHtM1y8yRHig==";
        };
        _nJedAzdD = {
            "id" = "nJedAzdD";
            "file" = "Disenchantment-6.4.0.jar";
            "hash" = "sha512-AoSHxcmXRdWTiz73g7j78K/39s9/MQxkW2jp1FPUg052Fe2NG8/HbcYZEXP0cAXhnqZaeyzzGYf24WrjZI5eZA==";
        };
        _UkqzB7sd = {
            "id" = "UkqzB7sd";
            "file" = "Disenchantment-6.5.0.jar";
            "hash" = "sha512-KrJzFowfFttV3aBGKcxnla5fqt1m3IIBJC/Hvaz/0LUoygR2QXHCHL2/TxMTc67RxTSeC1hBv/Gk6qT/SB+6+A==";
        };
        _RRrMHZKN = {
            "id" = "RRrMHZKN";
            "file" = "Disenchantment-6.5.11.jar";
            "hash" = "sha512-uOjyoogSGgmuww5RwGw2ueOjYODTlhZxbWxQzjuOP6JyEXMhhus9x5j7oyIA/ZLAprk7m9Rfl0dqDCHHAkmnjQ==";
        };
        _pEBypCNa = {
            "id" = "pEBypCNa";
            "file" = "Disenchantment-6.5.12.jar";
            "hash" = "sha512-eybNvmYThx4SF2n0tj/Duc0J944FNBrIJwCSGYihJrrphs4LCeUpuZ+GX8CD8oMkWQ6tweuzY286N1jBEXg9eg==";
        };
    in {
        "PKbK9GkJ" = _PKbK9GkJ;
        "89zjdjT6" = _89zjdjT6;
        "yz0Jnqer" = _yz0Jnqer;
        "OYZufJ8P" = _OYZufJ8P;
        "K11I5h0F" = _K11I5h0F;
        "1ahHZ97P" = _1ahHZ97P;
        "dAeKkIzx" = _dAeKkIzx;
        "Cv3Ozis3" = _Cv3Ozis3;
        "8WboOC2F" = _8WboOC2F;
        "nJedAzdD" = _nJedAzdD;
        "UkqzB7sd" = _UkqzB7sd;
        "RRrMHZKN" = _RRrMHZKN;
        "pEBypCNa" = _pEBypCNa;
        "folia-1.18" = _pEBypCNa;
        "folia-1.18.1" = _pEBypCNa;
        "folia-1.18.2" = _pEBypCNa;
        "folia-1.19" = _pEBypCNa;
        "folia-1.19.1" = _pEBypCNa;
        "folia-1.19.2" = _pEBypCNa;
        "folia-1.19.3" = _pEBypCNa;
        "folia-1.19.4" = _pEBypCNa;
        "folia-1.20" = _pEBypCNa;
        "folia-1.20.1" = _pEBypCNa;
        "folia-1.20.2" = _pEBypCNa;
        "folia-1.20.3" = _pEBypCNa;
        "folia-1.20.4" = _pEBypCNa;
        "folia-1.20.5" = _pEBypCNa;
        "folia-1.20.6" = _pEBypCNa;
        "folia-1.21" = _pEBypCNa;
        "folia-1.21.1" = _pEBypCNa;
        "folia-1.21.2" = _pEBypCNa;
        "folia-1.21.3" = _pEBypCNa;
        "folia-1.21.4" = _pEBypCNa;
        "folia-1.21.5" = _pEBypCNa;
        "folia-1.21.6" = _pEBypCNa;
        "folia-1.21.7" = _pEBypCNa;
        "folia-1.21.8" = _pEBypCNa;
        "folia-1.21.9" = _pEBypCNa;
        "folia-1.21.10" = _pEBypCNa;
        "folia-1.21.11" = _pEBypCNa;
        "folia-26.1" = _pEBypCNa;
        "folia-26.1.1" = _pEBypCNa;
        "folia-26.1.2" = _pEBypCNa;
        "folia-26.2" = _pEBypCNa;
        "paper-1.18" = _pEBypCNa;
        "paper-1.18.1" = _pEBypCNa;
        "paper-1.18.2" = _pEBypCNa;
        "paper-1.19" = _pEBypCNa;
        "paper-1.19.1" = _pEBypCNa;
        "paper-1.19.2" = _pEBypCNa;
        "paper-1.19.3" = _pEBypCNa;
        "paper-1.19.4" = _pEBypCNa;
        "paper-1.20" = _pEBypCNa;
        "paper-1.20.1" = _pEBypCNa;
        "paper-1.20.2" = _pEBypCNa;
        "paper-1.20.3" = _pEBypCNa;
        "paper-1.20.4" = _pEBypCNa;
        "paper-1.20.5" = _pEBypCNa;
        "paper-1.20.6" = _pEBypCNa;
        "paper-1.21" = _pEBypCNa;
        "paper-1.21.1" = _pEBypCNa;
        "paper-1.21.2" = _pEBypCNa;
        "paper-1.21.3" = _pEBypCNa;
        "paper-1.21.4" = _pEBypCNa;
        "paper-1.21.5" = _pEBypCNa;
        "paper-1.21.6" = _pEBypCNa;
        "paper-1.21.7" = _pEBypCNa;
        "paper-1.21.8" = _pEBypCNa;
        "paper-1.21.9" = _pEBypCNa;
        "paper-1.21.10" = _pEBypCNa;
        "paper-1.21.11" = _pEBypCNa;
        "paper-26.1" = _pEBypCNa;
        "paper-26.1.1" = _pEBypCNa;
        "paper-26.1.2" = _pEBypCNa;
        "paper-26.2" = _pEBypCNa;
        "purpur-1.18" = _pEBypCNa;
        "purpur-1.18.1" = _pEBypCNa;
        "purpur-1.18.2" = _pEBypCNa;
        "purpur-1.19" = _pEBypCNa;
        "purpur-1.19.1" = _pEBypCNa;
        "purpur-1.19.2" = _pEBypCNa;
        "purpur-1.19.3" = _pEBypCNa;
        "purpur-1.19.4" = _pEBypCNa;
        "purpur-1.20" = _pEBypCNa;
        "purpur-1.20.1" = _pEBypCNa;
        "purpur-1.20.2" = _pEBypCNa;
        "purpur-1.20.3" = _pEBypCNa;
        "purpur-1.20.4" = _pEBypCNa;
        "purpur-1.20.5" = _pEBypCNa;
        "purpur-1.20.6" = _pEBypCNa;
        "purpur-1.21" = _pEBypCNa;
        "purpur-1.21.1" = _pEBypCNa;
        "purpur-1.21.2" = _pEBypCNa;
        "purpur-1.21.3" = _pEBypCNa;
        "purpur-1.21.4" = _pEBypCNa;
        "purpur-1.21.5" = _pEBypCNa;
        "purpur-1.21.6" = _pEBypCNa;
        "purpur-1.21.7" = _pEBypCNa;
        "purpur-1.21.8" = _pEBypCNa;
        "purpur-1.21.9" = _pEBypCNa;
        "purpur-1.21.10" = _pEBypCNa;
        "purpur-1.21.11" = _pEBypCNa;
        "purpur-26.1" = _pEBypCNa;
        "purpur-26.1.1" = _pEBypCNa;
        "purpur-26.1.2" = _pEBypCNa;
        "purpur-26.2" = _pEBypCNa;
        "spigot-1.18" = _pEBypCNa;
        "spigot-1.18.1" = _pEBypCNa;
        "spigot-1.18.2" = _pEBypCNa;
        "spigot-1.19" = _pEBypCNa;
        "spigot-1.19.1" = _pEBypCNa;
        "spigot-1.19.2" = _pEBypCNa;
        "spigot-1.19.3" = _pEBypCNa;
        "spigot-1.19.4" = _pEBypCNa;
        "spigot-1.20" = _pEBypCNa;
        "spigot-1.20.1" = _pEBypCNa;
        "spigot-1.20.2" = _pEBypCNa;
        "spigot-1.20.3" = _pEBypCNa;
        "spigot-1.20.4" = _pEBypCNa;
        "spigot-1.20.5" = _pEBypCNa;
        "spigot-1.20.6" = _pEBypCNa;
        "spigot-1.21" = _pEBypCNa;
        "spigot-1.21.1" = _pEBypCNa;
        "spigot-1.21.2" = _pEBypCNa;
        "spigot-1.21.3" = _pEBypCNa;
        "spigot-1.21.4" = _pEBypCNa;
        "spigot-1.21.5" = _pEBypCNa;
        "spigot-1.21.6" = _pEBypCNa;
        "spigot-1.21.7" = _pEBypCNa;
        "spigot-1.21.8" = _pEBypCNa;
        "spigot-1.21.9" = _pEBypCNa;
        "spigot-1.21.10" = _pEBypCNa;
        "spigot-1.21.11" = _pEBypCNa;
        "spigot-26.1" = _pEBypCNa;
        "spigot-26.1.1" = _pEBypCNa;
        "spigot-26.1.2" = _pEBypCNa;
        "spigot-26.2" = _pEBypCNa;
        "pkg-6.2.0" = _PKbK9GkJ;
        "pkg-6.2.1" = _89zjdjT6;
        "pkg-6.2.2" = _yz0Jnqer;
        "pkg-6.3.0" = _OYZufJ8P;
        "pkg-6.3.1" = _K11I5h0F;
        "pkg-6.3.2" = _1ahHZ97P;
        "pkg-6.3.3" = _dAeKkIzx;
        "pkg-6.3.4" = _Cv3Ozis3;
        "pkg-6.3.5" = _8WboOC2F;
        "pkg-6.4.0" = _nJedAzdD;
        "pkg-6.5.0" = _UkqzB7sd;
        "pkg-6.5.11" = _RRrMHZKN;
        "pkg-6.5.12" = _pEBypCNa;
        "default" = _pEBypCNa;
    });
    fn = lib.prismnix.pkgs.mkVersionedModrinthPkgFn {
        name = "disenchantment";
        id = "8otGFPAu";
        type = "mod";
        versions = versions;
        meta = {
            license = lib.getLicenseFromSpdxIdOr "MIT" {
                free = false;
                deprecated = false;
                redistributable = false;
                fullName = "MIT License";
                shortName = "MIT";
                url = "https://github.com/H7KZ/Disenchantment/blob/master/LICENSE";
            };
        };
    };
in callPackage fn {}