{lib, callPackage, ...}:
let
    versions = (let
        _aVpADn66 = {
            "id" = "aVpADn66";
            "file" = "donutauction-1.0.0.jar";
            "hash" = "sha512-icXr1VwLvRQl7u9JhhsxyRwJPDa+ML39SQvpZjljVcsiYlVQg34AFfwlu+RBN3xSQa449t/8UC4m5e4zILMKLg==";
        };
        _f2BOoUGM = {
            "id" = "f2BOoUGM";
            "file" = "donutauction-1.0.1.jar";
            "hash" = "sha512-ZZm9szivT5HuTVUEcngxFYbWzVhY0WhcOq1V/Vy2FslTGEBiAFTvd1thfAiKHMAHtog9PyqQ0z65s5GZ5gLMVQ==";
        };
        _p3OLZCag = {
            "id" = "p3OLZCag";
            "file" = "donutauction-1.0.2.jar";
            "hash" = "sha512-OT9FnVVVAd/cxg6ExR6wis9ZhTzx6XKaH66sxm2PMvb5joHQeeiFvoTJON5VmW8ImHSGAuSMx+8ahv9nnVsDKQ==";
        };
        _PfrA9xKH = {
            "id" = "PfrA9xKH";
            "file" = "donutauction-1.0.3.jar";
            "hash" = "sha512-+who0UekcW/QaJs8YaHHMAMkpHU4a5c5JtKuqy8/hmZz6RqCL6AY/6x+py+iNRzFgYocjsC2iZ6Wlwl9G1iDzQ==";
        };
        _pCNipFpn = {
            "id" = "pCNipFpn";
            "file" = "donutauction-1.1.0.jar";
            "hash" = "sha512-0BJxgPcmlWeDJ/yogMsYlFvu53je7EIC6Ub/uvbFIi3KJlonTTz3RslvEoGYNByJRuSjS/b8DKoNhkkQsjnlZQ==";
        };
        _6M7etBnI = {
            "id" = "6M7etBnI";
            "file" = "donutauction-1.2.0.jar";
            "hash" = "sha512-qktjaipJ61BhTahUFbB7Axs7YR8JwallMhKcfW44O7pjIycdsSMS+3Y5i/50xsm+5NiN4r7imxVEx/U4m943EQ==";
        };
        _5iCFmev3 = {
            "id" = "5iCFmev3";
            "file" = "donutauction-1.2.1.jar";
            "hash" = "sha512-/jV8z29ZAS5dO0BK3ZMJ4FJ8zLKPe9VnVeFDtGLkl0kjJkA/eFZv8I2QG9myaOLJMZb/cqkd3ljazsUN3PYl3Q==";
        };
        _8TAYYFkh = {
            "id" = "8TAYYFkh";
            "file" = "DonutAuctionHouse-1.2.2.jar";
            "hash" = "sha512-UY6iT/M0cdGhVNOq59vgETOYti2jUwWO3/piKHpVGat95IswcQo4Fp4lSBoBkvCxTzqfRBjfoOx7geV1zCMI0Q==";
        };
        _VIt5kAs8 = {
            "id" = "VIt5kAs8";
            "file" = "donutauction-1.3.0.jar";
            "hash" = "sha512-l5HUFdzMAkeUfN0I4LDWsayhg7SyGewEgf8vmiJQKwJ4sDCd+Twou7l/cuh626H7vHNx7gGhFNVxtr9cN8o7YA==";
        };
        _atk4oxqo = {
            "id" = "atk4oxqo";
            "file" = "donutauction-1.3.1.jar";
            "hash" = "sha512-wt2T+vW6mpOZY9keZTTWYB9wwa3u8Dovusl3h3tyDR83Xa7iBg2nUpzT7Ele7NXmOG64LZasZLeS/U/vCasnpg==";
        };
        _Jk75b0r1 = {
            "id" = "Jk75b0r1";
            "file" = "DonutAuctionHouse-1.4.0.jar";
            "hash" = "sha512-vL/LCTrZ93ZxcHXZmPFdw3QBjX0i59wCxzD62TnSR/zwJhM1IbJRnIa9qgPttQYUAhoR2T7PcyFAqTGNv/ewBg==";
        };
        _2a2DnuZG = {
            "id" = "2a2DnuZG";
            "file" = "DonutAuctionHouse-1.5.0.jar";
            "hash" = "sha512-9Kia/TXZbwZ5pFd+J67GjeVLhDutBsPRI1d7SyCU8C3B1Mha0uUVngBl/j2T8Wm9aq87o5bLE9lpPvSCZMXESg==";
        };
        _qx5X0Vjg = {
            "id" = "qx5X0Vjg";
            "file" = "DonutAuctionHouse-1.5.1.jar";
            "hash" = "sha512-NK4F6URGjUTj6bLfob9Kx201Fo40k4wVEQxOeA6VU9VrBHaYRgvgKZNEW7wifJpG7HHv8sK+GtG1TgNRqGMW7g==";
        };
        _bH62NfP9 = {
            "id" = "bH62NfP9";
            "file" = "DonutAuctionHouse-1.5.2.jar";
            "hash" = "sha512-nQyGK46GdYny/o/Zut7QigCQce+dltb7NQ12KYszNnZg2yCiZ5Wi4fYrY6nO+gGKlfuXcIBo+i/GvYEHJ+a8Uw==";
        };
        _xFhXuWyO = {
            "id" = "xFhXuWyO";
            "file" = "DonutAuctionHouse-1.6.0.jar";
            "hash" = "sha512-/8fm7VwUd+wvu3TMrmk8XGhyVKavooCwRQdZLKkZwbuFl/zdezMs9Yzt63DNki5SZh1LTVsQlxilrLtS/Y78Xg==";
        };
    in {
        "aVpADn66" = _aVpADn66;
        "f2BOoUGM" = _f2BOoUGM;
        "p3OLZCag" = _p3OLZCag;
        "PfrA9xKH" = _PfrA9xKH;
        "pCNipFpn" = _pCNipFpn;
        "6M7etBnI" = _6M7etBnI;
        "5iCFmev3" = _5iCFmev3;
        "8TAYYFkh" = _8TAYYFkh;
        "VIt5kAs8" = _VIt5kAs8;
        "atk4oxqo" = _atk4oxqo;
        "Jk75b0r1" = _Jk75b0r1;
        "2a2DnuZG" = _2a2DnuZG;
        "qx5X0Vjg" = _qx5X0Vjg;
        "bH62NfP9" = _bH62NfP9;
        "xFhXuWyO" = _xFhXuWyO;
        "bukkit-1.20" = _atk4oxqo;
        "bukkit-1.20.1" = _xFhXuWyO;
        "bukkit-1.20.2" = _xFhXuWyO;
        "bukkit-1.20.3" = _xFhXuWyO;
        "bukkit-1.20.4" = _xFhXuWyO;
        "bukkit-1.20.5" = _xFhXuWyO;
        "bukkit-1.20.6" = _xFhXuWyO;
        "bukkit-1.21" = _xFhXuWyO;
        "bukkit-1.21.1" = _xFhXuWyO;
        "bukkit-1.21.2" = _xFhXuWyO;
        "bukkit-1.21.3" = _xFhXuWyO;
        "bukkit-1.21.4" = _xFhXuWyO;
        "bukkit-1.21.5" = _xFhXuWyO;
        "bukkit-1.21.6" = _xFhXuWyO;
        "bukkit-1.21.7" = _xFhXuWyO;
        "bukkit-1.21.8" = _xFhXuWyO;
        "bukkit-1.21.9" = _xFhXuWyO;
        "bukkit-1.21.10" = _xFhXuWyO;
        "bukkit-1.21.11" = _xFhXuWyO;
        "bukkit-26.1" = _xFhXuWyO;
        "bukkit-26.1.1" = _xFhXuWyO;
        "bukkit-26.1.2" = _xFhXuWyO;
        "bukkit-26.2" = _xFhXuWyO;
        "bukkit-26.3" = _xFhXuWyO;
        "folia-1.20" = _atk4oxqo;
        "folia-1.20.1" = _xFhXuWyO;
        "folia-1.20.2" = _xFhXuWyO;
        "folia-1.20.3" = _xFhXuWyO;
        "folia-1.20.4" = _xFhXuWyO;
        "folia-1.20.5" = _xFhXuWyO;
        "folia-1.20.6" = _xFhXuWyO;
        "folia-1.21" = _xFhXuWyO;
        "folia-1.21.1" = _xFhXuWyO;
        "folia-1.21.2" = _xFhXuWyO;
        "folia-1.21.3" = _xFhXuWyO;
        "folia-1.21.4" = _xFhXuWyO;
        "folia-1.21.5" = _xFhXuWyO;
        "folia-1.21.6" = _xFhXuWyO;
        "folia-1.21.7" = _xFhXuWyO;
        "folia-1.21.8" = _xFhXuWyO;
        "folia-1.21.9" = _xFhXuWyO;
        "folia-1.21.10" = _xFhXuWyO;
        "folia-1.21.11" = _xFhXuWyO;
        "folia-26.1" = _xFhXuWyO;
        "folia-26.1.1" = _xFhXuWyO;
        "folia-26.1.2" = _xFhXuWyO;
        "folia-26.2" = _xFhXuWyO;
        "folia-26.3" = _xFhXuWyO;
        "paper-1.20" = _atk4oxqo;
        "paper-1.20.1" = _xFhXuWyO;
        "paper-1.20.2" = _xFhXuWyO;
        "paper-1.20.3" = _xFhXuWyO;
        "paper-1.20.4" = _xFhXuWyO;
        "paper-1.20.5" = _xFhXuWyO;
        "paper-1.20.6" = _xFhXuWyO;
        "paper-1.21" = _xFhXuWyO;
        "paper-1.21.1" = _xFhXuWyO;
        "paper-1.21.2" = _xFhXuWyO;
        "paper-1.21.3" = _xFhXuWyO;
        "paper-1.21.4" = _xFhXuWyO;
        "paper-1.21.5" = _xFhXuWyO;
        "paper-1.21.6" = _xFhXuWyO;
        "paper-1.21.7" = _xFhXuWyO;
        "paper-1.21.8" = _xFhXuWyO;
        "paper-1.21.9" = _xFhXuWyO;
        "paper-1.21.10" = _xFhXuWyO;
        "paper-1.21.11" = _xFhXuWyO;
        "paper-26.1" = _xFhXuWyO;
        "paper-26.1.1" = _xFhXuWyO;
        "paper-26.1.2" = _xFhXuWyO;
        "paper-26.2" = _xFhXuWyO;
        "paper-26.3" = _xFhXuWyO;
        "purpur-1.20" = _atk4oxqo;
        "purpur-1.20.1" = _xFhXuWyO;
        "purpur-1.20.2" = _xFhXuWyO;
        "purpur-1.20.3" = _xFhXuWyO;
        "purpur-1.20.4" = _xFhXuWyO;
        "purpur-1.20.5" = _xFhXuWyO;
        "purpur-1.20.6" = _xFhXuWyO;
        "purpur-1.21" = _xFhXuWyO;
        "purpur-1.21.1" = _xFhXuWyO;
        "purpur-1.21.2" = _xFhXuWyO;
        "purpur-1.21.3" = _xFhXuWyO;
        "purpur-1.21.4" = _xFhXuWyO;
        "purpur-1.21.5" = _xFhXuWyO;
        "purpur-1.21.6" = _xFhXuWyO;
        "purpur-1.21.7" = _xFhXuWyO;
        "purpur-1.21.8" = _xFhXuWyO;
        "purpur-1.21.9" = _xFhXuWyO;
        "purpur-1.21.10" = _xFhXuWyO;
        "purpur-1.21.11" = _xFhXuWyO;
        "purpur-26.1" = _xFhXuWyO;
        "purpur-26.1.1" = _xFhXuWyO;
        "purpur-26.1.2" = _xFhXuWyO;
        "purpur-26.2" = _xFhXuWyO;
        "purpur-26.3" = _xFhXuWyO;
        "spigot-1.20" = _atk4oxqo;
        "spigot-1.20.1" = _xFhXuWyO;
        "spigot-1.20.2" = _xFhXuWyO;
        "spigot-1.20.3" = _xFhXuWyO;
        "spigot-1.20.4" = _xFhXuWyO;
        "spigot-1.20.5" = _xFhXuWyO;
        "spigot-1.20.6" = _xFhXuWyO;
        "spigot-1.21" = _xFhXuWyO;
        "spigot-1.21.1" = _xFhXuWyO;
        "spigot-1.21.2" = _xFhXuWyO;
        "spigot-1.21.3" = _xFhXuWyO;
        "spigot-1.21.4" = _xFhXuWyO;
        "spigot-1.21.5" = _xFhXuWyO;
        "spigot-1.21.6" = _xFhXuWyO;
        "spigot-1.21.7" = _xFhXuWyO;
        "spigot-1.21.8" = _xFhXuWyO;
        "spigot-1.21.9" = _xFhXuWyO;
        "spigot-1.21.10" = _xFhXuWyO;
        "spigot-1.21.11" = _xFhXuWyO;
        "spigot-26.1" = _xFhXuWyO;
        "spigot-26.1.1" = _xFhXuWyO;
        "spigot-26.1.2" = _xFhXuWyO;
        "spigot-26.2" = _xFhXuWyO;
        "spigot-26.3" = _xFhXuWyO;
        "pkg-1.0.0" = _aVpADn66;
        "pkg-1.0.1" = _f2BOoUGM;
        "pkg-1.0.2" = _p3OLZCag;
        "pkg-1.0.3" = _PfrA9xKH;
        "pkg-1.1.0" = _pCNipFpn;
        "pkg-1.2.0" = _6M7etBnI;
        "pkg-1.2.1" = _5iCFmev3;
        "pkg-1.2.2" = _8TAYYFkh;
        "pkg-1.3.0" = _VIt5kAs8;
        "pkg-1.3.1" = _atk4oxqo;
        "pkg-1.4.0" = _Jk75b0r1;
        "pkg-1.5.0" = _2a2DnuZG;
        "pkg-1.5.1" = _qx5X0Vjg;
        "pkg-1.5.2" = _bH62NfP9;
        "pkg-1.6.0" = _xFhXuWyO;
        "default" = _xFhXuWyO;
    });
    fn = lib.prismnix.pkgs.mkVersionedModrinthPkgFn {
        name = "donut-auction";
        id = "8XgyeSRH";
        type = "mod";
        versions = versions;
        meta = {
            license = lib.getLicenseFromSpdxIdOr "Apache-2.0" {
                free = false;
                deprecated = false;
                redistributable = false;
                fullName = "Apache License 2.0";
                shortName = "Apache-2.0";
                url = null;
            };
        };
    };
in callPackage fn {}