{lib, callPackage, ...}:
let
    versions = (let
        _NRHLmGlU = {
            "id" = "NRHLmGlU";
            "file" = "Ishowspeed Totem (my mom is kinda homeless edition).zip";
            "hash" = "sha512-9pkWT2GI0fahMgXv3jV9I39WyjZo9EB7NjquOQXzsGyDwb00pErYDxncc0GBwAhO+nrmr9gD7YBtlkdyQdp1kQ==";
        };
        _3NffkpcJ = {
            "id" = "3NffkpcJ";
            "file" = "Ishowspeed Totem (my mom is kinda homeless edition) (1.16-1.21.11).zip";
            "hash" = "sha512-9pkWT2GI0fahMgXv3jV9I39WyjZo9EB7NjquOQXzsGyDwb00pErYDxncc0GBwAhO+nrmr9gD7YBtlkdyQdp1kQ==";
        };
        _QwsLa7WF = {
            "id" = "QwsLa7WF";
            "file" = "Ishowspeed Totem (my mom is kinda homeless edition) (26.1).zip";
            "hash" = "sha512-kqHXUBnarEMw4fqrYyktbmT1IBegZist99a5bCXwYTaiUyFVUHlL/YiQIWt1qFS0w0fIOLGi8pMII+aFXRFO4Q==";
        };
        _Zf0Hn2mF = {
            "id" = "Zf0Hn2mF";
            "file" = "Ishowspeed Totem (my mom is kinda homeless edition)-1.17-26.2.zip";
            "hash" = "sha512-CvaElyUOt7yK+/RagO0o89qGkXgdU+IVQU/aby/PooXltkQxFsYJV+kzfRh7S6e0nzPV2qDBuQ+m30TEBhPyaw==";
        };
        _xAbleQSM = {
            "id" = "xAbleQSM";
            "file" = "Ishowspeed Totem-1.17-26.3.zip";
            "hash" = "sha512-CvaElyUOt7yK+/RagO0o89qGkXgdU+IVQU/aby/PooXltkQxFsYJV+kzfRh7S6e0nzPV2qDBuQ+m30TEBhPyaw==";
        };
    in {
        "NRHLmGlU" = _NRHLmGlU;
        "3NffkpcJ" = _3NffkpcJ;
        "QwsLa7WF" = _QwsLa7WF;
        "Zf0Hn2mF" = _Zf0Hn2mF;
        "xAbleQSM" = _xAbleQSM;
        "minecraft-1.16" = _QwsLa7WF;
        "minecraft-1.16.1" = _QwsLa7WF;
        "minecraft-1.16.2" = _QwsLa7WF;
        "minecraft-1.16.3" = _QwsLa7WF;
        "minecraft-1.16.4" = _QwsLa7WF;
        "minecraft-1.16.5" = _QwsLa7WF;
        "minecraft-1.17" = _xAbleQSM;
        "minecraft-1.17.1" = _xAbleQSM;
        "minecraft-1.18" = _xAbleQSM;
        "minecraft-1.18.1" = _xAbleQSM;
        "minecraft-1.18.2" = _xAbleQSM;
        "minecraft-1.19" = _xAbleQSM;
        "minecraft-1.19.1" = _xAbleQSM;
        "minecraft-1.19.2" = _xAbleQSM;
        "minecraft-1.19.3" = _xAbleQSM;
        "minecraft-1.19.4" = _xAbleQSM;
        "minecraft-1.20" = _xAbleQSM;
        "minecraft-1.20.1" = _xAbleQSM;
        "minecraft-1.20.2" = _xAbleQSM;
        "minecraft-1.20.3" = _xAbleQSM;
        "minecraft-1.20.4" = _xAbleQSM;
        "minecraft-1.20.5" = _xAbleQSM;
        "minecraft-1.20.6" = _xAbleQSM;
        "minecraft-1.21" = _xAbleQSM;
        "minecraft-1.21.1" = _xAbleQSM;
        "minecraft-1.21.2" = _xAbleQSM;
        "minecraft-1.21.3" = _xAbleQSM;
        "minecraft-1.21.4" = _xAbleQSM;
        "minecraft-1.21.5" = _xAbleQSM;
        "minecraft-1.21.6" = _xAbleQSM;
        "minecraft-1.21.7" = _xAbleQSM;
        "minecraft-1.21.8" = _xAbleQSM;
        "minecraft-1.21.9" = _xAbleQSM;
        "minecraft-1.21.10" = _xAbleQSM;
        "minecraft-25w41a" = _3NffkpcJ;
        "minecraft-25w42a" = _3NffkpcJ;
        "minecraft-25w43a" = _3NffkpcJ;
        "minecraft-25w44a" = _3NffkpcJ;
        "minecraft-25w45a" = _3NffkpcJ;
        "minecraft-25w46a" = _3NffkpcJ;
        "minecraft-1.21.11-pre1" = _3NffkpcJ;
        "minecraft-1.21.11-pre2" = _3NffkpcJ;
        "minecraft-1.21.11-pre3" = _3NffkpcJ;
        "minecraft-1.21.11-pre4" = _3NffkpcJ;
        "minecraft-1.21.11-pre5" = _3NffkpcJ;
        "minecraft-1.21.11-rc1" = _3NffkpcJ;
        "minecraft-1.21.11-rc2" = _3NffkpcJ;
        "minecraft-1.21.11-rc3" = _3NffkpcJ;
        "minecraft-1.21.11" = _xAbleQSM;
        "minecraft-1.13" = _QwsLa7WF;
        "minecraft-1.13.1" = _QwsLa7WF;
        "minecraft-1.13.2" = _QwsLa7WF;
        "minecraft-1.14" = _QwsLa7WF;
        "minecraft-1.14.1" = _QwsLa7WF;
        "minecraft-1.14.2" = _QwsLa7WF;
        "minecraft-1.14.3" = _QwsLa7WF;
        "minecraft-1.14.4" = _QwsLa7WF;
        "minecraft-1.15" = _QwsLa7WF;
        "minecraft-1.15.1" = _QwsLa7WF;
        "minecraft-1.15.2" = _QwsLa7WF;
        "minecraft-26.1" = _xAbleQSM;
        "minecraft-26.1.1" = _xAbleQSM;
        "minecraft-26.1.2" = _xAbleQSM;
        "minecraft-26.2" = _xAbleQSM;
        "minecraft-22w42a" = _xAbleQSM;
        "minecraft-22w43a" = _xAbleQSM;
        "minecraft-22w44a" = _xAbleQSM;
        "minecraft-23w14a" = _xAbleQSM;
        "minecraft-23w16a" = _xAbleQSM;
        "minecraft-23w31a" = _xAbleQSM;
        "minecraft-23w32a" = _xAbleQSM;
        "minecraft-23w33a" = _xAbleQSM;
        "minecraft-23w35a" = _xAbleQSM;
        "minecraft-1.20.2-pre1" = _xAbleQSM;
        "minecraft-23w42a" = _xAbleQSM;
        "minecraft-23w43a" = _xAbleQSM;
        "minecraft-23w43b" = _xAbleQSM;
        "minecraft-23w44a" = _xAbleQSM;
        "minecraft-23w45a" = _xAbleQSM;
        "minecraft-23w46a" = _xAbleQSM;
        "minecraft-24w03a" = _xAbleQSM;
        "minecraft-24w03b" = _xAbleQSM;
        "minecraft-24w04a" = _xAbleQSM;
        "minecraft-24w05a" = _xAbleQSM;
        "minecraft-24w05b" = _xAbleQSM;
        "minecraft-24w06a" = _xAbleQSM;
        "minecraft-24w07a" = _xAbleQSM;
        "minecraft-24w09a" = _xAbleQSM;
        "minecraft-24w10a" = _xAbleQSM;
        "minecraft-24w11a" = _xAbleQSM;
        "minecraft-24w12a" = _xAbleQSM;
        "minecraft-24w13a" = _xAbleQSM;
        "minecraft-24w14potato" = _xAbleQSM;
        "minecraft-24w14a" = _xAbleQSM;
        "minecraft-1.20.5-pre1" = _xAbleQSM;
        "minecraft-1.20.5-pre2" = _xAbleQSM;
        "minecraft-1.20.5-pre3" = _xAbleQSM;
        "minecraft-24w18a" = _xAbleQSM;
        "minecraft-24w19a" = _xAbleQSM;
        "minecraft-24w19b" = _xAbleQSM;
        "minecraft-24w20a" = _xAbleQSM;
        "minecraft-24w33a" = _xAbleQSM;
        "minecraft-24w34a" = _xAbleQSM;
        "minecraft-24w35a" = _xAbleQSM;
        "minecraft-24w36a" = _xAbleQSM;
        "minecraft-24w37a" = _xAbleQSM;
        "minecraft-24w38a" = _xAbleQSM;
        "minecraft-24w39a" = _xAbleQSM;
        "minecraft-24w40a" = _xAbleQSM;
        "minecraft-1.21.2-pre1" = _xAbleQSM;
        "minecraft-1.21.2-pre2" = _xAbleQSM;
        "minecraft-24w44a" = _xAbleQSM;
        "minecraft-24w45a" = _xAbleQSM;
        "minecraft-24w46a" = _xAbleQSM;
        "minecraft-26.3" = _xAbleQSM;
        "pkg-1.0" = _xAbleQSM;
        "default" = _xAbleQSM;
    });
    fn = lib.prismnix.pkgs.mkVersionedModrinthPkgFn {
        name = "ishowspeed-totem-(my-mom-is-kinda-homeless)";
        id = "Bq8S2e97";
        type = "resourcepack";
        versions = versions;
        meta = {
            license = lib.getLicenseFromSpdxIdOr "LicenseRef-All-Rights-Reserved" {
                free = false;
                deprecated = false;
                redistributable = false;
                fullName = "LicenseRef-All-Rights-Reserved";
                shortName = "LicenseRef-All-Rights-Reserved";
                url = null;
            };
        };
    };
in callPackage fn {}