{lib, callPackage, ...}:
let
    versions = (let
        _LtrWtuQe = {
            "id" = "LtrWtuQe";
            "file" = "Deeper MC v1.0 1.21.8.zip";
            "hash" = "sha512-jByMuCtDxIRb7GMYBamv9Xd7/qkExv7ErWkGuh6mTlG7N92fAb2sr2JnnKz2xddE7UOBibAopjJCL1h9J1nJEA==";
        };
        _CMW3a2Ew = {
            "id" = "CMW3a2Ew";
            "file" = "Deeper MC v1.1 1.21.11.zip";
            "hash" = "sha512-MCBhHzIPxzj0medX4l8rrbFPR3XrSmtNQDf359j+EQsD8K6A8YPoaVPnWaYlsPYTCw5wKoF5c7C4oKFn7z4MGA==";
        };
        _JtqixxZk = {
            "id" = "JtqixxZk";
            "file" = "Deeper MC v2.0 26.2.zip";
            "hash" = "sha512-zr/+3FibxOPrhY5Sg4J4KdQBMLDFeW70pt6zQiZlZ8Xk4l0l3FWpF15R/BDOI/GpHKAq2nt83apdYtvaZvwLvw==";
        };
    in {
        "LtrWtuQe" = _LtrWtuQe;
        "CMW3a2Ew" = _CMW3a2Ew;
        "JtqixxZk" = _JtqixxZk;
        "minecraft-1.14" = _JtqixxZk;
        "minecraft-1.14.1" = _JtqixxZk;
        "minecraft-1.14.2" = _JtqixxZk;
        "minecraft-1.14.3" = _JtqixxZk;
        "minecraft-1.14.4" = _JtqixxZk;
        "minecraft-1.15" = _JtqixxZk;
        "minecraft-1.15.1" = _JtqixxZk;
        "minecraft-1.15.2" = _JtqixxZk;
        "minecraft-1.16" = _JtqixxZk;
        "minecraft-1.16.1" = _JtqixxZk;
        "minecraft-1.16.2" = _JtqixxZk;
        "minecraft-1.16.3" = _JtqixxZk;
        "minecraft-1.16.4" = _JtqixxZk;
        "minecraft-1.16.5" = _JtqixxZk;
        "minecraft-1.17" = _JtqixxZk;
        "minecraft-1.17.1" = _JtqixxZk;
        "minecraft-1.18" = _JtqixxZk;
        "minecraft-1.18.1" = _JtqixxZk;
        "minecraft-1.18.2" = _JtqixxZk;
        "minecraft-1.19" = _JtqixxZk;
        "minecraft-1.19.1" = _JtqixxZk;
        "minecraft-1.19.2" = _JtqixxZk;
        "minecraft-1.19.3" = _JtqixxZk;
        "minecraft-1.19.4" = _JtqixxZk;
        "minecraft-1.20" = _JtqixxZk;
        "minecraft-1.20.1" = _JtqixxZk;
        "minecraft-1.20.2" = _JtqixxZk;
        "minecraft-1.20.3" = _JtqixxZk;
        "minecraft-1.20.4" = _JtqixxZk;
        "minecraft-1.20.5" = _JtqixxZk;
        "minecraft-1.20.6" = _JtqixxZk;
        "minecraft-1.21" = _JtqixxZk;
        "minecraft-1.21.1" = _JtqixxZk;
        "minecraft-1.21.2" = _JtqixxZk;
        "minecraft-1.21.3" = _JtqixxZk;
        "minecraft-1.21.4" = _JtqixxZk;
        "minecraft-1.21.5" = _JtqixxZk;
        "minecraft-1.21.6" = _JtqixxZk;
        "minecraft-1.21.7" = _JtqixxZk;
        "minecraft-1.21.8" = _JtqixxZk;
        "minecraft-1.21.9" = _JtqixxZk;
        "minecraft-1.21.10" = _JtqixxZk;
        "minecraft-1.21.11" = _JtqixxZk;
        "minecraft-23w31a" = _JtqixxZk;
        "minecraft-23w32a" = _JtqixxZk;
        "minecraft-23w33a" = _JtqixxZk;
        "minecraft-23w35a" = _JtqixxZk;
        "minecraft-1.20.2-pre1" = _JtqixxZk;
        "minecraft-23w42a" = _JtqixxZk;
        "minecraft-23w43a" = _JtqixxZk;
        "minecraft-23w43b" = _JtqixxZk;
        "minecraft-23w44a" = _JtqixxZk;
        "minecraft-23w45a" = _JtqixxZk;
        "minecraft-23w46a" = _JtqixxZk;
        "minecraft-24w03a" = _JtqixxZk;
        "minecraft-24w03b" = _JtqixxZk;
        "minecraft-24w04a" = _JtqixxZk;
        "minecraft-24w05a" = _JtqixxZk;
        "minecraft-24w05b" = _JtqixxZk;
        "minecraft-24w06a" = _JtqixxZk;
        "minecraft-24w07a" = _JtqixxZk;
        "minecraft-24w09a" = _JtqixxZk;
        "minecraft-24w10a" = _JtqixxZk;
        "minecraft-24w11a" = _JtqixxZk;
        "minecraft-24w12a" = _JtqixxZk;
        "minecraft-24w13a" = _JtqixxZk;
        "minecraft-24w14potato" = _JtqixxZk;
        "minecraft-24w14a" = _JtqixxZk;
        "minecraft-1.20.5-pre1" = _JtqixxZk;
        "minecraft-1.20.5-pre2" = _JtqixxZk;
        "minecraft-1.20.5-pre3" = _JtqixxZk;
        "minecraft-24w18a" = _JtqixxZk;
        "minecraft-24w19a" = _JtqixxZk;
        "minecraft-24w19b" = _JtqixxZk;
        "minecraft-24w20a" = _JtqixxZk;
        "minecraft-24w33a" = _JtqixxZk;
        "minecraft-24w34a" = _JtqixxZk;
        "minecraft-24w35a" = _JtqixxZk;
        "minecraft-24w36a" = _JtqixxZk;
        "minecraft-24w37a" = _JtqixxZk;
        "minecraft-24w38a" = _JtqixxZk;
        "minecraft-24w39a" = _JtqixxZk;
        "minecraft-24w40a" = _JtqixxZk;
        "minecraft-1.21.2-pre1" = _JtqixxZk;
        "minecraft-1.21.2-pre2" = _JtqixxZk;
        "minecraft-24w44a" = _JtqixxZk;
        "minecraft-24w45a" = _JtqixxZk;
        "minecraft-24w46a" = _JtqixxZk;
        "minecraft-26.1" = _JtqixxZk;
        "minecraft-26.1.1" = _JtqixxZk;
        "minecraft-26.1.2" = _JtqixxZk;
        "minecraft-26.2" = _JtqixxZk;
        "pkg-1.0" = _LtrWtuQe;
        "pkg-1.1" = _CMW3a2Ew;
        "pkg-2.0" = _JtqixxZk;
        "default" = _JtqixxZk;
    });
    fn = lib.prismnix.pkgs.mkVersionedModrinthPkgFn {
        name = "deeper-mc";
        id = "eK9yQLpt";
        type = "resourcepack";
        versions = versions;
        meta = {
            license = lib.getLicenseFromSpdxIdOr "LicenseRef-All-Rights-Reserved" {
                free = false;
                deprecated = false;
                redistributable = false;
                fullName = "LicenseRef-All-Rights-Reserved";
                shortName = "LicenseRef-All-Rights-Reserved";
                url = null;
            };
        };
    };
in callPackage fn {}