{lib, callPackage, ...}:
let
    versions = (let
        _VXWXUEVR = {
            "id" = "VXWXUEVR";
            "file" = "DonutShop-1.4.1-SNAPSHOT.jar";
            "hash" = "sha512-yD7f4Lcn1gspekRGu+9OGGt0tJ/h719EpSOptEnMjrDbLL0BGlj9yuJ4m5p1gpvY1mZ1SLxl3/ygbLu8KFApig==";
        };
        _gtfpEHtL = {
            "id" = "gtfpEHtL";
            "file" = "DonutShop-1.4.3-SNAPSHOT.jar";
            "hash" = "sha512-bnjm7hSFMpN9msDIftmOQrXwZZ1ni0UmvzLJlbM+jPWf5Vg4Z/zFFTcbhAlS1lJVPm8WZIHsKYN1wgJRobga0Q==";
        };
        _F24j3njP = {
            "id" = "F24j3njP";
            "file" = "DonutShop-1.5.3-SNAPSHOT.jar";
            "hash" = "sha512-aqeIfw11XlQW8xsCYS4uGe6JTxT08cfVNmXSWg0AZJqzdcXsmVYSjXYqZnlqSAYfYJ3Wd3Tw/1OQOldGHToAVw==";
        };
        _K0VwQJsY = {
            "id" = "K0VwQJsY";
            "file" = "DonutShop-1.5.4-SNAPSHOT.jar";
            "hash" = "sha512-S6ui+lAChET9cgttVYDJcof2qXN/w2t61GNIxj/Do7ND+46/KbiWyjEiDu366L0j2z6GQ4TfDb4VZMaQRlpFcA==";
        };
        _RMHgELKd = {
            "id" = "RMHgELKd";
            "file" = "DonutShop-1.5.5-SNAPSHOT.jar";
            "hash" = "sha512-m/EPdxdasJdBDQRC+TrQ5xZDZgXAyXjmtkrhghHm75Ia8OGTUoE9pRpk6i9PKpAvtJvsyb0bb341VFHsigFSEw==";
        };
        _IpzQbNlf = {
            "id" = "IpzQbNlf";
            "file" = "DonutShop-1.5.6-SNAPSHOT.jar";
            "hash" = "sha512-1JErpeaaCoDnYNIkUfn+zNRHkG2Yj292m8eRBqG3HhDSOI+DKEiyR2wP+1VseAOZLHs/LXVpOoLk0C+ZZhc60Q==";
        };
    in {
        "VXWXUEVR" = _VXWXUEVR;
        "gtfpEHtL" = _gtfpEHtL;
        "F24j3njP" = _F24j3njP;
        "K0VwQJsY" = _K0VwQJsY;
        "RMHgELKd" = _RMHgELKd;
        "IpzQbNlf" = _IpzQbNlf;
        "bukkit-1.21" = _IpzQbNlf;
        "bukkit-1.21.1" = _IpzQbNlf;
        "bukkit-1.21.2" = _IpzQbNlf;
        "bukkit-1.21.3" = _IpzQbNlf;
        "bukkit-1.21.4" = _IpzQbNlf;
        "bukkit-1.21.5" = _IpzQbNlf;
        "bukkit-1.21.6" = _IpzQbNlf;
        "bukkit-1.21.7" = _IpzQbNlf;
        "bukkit-1.21.8" = _IpzQbNlf;
        "bukkit-1.21.9" = _IpzQbNlf;
        "bukkit-1.21.10" = _IpzQbNlf;
        "bukkit-1.21.11" = _IpzQbNlf;
        "bukkit-26.1" = _IpzQbNlf;
        "bukkit-26.1.1" = _IpzQbNlf;
        "bukkit-26.1.2" = _IpzQbNlf;
        "bukkit-26.2" = _IpzQbNlf;
        "bungeecord-1.21" = _IpzQbNlf;
        "bungeecord-1.21.1" = _IpzQbNlf;
        "bungeecord-1.21.2" = _IpzQbNlf;
        "bungeecord-1.21.3" = _IpzQbNlf;
        "bungeecord-1.21.4" = _IpzQbNlf;
        "bungeecord-1.21.5" = _IpzQbNlf;
        "bungeecord-1.21.6" = _IpzQbNlf;
        "bungeecord-1.21.7" = _IpzQbNlf;
        "bungeecord-1.21.8" = _IpzQbNlf;
        "bungeecord-1.21.9" = _IpzQbNlf;
        "bungeecord-1.21.10" = _IpzQbNlf;
        "bungeecord-1.21.11" = _IpzQbNlf;
        "bungeecord-26.1" = _IpzQbNlf;
        "bungeecord-26.1.1" = _IpzQbNlf;
        "bungeecord-26.1.2" = _IpzQbNlf;
        "bungeecord-26.2" = _IpzQbNlf;
        "folia-1.21" = _VXWXUEVR;
        "folia-1.21.1" = _VXWXUEVR;
        "folia-1.21.2" = _VXWXUEVR;
        "folia-1.21.3" = _VXWXUEVR;
        "folia-1.21.4" = _VXWXUEVR;
        "folia-1.21.5" = _VXWXUEVR;
        "folia-1.21.6" = _VXWXUEVR;
        "folia-1.21.7" = _VXWXUEVR;
        "folia-1.21.8" = _VXWXUEVR;
        "folia-1.21.9" = _VXWXUEVR;
        "folia-1.21.10" = _VXWXUEVR;
        "folia-1.21.11" = _VXWXUEVR;
        "folia-26.1" = _VXWXUEVR;
        "folia-26.1.1" = _VXWXUEVR;
        "folia-26.1.2" = _VXWXUEVR;
        "paper-1.21" = _IpzQbNlf;
        "paper-1.21.1" = _IpzQbNlf;
        "paper-1.21.2" = _IpzQbNlf;
        "paper-1.21.3" = _IpzQbNlf;
        "paper-1.21.4" = _IpzQbNlf;
        "paper-1.21.5" = _IpzQbNlf;
        "paper-1.21.6" = _IpzQbNlf;
        "paper-1.21.7" = _IpzQbNlf;
        "paper-1.21.8" = _IpzQbNlf;
        "paper-1.21.9" = _IpzQbNlf;
        "paper-1.21.10" = _IpzQbNlf;
        "paper-1.21.11" = _IpzQbNlf;
        "paper-26.1" = _IpzQbNlf;
        "paper-26.1.1" = _IpzQbNlf;
        "paper-26.1.2" = _IpzQbNlf;
        "paper-26.2" = _IpzQbNlf;
        "purpur-1.21" = _IpzQbNlf;
        "purpur-1.21.1" = _IpzQbNlf;
        "purpur-1.21.2" = _IpzQbNlf;
        "purpur-1.21.3" = _IpzQbNlf;
        "purpur-1.21.4" = _IpzQbNlf;
        "purpur-1.21.5" = _IpzQbNlf;
        "purpur-1.21.6" = _IpzQbNlf;
        "purpur-1.21.7" = _IpzQbNlf;
        "purpur-1.21.8" = _IpzQbNlf;
        "purpur-1.21.9" = _IpzQbNlf;
        "purpur-1.21.10" = _IpzQbNlf;
        "purpur-1.21.11" = _IpzQbNlf;
        "purpur-26.1" = _IpzQbNlf;
        "purpur-26.1.1" = _IpzQbNlf;
        "purpur-26.1.2" = _IpzQbNlf;
        "purpur-26.2" = _IpzQbNlf;
        "spigot-1.21" = _IpzQbNlf;
        "spigot-1.21.1" = _IpzQbNlf;
        "spigot-1.21.2" = _IpzQbNlf;
        "spigot-1.21.3" = _IpzQbNlf;
        "spigot-1.21.4" = _IpzQbNlf;
        "spigot-1.21.5" = _IpzQbNlf;
        "spigot-1.21.6" = _IpzQbNlf;
        "spigot-1.21.7" = _IpzQbNlf;
        "spigot-1.21.8" = _IpzQbNlf;
        "spigot-1.21.9" = _IpzQbNlf;
        "spigot-1.21.10" = _IpzQbNlf;
        "spigot-1.21.11" = _IpzQbNlf;
        "spigot-26.1" = _IpzQbNlf;
        "spigot-26.1.1" = _IpzQbNlf;
        "spigot-26.1.2" = _IpzQbNlf;
        "spigot-26.2" = _IpzQbNlf;
        "pkg-1.4.1-SNAPSHOT" = _VXWXUEVR;
        "pkg-1.4.3-SNAPSHOT" = _gtfpEHtL;
        "pkg-1.5.3-SNAPSHOT" = _F24j3njP;
        "pkg-1.5.4-SNAPSHOT" = _K0VwQJsY;
        "pkg-1.5.5-SNAPSHOT" = _RMHgELKd;
        "pkg-1.5.6-SNAPSHOT" = _IpzQbNlf;
        "default" = _IpzQbNlf;
    });
    fn = lib.prismnix.pkgs.mkVersionedModrinthPkgFn {
        name = "donut--shop";
        id = "eTYcGc1j";
        type = "mod";
        versions = versions;
        meta = {
            license = lib.getLicenseFromSpdxIdOr "MIT" {
                free = false;
                deprecated = false;
                redistributable = false;
                fullName = "MIT License";
                shortName = "MIT";
                url = null;
            };
        };
    };
in callPackage fn {}