{lib, callPackage, ...}:
let
    versions = (let
        _zx4REyru = {
            "id" = "zx4REyru";
            "file" = "Ginkgo Font.zip";
            "hash" = "sha512-1S2r0Bytpa30sLNz2DXdeZ450X88oGhTB/Yc0el9ek7Qr4ToMCrB5b/H0ZVW1sYi9SfUce/huaBuPuEIYn2XFQ==";
        };
        _Yx8UL1xp = {
            "id" = "Yx8UL1xp";
            "file" = "Ginkgo Font - ALT.zip";
            "hash" = "sha512-7UuAzxaeVfZHKvq0FMZ0ZSjUUGq+nEQyfcQh0JoAIz4RGf7ii6w1HEYECHoTgUFjqKTrLB1cHMEpET+aWJneBw==";
        };
        _9Z1ATvGs = {
            "id" = "9Z1ATvGs";
            "file" = "Ginkgo Font.zip";
            "hash" = "sha512-RWdeUeRg9lWJpoxbDk9IbKbx2S3GelY7cQd8gtozns3E6saS+v9eVTtF1zvvsO5Jw5X3TCC3D9sJpJapHrawbA==";
        };
        _NmwMQKvc = {
            "id" = "NmwMQKvc";
            "file" = "Ginkgo Font - ALT.zip";
            "hash" = "sha512-9GVBpaIJ6dzSv2V1Mq/vnSzFEZ9r/eEDslqVA2fMiY1GrvOAh8tBdFE0nGVfw2NMwsvyHtnrjohkDRDFDWiYYg==";
        };
        _HPprBsij = {
            "id" = "HPprBsij";
            "file" = "Ginkgo Font.zip";
            "hash" = "sha512-NVcRIODzmAwiJ2tULsuc+paNNfY3Dl0YjbCl12F/9t865y3/JHpYHnxKsIFhnlSejDU5yhWyCS+LbTXh7RgpTg==";
        };
        _RAKggsm3 = {
            "id" = "RAKggsm3";
            "file" = "Ginkgo Font - ALT.zip";
            "hash" = "sha512-nJ3E4d7Lqk2OHLisP625Lt08aWOcSymuJoFiys0K1wbeCf9oKMaWOWuO7stvz8uiV5i+xdXqM8vwBW01xvID6Q==";
        };
        _KRxgVuYg = {
            "id" = "KRxgVuYg";
            "file" = "Ginkgo Font.zip";
            "hash" = "sha512-4HBDGyYP0eL59SgGZi+QD5cgMUwQ2SZm3qb8MDvsPFl0OgP0rh4+ydJRfbMweDshCSxDE+TgIP41df3hhV34EA==";
        };
        _uuB5nDbt = {
            "id" = "uuB5nDbt";
            "file" = "Ginkgo Font - ALT.zip";
            "hash" = "sha512-d7AI+TIdbTjVwzt55KAArirZAIRiDOPoMaTYzOh26qlNMSmvqWqmBWbFF4+pVCASCX2UNTGqjOqUQo+DHMixtg==";
        };
        _IIOdz1fy = {
            "id" = "IIOdz1fy";
            "file" = "Ginkgo Font.zip";
            "hash" = "sha512-GQA/3UxicM7vv9X61myTgYvDQ2V28jm+RSleQ0XsP7A6/bvj3ZtiCnn5m7FohXjWY9HFU0LoYox+7fK5mQE4sw==";
        };
    in {
        "zx4REyru" = _zx4REyru;
        "Yx8UL1xp" = _Yx8UL1xp;
        "9Z1ATvGs" = _9Z1ATvGs;
        "NmwMQKvc" = _NmwMQKvc;
        "HPprBsij" = _HPprBsij;
        "RAKggsm3" = _RAKggsm3;
        "KRxgVuYg" = _KRxgVuYg;
        "uuB5nDbt" = _uuB5nDbt;
        "IIOdz1fy" = _IIOdz1fy;
        "minecraft-1.19" = _IIOdz1fy;
        "minecraft-1.19.1" = _IIOdz1fy;
        "minecraft-1.19.2" = _IIOdz1fy;
        "minecraft-1.19.3" = _IIOdz1fy;
        "minecraft-1.19.4" = _IIOdz1fy;
        "minecraft-1.20" = _IIOdz1fy;
        "minecraft-1.20.1" = _IIOdz1fy;
        "minecraft-1.20.2" = _IIOdz1fy;
        "minecraft-1.20.3" = _IIOdz1fy;
        "minecraft-1.20.4" = _IIOdz1fy;
        "minecraft-1.20.5" = _IIOdz1fy;
        "minecraft-1.20.6" = _IIOdz1fy;
        "minecraft-1.21" = _IIOdz1fy;
        "minecraft-1.21.1" = _IIOdz1fy;
        "minecraft-1.21.2" = _IIOdz1fy;
        "minecraft-1.21.3" = _IIOdz1fy;
        "minecraft-1.12" = _IIOdz1fy;
        "minecraft-1.12.1" = _IIOdz1fy;
        "minecraft-1.12.2" = _IIOdz1fy;
        "minecraft-1.13" = _IIOdz1fy;
        "minecraft-1.13.1" = _IIOdz1fy;
        "minecraft-1.13.2" = _IIOdz1fy;
        "minecraft-1.14" = _IIOdz1fy;
        "minecraft-1.14.1" = _IIOdz1fy;
        "minecraft-1.14.2" = _IIOdz1fy;
        "minecraft-1.14.3" = _IIOdz1fy;
        "minecraft-1.14.4" = _IIOdz1fy;
        "minecraft-1.15" = _IIOdz1fy;
        "minecraft-1.15.1" = _IIOdz1fy;
        "minecraft-1.15.2" = _IIOdz1fy;
        "minecraft-1.16" = _IIOdz1fy;
        "minecraft-1.16.1" = _IIOdz1fy;
        "minecraft-1.16.2" = _IIOdz1fy;
        "minecraft-1.16.3" = _IIOdz1fy;
        "minecraft-1.16.4" = _IIOdz1fy;
        "minecraft-1.16.5" = _IIOdz1fy;
        "minecraft-1.17" = _IIOdz1fy;
        "minecraft-1.17.1" = _IIOdz1fy;
        "minecraft-1.18" = _IIOdz1fy;
        "minecraft-1.18.1" = _IIOdz1fy;
        "minecraft-1.18.2" = _IIOdz1fy;
        "minecraft-22w42a" = _uuB5nDbt;
        "minecraft-22w43a" = _uuB5nDbt;
        "minecraft-22w44a" = _uuB5nDbt;
        "minecraft-23w14a" = _uuB5nDbt;
        "minecraft-23w16a" = _uuB5nDbt;
        "minecraft-23w31a" = _uuB5nDbt;
        "minecraft-23w32a" = _uuB5nDbt;
        "minecraft-23w33a" = _uuB5nDbt;
        "minecraft-23w35a" = _uuB5nDbt;
        "minecraft-1.20.2-pre1" = _uuB5nDbt;
        "minecraft-23w42a" = _uuB5nDbt;
        "minecraft-23w43a" = _uuB5nDbt;
        "minecraft-23w43b" = _uuB5nDbt;
        "minecraft-23w44a" = _uuB5nDbt;
        "minecraft-23w45a" = _uuB5nDbt;
        "minecraft-23w46a" = _uuB5nDbt;
        "minecraft-24w03a" = _uuB5nDbt;
        "minecraft-24w03b" = _uuB5nDbt;
        "minecraft-24w04a" = _uuB5nDbt;
        "minecraft-24w05a" = _uuB5nDbt;
        "minecraft-24w05b" = _uuB5nDbt;
        "minecraft-24w06a" = _uuB5nDbt;
        "minecraft-24w07a" = _uuB5nDbt;
        "minecraft-24w09a" = _uuB5nDbt;
        "minecraft-24w10a" = _uuB5nDbt;
        "minecraft-24w11a" = _uuB5nDbt;
        "minecraft-24w12a" = _uuB5nDbt;
        "minecraft-24w13a" = _uuB5nDbt;
        "minecraft-24w14potato" = _uuB5nDbt;
        "minecraft-24w14a" = _uuB5nDbt;
        "minecraft-1.20.5-pre1" = _uuB5nDbt;
        "minecraft-1.20.5-pre2" = _uuB5nDbt;
        "minecraft-1.20.5-pre3" = _uuB5nDbt;
        "minecraft-24w18a" = _uuB5nDbt;
        "minecraft-24w19a" = _uuB5nDbt;
        "minecraft-24w19b" = _uuB5nDbt;
        "minecraft-24w20a" = _uuB5nDbt;
        "minecraft-24w33a" = _uuB5nDbt;
        "minecraft-24w34a" = _uuB5nDbt;
        "minecraft-24w35a" = _uuB5nDbt;
        "minecraft-24w36a" = _uuB5nDbt;
        "minecraft-24w37a" = _uuB5nDbt;
        "minecraft-24w38a" = _uuB5nDbt;
        "minecraft-24w39a" = _uuB5nDbt;
        "minecraft-24w40a" = _uuB5nDbt;
        "minecraft-1.21.2-pre1" = _uuB5nDbt;
        "minecraft-1.21.2-pre2" = _uuB5nDbt;
        "minecraft-24w44a" = _uuB5nDbt;
        "minecraft-24w45a" = _uuB5nDbt;
        "minecraft-24w46a" = _uuB5nDbt;
        "minecraft-1.21.4" = _IIOdz1fy;
        "minecraft-1.21.5" = _IIOdz1fy;
        "minecraft-1.21.6" = _IIOdz1fy;
        "minecraft-1.21.7" = _IIOdz1fy;
        "minecraft-1.21.8" = _IIOdz1fy;
        "minecraft-1.21.9" = _IIOdz1fy;
        "minecraft-1.21.10" = _IIOdz1fy;
        "minecraft-1.21.11" = _IIOdz1fy;
        "minecraft-26.1" = _IIOdz1fy;
        "minecraft-26.1.1" = _IIOdz1fy;
        "minecraft-26.1.2" = _IIOdz1fy;
        "minecraft-26.2" = _IIOdz1fy;
        "pkg-1.0" = _zx4REyru;
        "pkg-1.2Alt" = _Yx8UL1xp;
        "pkg-1.2" = _9Z1ATvGs;
        "pkg-1.3Alt" = _NmwMQKvc;
        "pkg-1.3" = _HPprBsij;
        "pkg-1.4Alt" = _RAKggsm3;
        "pkg-1.4" = _KRxgVuYg;
        "pkg-1.5Alt" = _uuB5nDbt;
        "pkg-1.5" = _IIOdz1fy;
        "default" = _IIOdz1fy;
    });
    fn = lib.prismnix.pkgs.mkVersionedModrinthPkgFn {
        name = "ginkgo-font";
        id = "Fbu2X1Dl";
        type = "resourcepack";
        versions = versions;
        meta = {
            license = lib.getLicenseFromSpdxIdOr "Apache-2.0" {
                free = false;
                deprecated = false;
                redistributable = false;
                fullName = "Apache License 2.0";
                shortName = "Apache-2.0";
                url = null;
            };
        };
    };
in callPackage fn {}