{lib, callPackage, ...}:
let
    versions = (let
        _ktAxXXbi = {
            "id" = "ktAxXXbi";
            "file" = "NoFog.zip";
            "hash" = "sha512-oIHBT/I0dXsqZN78RPhqvBQiUDIu9b4hNnx0/MmoPWxOTAnM0baSwquaAJTES9QZJRzT1h6ojRwLC5LLZjvAIA==";
        };
        _zFhJQT5g = {
            "id" = "zFhJQT5g";
            "file" = "NoFog.zip";
            "hash" = "sha512-Tzs/UD8BBMyPzL7pYqUvhJHfoaTRV5qKo0+l+EtjATEW9hQvFjB4xOPbMSA5HV2eZP+M84d7yQKQj+rQumqQkA==";
        };
        _ZpcZKVpV = {
            "id" = "ZpcZKVpV";
            "file" = "NoFog.zip";
            "hash" = "sha512-M/b7dnU0VlYR6Nv6NWwTnHxNN+L8OiJi4pWA5nbzKwhxJmfE4Iaeg0S757SdoDeGocfGiP2YDaE1qutpvPOqcA==";
        };
    in {
        "ktAxXXbi" = _ktAxXXbi;
        "zFhJQT5g" = _zFhJQT5g;
        "ZpcZKVpV" = _ZpcZKVpV;
        "minecraft-1.21" = _ZpcZKVpV;
        "minecraft-1.21.1" = _ZpcZKVpV;
        "minecraft-1.21.2" = _ZpcZKVpV;
        "minecraft-1.21.3" = _ZpcZKVpV;
        "minecraft-1.21.4" = _ZpcZKVpV;
        "minecraft-1.21.5" = _ZpcZKVpV;
        "minecraft-1.21.6" = _ZpcZKVpV;
        "minecraft-1.21.7" = _ZpcZKVpV;
        "minecraft-1.21.8" = _ZpcZKVpV;
        "minecraft-1.21.9" = _ZpcZKVpV;
        "minecraft-1.21.10" = _ZpcZKVpV;
        "minecraft-1.21.11" = _ZpcZKVpV;
        "minecraft-1.17" = _ZpcZKVpV;
        "minecraft-1.17.1" = _ZpcZKVpV;
        "minecraft-1.18" = _ZpcZKVpV;
        "minecraft-1.18.1" = _ZpcZKVpV;
        "minecraft-1.18.2" = _ZpcZKVpV;
        "minecraft-1.19" = _ZpcZKVpV;
        "minecraft-1.19.1" = _ZpcZKVpV;
        "minecraft-1.19.2" = _ZpcZKVpV;
        "minecraft-1.19.3" = _ZpcZKVpV;
        "minecraft-1.19.4" = _ZpcZKVpV;
        "minecraft-1.20" = _ZpcZKVpV;
        "minecraft-1.20.1" = _ZpcZKVpV;
        "minecraft-1.20.2" = _ZpcZKVpV;
        "minecraft-1.20.3" = _ZpcZKVpV;
        "minecraft-1.20.4" = _ZpcZKVpV;
        "minecraft-1.20.5" = _ZpcZKVpV;
        "minecraft-1.20.6" = _ZpcZKVpV;
        "minecraft-23w31a" = _ZpcZKVpV;
        "minecraft-23w32a" = _ZpcZKVpV;
        "minecraft-23w33a" = _ZpcZKVpV;
        "minecraft-23w35a" = _ZpcZKVpV;
        "minecraft-1.20.2-pre1" = _ZpcZKVpV;
        "minecraft-23w42a" = _ZpcZKVpV;
        "minecraft-23w43a" = _ZpcZKVpV;
        "minecraft-23w43b" = _ZpcZKVpV;
        "minecraft-23w44a" = _ZpcZKVpV;
        "minecraft-23w45a" = _ZpcZKVpV;
        "minecraft-23w46a" = _ZpcZKVpV;
        "minecraft-24w03a" = _ZpcZKVpV;
        "minecraft-24w03b" = _ZpcZKVpV;
        "minecraft-24w04a" = _ZpcZKVpV;
        "minecraft-24w05a" = _ZpcZKVpV;
        "minecraft-24w05b" = _ZpcZKVpV;
        "minecraft-24w06a" = _ZpcZKVpV;
        "minecraft-24w07a" = _ZpcZKVpV;
        "minecraft-24w09a" = _ZpcZKVpV;
        "minecraft-24w10a" = _ZpcZKVpV;
        "minecraft-24w11a" = _ZpcZKVpV;
        "minecraft-24w12a" = _ZpcZKVpV;
        "minecraft-24w13a" = _ZpcZKVpV;
        "minecraft-24w14potato" = _ZpcZKVpV;
        "minecraft-24w14a" = _ZpcZKVpV;
        "minecraft-1.20.5-pre1" = _ZpcZKVpV;
        "minecraft-1.20.5-pre2" = _ZpcZKVpV;
        "minecraft-1.20.5-pre3" = _ZpcZKVpV;
        "minecraft-24w18a" = _ZpcZKVpV;
        "minecraft-24w19a" = _ZpcZKVpV;
        "minecraft-24w19b" = _ZpcZKVpV;
        "minecraft-24w20a" = _ZpcZKVpV;
        "minecraft-24w33a" = _ZpcZKVpV;
        "minecraft-24w34a" = _ZpcZKVpV;
        "minecraft-24w35a" = _ZpcZKVpV;
        "minecraft-24w36a" = _ZpcZKVpV;
        "minecraft-24w37a" = _ZpcZKVpV;
        "minecraft-24w38a" = _ZpcZKVpV;
        "minecraft-24w39a" = _ZpcZKVpV;
        "minecraft-24w40a" = _ZpcZKVpV;
        "minecraft-1.21.2-pre1" = _ZpcZKVpV;
        "minecraft-1.21.2-pre2" = _ZpcZKVpV;
        "minecraft-24w44a" = _ZpcZKVpV;
        "minecraft-24w45a" = _ZpcZKVpV;
        "minecraft-24w46a" = _ZpcZKVpV;
        "minecraft-26.1" = _ZpcZKVpV;
        "minecraft-26.1.1" = _ZpcZKVpV;
        "minecraft-26.1.2" = _ZpcZKVpV;
        "minecraft-26.2" = _ZpcZKVpV;
        "pkg-1.0" = _ktAxXXbi;
        "pkg-2.0" = _zFhJQT5g;
        "pkg-v2.1.0" = _ZpcZKVpV;
        "default" = _ZpcZKVpV;
    });
    fn = lib.prismnix.pkgs.mkVersionedModrinthPkgFn {
        name = "nofog-turbo";
        id = "fI52H35V";
        type = "resourcepack";
        versions = versions;
        meta = {
            license = lib.getLicenseFromSpdxIdOr "GPL-3.0-only" {
                free = false;
                deprecated = false;
                redistributable = false;
                fullName = "GNU General Public License v3.0 only";
                shortName = "GPL-3.0-only";
                url = null;
            };
        };
    };
in callPackage fn {}