{lib, callPackage, ...}:
let
    versions = (let
        _lS2MCNnf = {
            "id" = "lS2MCNnf";
            "file" = "Night Vision Plus V1.6.0.zip";
            "hash" = "sha512-rhk49N10uHynaZbPLkDR7NM77UcdRRAzKH+vmjworZocu0GDO4xr86K3aBKQiiWdPShQs1B1Cz26gqCylK+N5g==";
        };
    in {
        "lS2MCNnf" = _lS2MCNnf;
        "minecraft-1.8" = _lS2MCNnf;
        "minecraft-1.8.1" = _lS2MCNnf;
        "minecraft-1.8.2" = _lS2MCNnf;
        "minecraft-1.8.3" = _lS2MCNnf;
        "minecraft-1.8.4" = _lS2MCNnf;
        "minecraft-1.8.5" = _lS2MCNnf;
        "minecraft-1.8.6" = _lS2MCNnf;
        "minecraft-1.8.7" = _lS2MCNnf;
        "minecraft-1.8.8" = _lS2MCNnf;
        "minecraft-1.8.9" = _lS2MCNnf;
        "minecraft-1.9" = _lS2MCNnf;
        "minecraft-1.9.1" = _lS2MCNnf;
        "minecraft-1.9.2" = _lS2MCNnf;
        "minecraft-1.9.3" = _lS2MCNnf;
        "minecraft-1.9.4" = _lS2MCNnf;
        "minecraft-1.10" = _lS2MCNnf;
        "minecraft-1.10.1" = _lS2MCNnf;
        "minecraft-1.10.2" = _lS2MCNnf;
        "minecraft-1.11" = _lS2MCNnf;
        "minecraft-1.11.1" = _lS2MCNnf;
        "minecraft-1.11.2" = _lS2MCNnf;
        "minecraft-1.12" = _lS2MCNnf;
        "minecraft-1.12.1" = _lS2MCNnf;
        "minecraft-1.12.2" = _lS2MCNnf;
        "minecraft-1.13" = _lS2MCNnf;
        "minecraft-1.13.1" = _lS2MCNnf;
        "minecraft-1.13.2" = _lS2MCNnf;
        "minecraft-1.14" = _lS2MCNnf;
        "minecraft-1.14.1" = _lS2MCNnf;
        "minecraft-1.14.2" = _lS2MCNnf;
        "minecraft-1.14.3" = _lS2MCNnf;
        "minecraft-1.14.4" = _lS2MCNnf;
        "minecraft-1.15" = _lS2MCNnf;
        "minecraft-1.15.1" = _lS2MCNnf;
        "minecraft-1.15.2" = _lS2MCNnf;
        "minecraft-1.16" = _lS2MCNnf;
        "minecraft-1.16.1" = _lS2MCNnf;
        "minecraft-1.16.2" = _lS2MCNnf;
        "minecraft-1.16.3" = _lS2MCNnf;
        "minecraft-1.16.4" = _lS2MCNnf;
        "minecraft-1.16.5" = _lS2MCNnf;
        "minecraft-1.17" = _lS2MCNnf;
        "minecraft-1.17.1" = _lS2MCNnf;
        "minecraft-1.18" = _lS2MCNnf;
        "minecraft-1.18.1" = _lS2MCNnf;
        "minecraft-1.18.2" = _lS2MCNnf;
        "minecraft-1.19" = _lS2MCNnf;
        "minecraft-1.19.1" = _lS2MCNnf;
        "minecraft-1.19.2" = _lS2MCNnf;
        "minecraft-1.19.3" = _lS2MCNnf;
        "minecraft-1.19.4" = _lS2MCNnf;
        "minecraft-1.20" = _lS2MCNnf;
        "minecraft-1.20.1" = _lS2MCNnf;
        "minecraft-1.20.2" = _lS2MCNnf;
        "minecraft-1.20.3" = _lS2MCNnf;
        "minecraft-1.20.4" = _lS2MCNnf;
        "minecraft-1.20.5" = _lS2MCNnf;
        "minecraft-1.20.6" = _lS2MCNnf;
        "minecraft-1.21" = _lS2MCNnf;
        "minecraft-1.21.1" = _lS2MCNnf;
        "minecraft-1.21.2" = _lS2MCNnf;
        "minecraft-1.21.3" = _lS2MCNnf;
        "minecraft-1.21.4" = _lS2MCNnf;
        "minecraft-1.21.5" = _lS2MCNnf;
        "minecraft-1.21.6" = _lS2MCNnf;
        "minecraft-1.21.7" = _lS2MCNnf;
        "minecraft-1.21.8" = _lS2MCNnf;
        "minecraft-1.21.9" = _lS2MCNnf;
        "minecraft-1.21.10" = _lS2MCNnf;
        "minecraft-1.21.11" = _lS2MCNnf;
        "minecraft-26.1" = _lS2MCNnf;
        "minecraft-26.1.1" = _lS2MCNnf;
        "minecraft-26.1.2" = _lS2MCNnf;
        "minecraft-26.2" = _lS2MCNnf;
        "pkg-1.6.0" = _lS2MCNnf;
        "default" = _lS2MCNnf;
    });
    fn = lib.prismnix.pkgs.mkVersionedModrinthPkgFn {
        name = "night-vision-plus";
        id = "h4c8V3Iy";
        type = "resourcepack";
        versions = versions;
        meta = {
            license = lib.getLicenseFromSpdxIdOr "LicenseRef-All-Rights-Reserved" {
                free = false;
                deprecated = false;
                redistributable = false;
                fullName = "LicenseRef-All-Rights-Reserved";
                shortName = "LicenseRef-All-Rights-Reserved";
                url = null;
            };
        };
    };
in callPackage fn {}