{lib, callPackage, ...}:
let
    versions = (let
        _EIQpPet0 = {
            "id" = "EIQpPet0";
            "file" = "1hpchallenge.zip";
            "hash" = "sha512-9Kv0L16SbYavfqvzaqtmNjwguN37Po9kqjyCKuD0mn3qKOxN+WhlPzesBGw6hw6BHcAn7EoGt3j20/Zu2r6suQ==";
        };
        _AUqFcbDI = {
            "id" = "AUqFcbDI";
            "file" = "1hpchallenge-0.1.jar";
            "hash" = "sha512-3ftdcUWKkoi8H2JT6FAHZbZpxRu7HmD1CEilKws01c8iCWXGn4g/vdrYx+nadko6bSdpvhsytaw8wujNpPbfjg==";
        };
        _7Xs2aJ0I = {
            "id" = "7Xs2aJ0I";
            "file" = "1HP Challenge.zip";
            "hash" = "sha512-kkHkEMJ+GaXPL+iVWpWYM2DdaGJ242QVzTmLQHTVT6TDDMnZu57ax31Bqk5WEt4wXtdXUrNWWMTYVaWarwMs9w==";
        };
        _xLjM6nxY = {
            "id" = "xLjM6nxY";
            "file" = "1hpchallenge-1.1.jar";
            "hash" = "sha512-Y6eqa8xQTxjnOaBnZUpp1IRBhj0Y7DZBscRlm4yue+Z5LXioquIoUVDiJDXmXT1pdn7Bqie7bIpVg6nnGihljQ==";
        };
        _fppQH8wm = {
            "id" = "fppQH8wm";
            "file" = "1HP-Challenge_1.21.2-26.2_V1.2.zip";
            "hash" = "sha512-hCs9Jeb0sfUH9B6W9a/LvvJBuOWaraL3Zs6YGmeWBPpqaj5n+Gh+ZUUPeYHD0ScZHpiWtlKvGgxPY3EiFzBJpw==";
        };
        _fDDCiPoz = {
            "id" = "fDDCiPoz";
            "file" = "1hpchallenge-1.2.jar";
            "hash" = "sha512-X+/f4SRYJyqobEuYW1w1KPeASYJEsliZc4xP0vXuDSym5B3NkCj1eItfdE9K6qz1LVgtcUiAllaSTNT7WFGfzw==";
        };
    in {
        "EIQpPet0" = _EIQpPet0;
        "AUqFcbDI" = _AUqFcbDI;
        "7Xs2aJ0I" = _7Xs2aJ0I;
        "xLjM6nxY" = _xLjM6nxY;
        "fppQH8wm" = _fppQH8wm;
        "fDDCiPoz" = _fDDCiPoz;
        "datapack-1.20.5" = _EIQpPet0;
        "datapack-1.20.6" = _EIQpPet0;
        "datapack-1.21" = _EIQpPet0;
        "datapack-1.21.1" = _EIQpPet0;
        "datapack-1.21.2" = _fppQH8wm;
        "datapack-1.21.3" = _fppQH8wm;
        "datapack-1.21.4" = _fppQH8wm;
        "datapack-1.21.5" = _fppQH8wm;
        "datapack-1.21.6" = _fppQH8wm;
        "datapack-24w44a" = _fppQH8wm;
        "datapack-24w45a" = _fppQH8wm;
        "datapack-24w46a" = _fppQH8wm;
        "datapack-1.21.7" = _fppQH8wm;
        "datapack-1.21.8" = _fppQH8wm;
        "datapack-1.21.9" = _fppQH8wm;
        "datapack-1.21.10" = _fppQH8wm;
        "datapack-1.21.11" = _fppQH8wm;
        "datapack-26.1" = _fppQH8wm;
        "datapack-26.1.1" = _fppQH8wm;
        "datapack-26.1.2" = _fppQH8wm;
        "datapack-26.2" = _fppQH8wm;
        "fabric-1.20.5" = _AUqFcbDI;
        "fabric-1.20.6" = _AUqFcbDI;
        "fabric-1.21" = _AUqFcbDI;
        "fabric-1.21.1" = _AUqFcbDI;
        "fabric-1.21.2" = _fDDCiPoz;
        "fabric-1.21.3" = _fDDCiPoz;
        "fabric-1.21.4" = _fDDCiPoz;
        "fabric-1.21.5" = _fDDCiPoz;
        "fabric-1.21.6" = _fDDCiPoz;
        "fabric-24w44a" = _fDDCiPoz;
        "fabric-24w45a" = _fDDCiPoz;
        "fabric-24w46a" = _fDDCiPoz;
        "fabric-1.21.7" = _fDDCiPoz;
        "fabric-1.21.8" = _fDDCiPoz;
        "fabric-1.21.9" = _fDDCiPoz;
        "fabric-1.21.10" = _fDDCiPoz;
        "fabric-1.21.11" = _fDDCiPoz;
        "fabric-26.1" = _fDDCiPoz;
        "fabric-26.1.1" = _fDDCiPoz;
        "fabric-26.1.2" = _fDDCiPoz;
        "fabric-26.2" = _fDDCiPoz;
        "forge-1.20.5" = _AUqFcbDI;
        "forge-1.20.6" = _AUqFcbDI;
        "forge-1.21" = _AUqFcbDI;
        "forge-1.21.1" = _AUqFcbDI;
        "forge-1.21.2" = _fDDCiPoz;
        "forge-1.21.3" = _fDDCiPoz;
        "forge-1.21.4" = _fDDCiPoz;
        "forge-1.21.5" = _fDDCiPoz;
        "forge-1.21.6" = _fDDCiPoz;
        "forge-24w44a" = _fDDCiPoz;
        "forge-24w45a" = _fDDCiPoz;
        "forge-24w46a" = _fDDCiPoz;
        "forge-1.21.7" = _fDDCiPoz;
        "forge-1.21.8" = _fDDCiPoz;
        "forge-1.21.9" = _fDDCiPoz;
        "forge-1.21.10" = _fDDCiPoz;
        "forge-1.21.11" = _fDDCiPoz;
        "forge-26.1" = _fDDCiPoz;
        "forge-26.1.1" = _fDDCiPoz;
        "forge-26.1.2" = _fDDCiPoz;
        "forge-26.2" = _fDDCiPoz;
        "neoforge-1.20.5" = _AUqFcbDI;
        "neoforge-1.20.6" = _AUqFcbDI;
        "neoforge-1.21" = _AUqFcbDI;
        "neoforge-1.21.1" = _AUqFcbDI;
        "neoforge-1.21.2" = _fDDCiPoz;
        "neoforge-1.21.3" = _fDDCiPoz;
        "neoforge-1.21.4" = _fDDCiPoz;
        "neoforge-1.21.5" = _fDDCiPoz;
        "neoforge-1.21.6" = _fDDCiPoz;
        "neoforge-24w44a" = _fDDCiPoz;
        "neoforge-24w45a" = _fDDCiPoz;
        "neoforge-24w46a" = _fDDCiPoz;
        "neoforge-1.21.7" = _fDDCiPoz;
        "neoforge-1.21.8" = _fDDCiPoz;
        "neoforge-1.21.9" = _fDDCiPoz;
        "neoforge-1.21.10" = _fDDCiPoz;
        "neoforge-1.21.11" = _fDDCiPoz;
        "neoforge-26.1" = _fDDCiPoz;
        "neoforge-26.1.1" = _fDDCiPoz;
        "neoforge-26.1.2" = _fDDCiPoz;
        "neoforge-26.2" = _fDDCiPoz;
        "quilt-1.20.5" = _AUqFcbDI;
        "quilt-1.20.6" = _AUqFcbDI;
        "quilt-1.21" = _AUqFcbDI;
        "quilt-1.21.1" = _AUqFcbDI;
        "quilt-1.21.2" = _fDDCiPoz;
        "quilt-1.21.3" = _fDDCiPoz;
        "quilt-1.21.4" = _fDDCiPoz;
        "quilt-1.21.5" = _fDDCiPoz;
        "quilt-1.21.6" = _fDDCiPoz;
        "quilt-24w44a" = _fDDCiPoz;
        "quilt-24w45a" = _fDDCiPoz;
        "quilt-24w46a" = _fDDCiPoz;
        "quilt-1.21.7" = _fDDCiPoz;
        "quilt-1.21.8" = _fDDCiPoz;
        "quilt-1.21.9" = _fDDCiPoz;
        "quilt-1.21.10" = _fDDCiPoz;
        "quilt-1.21.11" = _fDDCiPoz;
        "quilt-26.1" = _fDDCiPoz;
        "quilt-26.1.1" = _fDDCiPoz;
        "quilt-26.1.2" = _fDDCiPoz;
        "quilt-26.2" = _fDDCiPoz;
        "pkg-0.1" = _EIQpPet0;
        "pkg-0.1+mod" = _AUqFcbDI;
        "pkg-1.1" = _7Xs2aJ0I;
        "pkg-1.1+mod" = _xLjM6nxY;
        "pkg-1.2" = _fppQH8wm;
        "pkg-1.2+mod" = _fDDCiPoz;
        "default" = _fDDCiPoz;
    });
    fn = lib.prismnix.pkgs.mkVersionedModrinthPkgFn {
        name = "1hpchallenge";
        id = "K4nLGYze";
        type = "mod";
        versions = versions;
        meta = {
            license = lib.getLicenseFromSpdxIdOr "MIT" {
                free = false;
                deprecated = false;
                redistributable = false;
                fullName = "MIT License";
                shortName = "MIT";
                url = null;
            };
        };
    };
in callPackage fn {}