{lib, callPackage, ...}:
let
    versions = (let
        _TkG0LWsn = {
            "id" = "TkG0LWsn";
            "file" = "mace2pan 21.0n21.8.zip";
            "hash" = "sha512-k9b1ftkxjhEkG3/yU8gb+7CaASU3mVtupEmaYdCW/U0HiGbhBUgLQ8f3HMvgCfbLWip52kPkGulj4/BXJ4Lasw==";
        };
        _GMrJuXk0 = {
            "id" = "GMrJuXk0";
            "file" = "mace to pan 21.0n26.3a.zip";
            "hash" = "sha512-C2iKV8ikeP4QamzN7cLgpE2Diux+YKZoosAL/tistGYJUniVe8feV4WMDL3baFfBWVUzE08NpRkvPb1PUZqYWQ==";
        };
    in {
        "TkG0LWsn" = _TkG0LWsn;
        "GMrJuXk0" = _GMrJuXk0;
        "minecraft-1.21" = _GMrJuXk0;
        "minecraft-1.21.1" = _GMrJuXk0;
        "minecraft-1.21.2" = _GMrJuXk0;
        "minecraft-1.21.3" = _GMrJuXk0;
        "minecraft-1.21.4" = _GMrJuXk0;
        "minecraft-1.21.5" = _GMrJuXk0;
        "minecraft-1.21.6" = _GMrJuXk0;
        "minecraft-1.21.7" = _GMrJuXk0;
        "minecraft-1.21.8" = _GMrJuXk0;
        "minecraft-24w33a" = _GMrJuXk0;
        "minecraft-24w34a" = _GMrJuXk0;
        "minecraft-24w35a" = _GMrJuXk0;
        "minecraft-24w36a" = _GMrJuXk0;
        "minecraft-24w37a" = _GMrJuXk0;
        "minecraft-24w38a" = _GMrJuXk0;
        "minecraft-24w39a" = _GMrJuXk0;
        "minecraft-24w40a" = _GMrJuXk0;
        "minecraft-1.21.2-pre1" = _GMrJuXk0;
        "minecraft-1.21.2-pre2" = _GMrJuXk0;
        "minecraft-24w44a" = _GMrJuXk0;
        "minecraft-24w45a" = _GMrJuXk0;
        "minecraft-24w46a" = _GMrJuXk0;
        "minecraft-1.21.9" = _GMrJuXk0;
        "minecraft-1.21.10" = _GMrJuXk0;
        "minecraft-1.21.11" = _GMrJuXk0;
        "minecraft-26.1-snapshot-1" = _GMrJuXk0;
        "minecraft-26.1-snapshot-2" = _GMrJuXk0;
        "minecraft-26.1-snapshot-3" = _GMrJuXk0;
        "minecraft-26.1-snapshot-4" = _GMrJuXk0;
        "minecraft-26.1-snapshot-5" = _GMrJuXk0;
        "minecraft-26.1-snapshot-6" = _GMrJuXk0;
        "minecraft-26.1-snapshot-7" = _GMrJuXk0;
        "minecraft-26.1-snapshot-8" = _GMrJuXk0;
        "minecraft-26.1-snapshot-9" = _GMrJuXk0;
        "minecraft-26.1-snapshot-10" = _GMrJuXk0;
        "minecraft-26.1-snapshot-11" = _GMrJuXk0;
        "minecraft-26.1-pre-1" = _GMrJuXk0;
        "minecraft-26.1-pre-2" = _GMrJuXk0;
        "minecraft-26.1-pre-3" = _GMrJuXk0;
        "minecraft-26.1-rc-1" = _GMrJuXk0;
        "minecraft-26.1-rc-2" = _GMrJuXk0;
        "minecraft-26.1-rc-3" = _GMrJuXk0;
        "minecraft-26.1" = _GMrJuXk0;
        "minecraft-26.1.1-rc-1" = _GMrJuXk0;
        "minecraft-26.1.1" = _GMrJuXk0;
        "minecraft-26w14a" = _GMrJuXk0;
        "minecraft-26.2-snapshot-1" = _GMrJuXk0;
        "minecraft-26.1.2-rc-1" = _GMrJuXk0;
        "minecraft-26.1.2" = _GMrJuXk0;
        "minecraft-26.2-snapshot-2" = _GMrJuXk0;
        "minecraft-26.2-snapshot-3" = _GMrJuXk0;
        "minecraft-26.2-snapshot-4" = _GMrJuXk0;
        "minecraft-26.2-snapshot-5" = _GMrJuXk0;
        "minecraft-26.2-snapshot-6" = _GMrJuXk0;
        "minecraft-26.2-snapshot-7" = _GMrJuXk0;
        "minecraft-26.2-snapshot-8" = _GMrJuXk0;
        "minecraft-26.2-pre-1" = _GMrJuXk0;
        "minecraft-26.2-pre-2" = _GMrJuXk0;
        "minecraft-26.2-pre-3" = _GMrJuXk0;
        "minecraft-26.2-pre-4" = _GMrJuXk0;
        "minecraft-26.2-pre-5" = _GMrJuXk0;
        "minecraft-26.2-pre-6" = _GMrJuXk0;
        "minecraft-26.2-rc-1" = _GMrJuXk0;
        "minecraft-26.2-rc-2" = _GMrJuXk0;
        "minecraft-26.2" = _GMrJuXk0;
        "minecraft-26.3-snapshot-1" = _GMrJuXk0;
        "minecraft-26.3-snapshot-2" = _GMrJuXk0;
        "minecraft-26.3-snapshot-3" = _GMrJuXk0;
        "minecraft-26.3-snapshot-4" = _GMrJuXk0;
        "minecraft-26.3-snapshot-5" = _GMrJuXk0;
        "minecraft-26.3-snapshot-6" = _GMrJuXk0;
        "minecraft-26.3-snapshot-7" = _GMrJuXk0;
        "minecraft-26.3-snapshot-8" = _GMrJuXk0;
        "minecraft-26.3-snapshot-9" = _GMrJuXk0;
        "minecraft-26.3-snapshot-10" = _GMrJuXk0;
        "minecraft-26.3-pre-1" = _GMrJuXk0;
        "minecraft-26.3-pre-2" = _GMrJuXk0;
        "minecraft-26.3-pre-3" = _GMrJuXk0;
        "minecraft-26.3-rc-1" = _GMrJuXk0;
        "minecraft-26.3-rc-2" = _GMrJuXk0;
        "minecraft-26.3-rc-3" = _GMrJuXk0;
        "minecraft-26.3" = _GMrJuXk0;
        "pkg-21.0n21.8a" = _TkG0LWsn;
        "pkg-21.0n26.3a" = _GMrJuXk0;
        "default" = _GMrJuXk0;
    });
    fn = lib.prismnix.pkgs.mkVersionedModrinthPkgFn {
        name = "mace2pan";
        id = "K4wWe1om";
        type = "resourcepack";
        versions = versions;
        meta = {
            license = lib.getLicenseFromSpdxIdOr "LicenseRef-All-Rights-Reserved" {
                free = false;
                deprecated = false;
                redistributable = false;
                fullName = "LicenseRef-All-Rights-Reserved";
                shortName = "LicenseRef-All-Rights-Reserved";
                url = null;
            };
        };
    };
in callPackage fn {}