{lib, callPackage, ...}:
let
    versions = (let
        _jliMx9qa = {
            "id" = "jliMx9qa";
            "file" = "§7§lFaithful §a32× §e§lGlowing §b§lOre.zip";
            "hash" = "sha512-oT/4GajLCDInURHN/phTUQpykEvJxANq32heR4erlb7BBujYnCljCGqxT8xK1+NG86xEVtYONnNoVV77PX60rg==";
        };
        _cUzQQ1Iz = {
            "id" = "cUzQQ1Iz";
            "file" = "§7§lFaithful §a32× §e§lGlowing §b§lOre.zip";
            "hash" = "sha512-oT/4GajLCDInURHN/phTUQpykEvJxANq32heR4erlb7BBujYnCljCGqxT8xK1+NG86xEVtYONnNoVV77PX60rg==";
        };
        _STApMBQo = {
            "id" = "STApMBQo";
            "file" = "§7§lFaithful §a32× §e§lGlowing §b§lOre.zip";
            "hash" = "sha512-oT/4GajLCDInURHN/phTUQpykEvJxANq32heR4erlb7BBujYnCljCGqxT8xK1+NG86xEVtYONnNoVV77PX60rg==";
        };
        _XnuhJCf7 = {
            "id" = "XnuhJCf7";
            "file" = "§7§lFaithful §a32× §e§lGlowing §b§lOre.zip";
            "hash" = "sha512-oT/4GajLCDInURHN/phTUQpykEvJxANq32heR4erlb7BBujYnCljCGqxT8xK1+NG86xEVtYONnNoVV77PX60rg==";
        };
    in {
        "jliMx9qa" = _jliMx9qa;
        "cUzQQ1Iz" = _cUzQQ1Iz;
        "STApMBQo" = _STApMBQo;
        "XnuhJCf7" = _XnuhJCf7;
        "minecraft-1.16" = _XnuhJCf7;
        "minecraft-1.16.1" = _XnuhJCf7;
        "minecraft-1.16.2" = _XnuhJCf7;
        "minecraft-1.16.3" = _XnuhJCf7;
        "minecraft-1.16.4" = _XnuhJCf7;
        "minecraft-1.16.5" = _XnuhJCf7;
        "minecraft-1.17" = _XnuhJCf7;
        "minecraft-1.17.1" = _XnuhJCf7;
        "minecraft-1.18" = _XnuhJCf7;
        "minecraft-1.18.1" = _XnuhJCf7;
        "minecraft-1.18.2" = _XnuhJCf7;
        "minecraft-1.19" = _XnuhJCf7;
        "minecraft-1.19.1" = _XnuhJCf7;
        "minecraft-1.19.2" = _XnuhJCf7;
        "minecraft-1.19.3" = _XnuhJCf7;
        "minecraft-1.19.4" = _XnuhJCf7;
        "minecraft-1.20" = _XnuhJCf7;
        "minecraft-1.20.1" = _XnuhJCf7;
        "minecraft-1.20.2" = _XnuhJCf7;
        "minecraft-23w43a" = _XnuhJCf7;
        "minecraft-23w43b" = _XnuhJCf7;
        "minecraft-23w44a" = _XnuhJCf7;
        "minecraft-23w45a" = _XnuhJCf7;
        "minecraft-23w46a" = _XnuhJCf7;
        "minecraft-1.20.3" = _XnuhJCf7;
        "minecraft-1.20.4" = _XnuhJCf7;
        "minecraft-24w03a" = _XnuhJCf7;
        "minecraft-24w03b" = _XnuhJCf7;
        "minecraft-24w04a" = _XnuhJCf7;
        "minecraft-24w05a" = _XnuhJCf7;
        "minecraft-24w05b" = _XnuhJCf7;
        "minecraft-24w06a" = _XnuhJCf7;
        "minecraft-24w07a" = _XnuhJCf7;
        "minecraft-24w09a" = _XnuhJCf7;
        "minecraft-24w10a" = _XnuhJCf7;
        "minecraft-24w11a" = _XnuhJCf7;
        "minecraft-24w12a" = _XnuhJCf7;
        "minecraft-24w13a" = _XnuhJCf7;
        "minecraft-24w14potato" = _XnuhJCf7;
        "minecraft-24w14a" = _XnuhJCf7;
        "minecraft-1.20.5-pre1" = _XnuhJCf7;
        "minecraft-1.20.5-pre2" = _XnuhJCf7;
        "minecraft-1.20.5-pre3" = _XnuhJCf7;
        "minecraft-1.20.5" = _XnuhJCf7;
        "minecraft-1.20.6" = _XnuhJCf7;
        "minecraft-24w18a" = _XnuhJCf7;
        "minecraft-24w19a" = _XnuhJCf7;
        "minecraft-24w19b" = _XnuhJCf7;
        "minecraft-24w20a" = _XnuhJCf7;
        "minecraft-1.21" = _XnuhJCf7;
        "minecraft-1.21.1" = _XnuhJCf7;
        "minecraft-24w33a" = _XnuhJCf7;
        "minecraft-24w34a" = _XnuhJCf7;
        "minecraft-24w35a" = _XnuhJCf7;
        "minecraft-24w36a" = _XnuhJCf7;
        "minecraft-24w37a" = _XnuhJCf7;
        "minecraft-24w38a" = _XnuhJCf7;
        "minecraft-24w39a" = _XnuhJCf7;
        "minecraft-24w40a" = _XnuhJCf7;
        "minecraft-1.21.2-pre1" = _XnuhJCf7;
        "minecraft-1.21.2-pre2" = _XnuhJCf7;
        "minecraft-1.21.2" = _XnuhJCf7;
        "minecraft-1.21.3" = _XnuhJCf7;
        "minecraft-24w44a" = _XnuhJCf7;
        "minecraft-24w45a" = _XnuhJCf7;
        "minecraft-24w46a" = _XnuhJCf7;
        "minecraft-1.21.4" = _XnuhJCf7;
        "minecraft-1.21.5" = _XnuhJCf7;
        "minecraft-1.21.6" = _XnuhJCf7;
        "minecraft-1.21.7" = _XnuhJCf7;
        "minecraft-1.21.8" = _XnuhJCf7;
        "minecraft-1.21.9" = _XnuhJCf7;
        "minecraft-1.21.10" = _XnuhJCf7;
        "minecraft-1.21.11" = _XnuhJCf7;
        "minecraft-26.1" = _XnuhJCf7;
        "minecraft-26.1.1" = _XnuhJCf7;
        "minecraft-26.1.2" = _XnuhJCf7;
        "minecraft-26.2" = _XnuhJCf7;
        "minecraft-1.14" = _STApMBQo;
        "minecraft-1.14.1" = _STApMBQo;
        "minecraft-1.14.2" = _STApMBQo;
        "minecraft-1.14.3" = _STApMBQo;
        "minecraft-1.14.4" = _STApMBQo;
        "minecraft-1.15" = _XnuhJCf7;
        "minecraft-1.15.1" = _XnuhJCf7;
        "minecraft-1.15.2" = _XnuhJCf7;
        "minecraft-26.3" = _XnuhJCf7;
        "pkg-1.0" = _jliMx9qa;
        "pkg-1.1" = _cUzQQ1Iz;
        "pkg-1.3" = _STApMBQo;
        "pkg-1.4" = _XnuhJCf7;
        "default" = _XnuhJCf7;
    });
    fn = lib.prismnix.pkgs.mkVersionedModrinthPkgFn {
        name = "faithful-32-glowing-ores";
        id = "op5UgY7l";
        type = "resourcepack";
        versions = versions;
        meta = {
            license = lib.getLicenseFromSpdxIdOr "CC-BY-NC-4.0" {
                free = false;
                deprecated = false;
                redistributable = false;
                fullName = "Creative Commons Attribution Non Commercial 4.0 International";
                shortName = "CC-BY-NC-4.0";
                url = null;
            };
        };
    };
in callPackage fn {}