{lib, callPackage, ...}:
let
    versions = (let
        _gGqjxiE4 = {
            "id" = "gGqjxiE4";
            "file" = "BloodMoon - Texture.zip";
            "hash" = "sha512-DiCFpkaEF/6t5Otls4CB1NIpGchH5Bs3a7NGDnFFUSRv8zysmskFY880n/iFbL83eaL0zrW+kOsDGBtMT00c+w==";
        };
        _LheZGJsi = {
            "id" = "LheZGJsi";
            "file" = "BloodMoon - Texture(1.20.5).zip";
            "hash" = "sha512-d2DGcdsP2BRi9O9A0235JdObnCcAY/8cAWoLja6QK5Mx1hYo/bZzNvaxFDf2/d7SJz+6Q47GbbYI3sj29wg2Mg==";
        };
        _bLgmKwaH = {
            "id" = "bLgmKwaH";
            "file" = "BloodMoon - Texture(1.20.6).zip";
            "hash" = "sha512-d2DGcdsP2BRi9O9A0235JdObnCcAY/8cAWoLja6QK5Mx1hYo/bZzNvaxFDf2/d7SJz+6Q47GbbYI3sj29wg2Mg==";
        };
        _9q7WBKaf = {
            "id" = "9q7WBKaf";
            "file" = "BloodMoon - Texture(1.20.1).zip";
            "hash" = "sha512-F/2XUCRG9XIwJ9La3Gx0JLKbCr0xJtAAh0rXbqaslyqsSZbkzZ8I+8xBhg9Rw51Ki37xt6iENd2kJZKfUKQBtg==";
        };
        _7OTFPbLT = {
            "id" = "7OTFPbLT";
            "file" = "BloodMoon - Texture(1.21.1).zip";
            "hash" = "sha512-KoNISrVLT5IoOav+kNLSXIHVqhaW+YXZfheB8ShO1l23S+oPBBCkrTSsm/WfePD2m4RMSH2JtCufplL8CFe9kg==";
        };
        _hRGuKdjx = {
            "id" = "hRGuKdjx";
            "file" = "BloodMoon - Texture(1.21.2).zip";
            "hash" = "sha512-0oyCTBr60GNx7tcMwojUQerHDcqauV34z0/Di8oEfA5K/NTi6t4eBBpGVkkiVkQ9tDSBKC2bvVSXQvw3U2d0xg==";
        };
        _LK3ITY69 = {
            "id" = "LK3ITY69";
            "file" = "BloodMoon - Texture(1.21.3).zip";
            "hash" = "sha512-N66+J6wRQAqqqSiEDRaxXLFRmOx9j6NunPP4zVWs/Mbd6dAcjMNEqIGG9n1NLNPM3oXpLgPC0+x3J1q8KQ+nvw==";
        };
        _NT7OhnGQ = {
            "id" = "NT7OhnGQ";
            "file" = "BloodMoon - Texture(1.21.4).zip";
            "hash" = "sha512-T6KhG2iROU2GxKk8cFOqtuvDok9x1ekAlykFRcCV1vizGEIK5YnELMDMPqqp/eeHR5dz3/3ECYRFq7jcAeVKOg==";
        };
        _TKhj8cpq = {
            "id" = "TKhj8cpq";
            "file" = "BloodMoon - Texture(1.21.5).zip";
            "hash" = "sha512-q2bv72PkJSKrzoYLmKmrxLIWvDllHtzVXPBEpNRlpxnWNdD4xV+XWUm9WkKo2npTnPxlcA29hYZ//4YaCVmtsA==";
        };
        _lG8t088k = {
            "id" = "lG8t088k";
            "file" = "BloodMoon - Texture(1.21.6).zip";
            "hash" = "sha512-bQ2yybAs606QOqAB17mKTpAgSNRM99s6fsxqkWIwfTBxEmwLHVKBqPxiGxOrdwneGRm7GG5U52RYyeWG5iVVxg==";
        };
        _4xfIx8RI = {
            "id" = "4xfIx8RI";
            "file" = "BloodMoon - Texture(1.21.7).zip";
            "hash" = "sha512-UNViBDtgl0GQRthpwirAP6SBBQeBJ14tF6mmWxtxw4FJztXXM+boo+Kj5GFzYTflNf2tBO9BPWgyGU0uwGNxMQ==";
        };
        _8TWlGf6M = {
            "id" = "8TWlGf6M";
            "file" = "BloodMoon - Texture(1.21.8).zip";
            "hash" = "sha512-5MTMApLO2u1Fm0bKQkPZ4YQDyBKpY06ySbBJXYgvn2WebZX9Botzv/SbSaVFXJbTBBIK/6ole2kyduC1xY8Dfw==";
        };
        _M6uWxUGK = {
            "id" = "M6uWxUGK";
            "file" = "BloodMoon - Texture(1.21.9-1.21.11).zip";
            "hash" = "sha512-e5NT3hvyNRzB3IZrRIt9OBlsoaaK0TtfbZSWSlDd+K+SiiGfoyWiEB1nzLfz3SaE7OQKadLHsp6W1AbM+4kapA==";
        };
        _DkReoHNA = {
            "id" = "DkReoHNA";
            "file" = "BloodMoon - Texture.zip";
            "hash" = "sha512-2XzC4r/OV73lTMvtaXkkd9XxmQBQ7Hfu2XTt9dBKIwdf4671iOea5b4iqxDZr0rOhnQygYZqTS/kKze3CvlwAQ==";
        };
    in {
        "gGqjxiE4" = _gGqjxiE4;
        "LheZGJsi" = _LheZGJsi;
        "bLgmKwaH" = _bLgmKwaH;
        "9q7WBKaf" = _9q7WBKaf;
        "7OTFPbLT" = _7OTFPbLT;
        "hRGuKdjx" = _hRGuKdjx;
        "LK3ITY69" = _LK3ITY69;
        "NT7OhnGQ" = _NT7OhnGQ;
        "TKhj8cpq" = _TKhj8cpq;
        "lG8t088k" = _lG8t088k;
        "4xfIx8RI" = _4xfIx8RI;
        "8TWlGf6M" = _8TWlGf6M;
        "M6uWxUGK" = _M6uWxUGK;
        "DkReoHNA" = _DkReoHNA;
        "minecraft-1.16" = _gGqjxiE4;
        "minecraft-1.16.1" = _gGqjxiE4;
        "minecraft-1.16.2" = _gGqjxiE4;
        "minecraft-1.16.3" = _gGqjxiE4;
        "minecraft-1.16.4" = _gGqjxiE4;
        "minecraft-1.16.5" = _gGqjxiE4;
        "minecraft-1.17" = _gGqjxiE4;
        "minecraft-1.17.1" = _gGqjxiE4;
        "minecraft-1.18" = _gGqjxiE4;
        "minecraft-1.18.1" = _gGqjxiE4;
        "minecraft-1.18.2" = _gGqjxiE4;
        "minecraft-1.19" = _gGqjxiE4;
        "minecraft-1.19.1" = _gGqjxiE4;
        "minecraft-1.19.2" = _gGqjxiE4;
        "minecraft-1.19.3" = _gGqjxiE4;
        "minecraft-1.19.4" = _gGqjxiE4;
        "minecraft-1.20" = _DkReoHNA;
        "minecraft-1.20.1" = _DkReoHNA;
        "minecraft-1.20.2" = _DkReoHNA;
        "minecraft-1.20.3" = _DkReoHNA;
        "minecraft-1.20.4" = _DkReoHNA;
        "minecraft-1.20.5" = _DkReoHNA;
        "minecraft-1.20.6" = _DkReoHNA;
        "minecraft-1.21" = _DkReoHNA;
        "minecraft-1.21.1" = _DkReoHNA;
        "minecraft-1.21.2" = _DkReoHNA;
        "minecraft-1.21.3" = _DkReoHNA;
        "minecraft-1.21.4" = _DkReoHNA;
        "minecraft-1.21.5" = _DkReoHNA;
        "minecraft-1.21.6" = _DkReoHNA;
        "minecraft-1.21.7" = _DkReoHNA;
        "minecraft-1.21.8" = _DkReoHNA;
        "minecraft-1.21.9" = _DkReoHNA;
        "minecraft-1.21.10" = _DkReoHNA;
        "minecraft-1.21.11" = _DkReoHNA;
        "minecraft-23w31a" = _DkReoHNA;
        "minecraft-23w32a" = _DkReoHNA;
        "minecraft-23w33a" = _DkReoHNA;
        "minecraft-23w35a" = _DkReoHNA;
        "minecraft-1.20.2-pre1" = _DkReoHNA;
        "minecraft-23w42a" = _DkReoHNA;
        "minecraft-23w43a" = _DkReoHNA;
        "minecraft-23w43b" = _DkReoHNA;
        "minecraft-23w44a" = _DkReoHNA;
        "minecraft-23w45a" = _DkReoHNA;
        "minecraft-23w46a" = _DkReoHNA;
        "minecraft-24w03a" = _DkReoHNA;
        "minecraft-24w03b" = _DkReoHNA;
        "minecraft-24w04a" = _DkReoHNA;
        "minecraft-24w05a" = _DkReoHNA;
        "minecraft-24w05b" = _DkReoHNA;
        "minecraft-24w06a" = _DkReoHNA;
        "minecraft-24w07a" = _DkReoHNA;
        "minecraft-24w09a" = _DkReoHNA;
        "minecraft-24w10a" = _DkReoHNA;
        "minecraft-24w11a" = _DkReoHNA;
        "minecraft-24w12a" = _DkReoHNA;
        "minecraft-24w13a" = _DkReoHNA;
        "minecraft-24w14potato" = _DkReoHNA;
        "minecraft-24w14a" = _DkReoHNA;
        "minecraft-1.20.5-pre1" = _DkReoHNA;
        "minecraft-1.20.5-pre2" = _DkReoHNA;
        "minecraft-1.20.5-pre3" = _DkReoHNA;
        "minecraft-24w18a" = _DkReoHNA;
        "minecraft-24w19a" = _DkReoHNA;
        "minecraft-24w19b" = _DkReoHNA;
        "minecraft-24w20a" = _DkReoHNA;
        "minecraft-24w33a" = _DkReoHNA;
        "minecraft-24w34a" = _DkReoHNA;
        "minecraft-24w35a" = _DkReoHNA;
        "minecraft-24w36a" = _DkReoHNA;
        "minecraft-24w37a" = _DkReoHNA;
        "minecraft-24w38a" = _DkReoHNA;
        "minecraft-24w39a" = _DkReoHNA;
        "minecraft-24w40a" = _DkReoHNA;
        "minecraft-1.21.2-pre1" = _DkReoHNA;
        "minecraft-1.21.2-pre2" = _DkReoHNA;
        "minecraft-24w44a" = _DkReoHNA;
        "minecraft-24w45a" = _DkReoHNA;
        "minecraft-24w46a" = _DkReoHNA;
        "minecraft-26.1-snapshot-1" = _DkReoHNA;
        "minecraft-26.1-snapshot-2" = _DkReoHNA;
        "minecraft-26.1-snapshot-3" = _DkReoHNA;
        "minecraft-26.1-snapshot-4" = _DkReoHNA;
        "minecraft-26.1-snapshot-5" = _DkReoHNA;
        "minecraft-26.1-snapshot-6" = _DkReoHNA;
        "minecraft-26.1-snapshot-7" = _DkReoHNA;
        "minecraft-26.1-snapshot-8" = _DkReoHNA;
        "minecraft-26.1-snapshot-9" = _DkReoHNA;
        "minecraft-26.1-snapshot-10" = _DkReoHNA;
        "minecraft-26.1-snapshot-11" = _DkReoHNA;
        "minecraft-26.1-pre-1" = _DkReoHNA;
        "minecraft-26.1-pre-2" = _DkReoHNA;
        "minecraft-26.1-pre-3" = _DkReoHNA;
        "minecraft-26.1-rc-1" = _DkReoHNA;
        "minecraft-26.1-rc-2" = _DkReoHNA;
        "minecraft-26.1-rc-3" = _DkReoHNA;
        "minecraft-26.1" = _DkReoHNA;
        "minecraft-26.1.1-rc-1" = _DkReoHNA;
        "minecraft-26.1.1" = _DkReoHNA;
        "minecraft-26w14a" = _DkReoHNA;
        "minecraft-26.2-snapshot-1" = _DkReoHNA;
        "minecraft-26.1.2-rc-1" = _DkReoHNA;
        "minecraft-26.1.2" = _DkReoHNA;
        "minecraft-26.2-snapshot-2" = _DkReoHNA;
        "minecraft-26.2-snapshot-3" = _DkReoHNA;
        "minecraft-26.2-snapshot-4" = _DkReoHNA;
        "minecraft-26.2-snapshot-5" = _DkReoHNA;
        "minecraft-26.2-snapshot-6" = _DkReoHNA;
        "minecraft-26.2-snapshot-7" = _DkReoHNA;
        "minecraft-26.2-snapshot-8" = _DkReoHNA;
        "minecraft-26.2-pre-1" = _DkReoHNA;
        "minecraft-26.2-pre-2" = _DkReoHNA;
        "minecraft-26.2-pre-3" = _DkReoHNA;
        "minecraft-26.2-pre-4" = _DkReoHNA;
        "minecraft-26.2-pre-5" = _DkReoHNA;
        "minecraft-26.2-pre-6" = _DkReoHNA;
        "minecraft-26.2-rc-1" = _DkReoHNA;
        "minecraft-26.2-rc-2" = _DkReoHNA;
        "minecraft-26.2" = _DkReoHNA;
        "minecraft-26.3-snapshot-1" = _DkReoHNA;
        "minecraft-26.3-snapshot-2" = _DkReoHNA;
        "minecraft-26.3-snapshot-3" = _DkReoHNA;
        "minecraft-26.3-snapshot-4" = _DkReoHNA;
        "minecraft-26.3-snapshot-5" = _DkReoHNA;
        "minecraft-26.3-snapshot-6" = _DkReoHNA;
        "minecraft-26.3-snapshot-7" = _DkReoHNA;
        "pkg-1.20.4" = _gGqjxiE4;
        "pkg-1.20.5" = _LheZGJsi;
        "pkg-1.20.6" = _bLgmKwaH;
        "pkg-1.21" = _9q7WBKaf;
        "pkg-1.21.1" = _7OTFPbLT;
        "pkg-1.21.2" = _hRGuKdjx;
        "pkg-1.21.3" = _LK3ITY69;
        "pkg-1.21.4" = _NT7OhnGQ;
        "pkg-1.21.5" = _TKhj8cpq;
        "pkg-1.21.6" = _lG8t088k;
        "pkg-1.21.7" = _4xfIx8RI;
        "pkg-1.21.8" = _8TWlGf6M;
        "pkg-1.21.9-1.21.11" = _M6uWxUGK;
        "pkg-26+" = _DkReoHNA;
        "default" = _DkReoHNA;
    });
    fn = lib.prismnix.pkgs.mkVersionedModrinthPkgFn {
        name = "bloodmoon-texture";
        id = "p9sqIz3S";
        type = "resourcepack";
        versions = versions;
        meta = {
            license = lib.getLicenseFromSpdxIdOr "MIT" {
                free = false;
                deprecated = false;
                redistributable = false;
                fullName = "MIT License";
                shortName = "MIT";
                url = null;
            };
        };
    };
in callPackage fn {}