{lib, callPackage, ...}:
let
    versions = (let
        _SajMdCYL = {
            "id" = "SajMdCYL";
            "file" = "ultimate bright.zip";
            "hash" = "sha512-t7hNYGCzahTSWUW+TmTnL4sJ0ReRkM8OJubPn6EnOmwWRxrKAtNADLaWhQWsIeoHB45EdYHvLkkZ3sxRjSf3/Q==";
        };
        _vRgbxXcC = {
            "id" = "vRgbxXcC";
            "file" = "ultimate bright.zip";
            "hash" = "sha512-t7hNYGCzahTSWUW+TmTnL4sJ0ReRkM8OJubPn6EnOmwWRxrKAtNADLaWhQWsIeoHB45EdYHvLkkZ3sxRjSf3/Q==";
        };
        _glYwDaw7 = {
            "id" = "glYwDaw7";
            "file" = "ultimate bright.zip";
            "hash" = "sha512-t7hNYGCzahTSWUW+TmTnL4sJ0ReRkM8OJubPn6EnOmwWRxrKAtNADLaWhQWsIeoHB45EdYHvLkkZ3sxRjSf3/Q==";
        };
    in {
        "SajMdCYL" = _SajMdCYL;
        "vRgbxXcC" = _vRgbxXcC;
        "glYwDaw7" = _glYwDaw7;
        "minecraft-1.20" = _glYwDaw7;
        "minecraft-1.20.1" = _glYwDaw7;
        "minecraft-23w31a" = _glYwDaw7;
        "minecraft-23w32a" = _glYwDaw7;
        "minecraft-23w33a" = _glYwDaw7;
        "minecraft-23w35a" = _glYwDaw7;
        "minecraft-1.20.2-pre1" = _glYwDaw7;
        "minecraft-1.20.2" = _glYwDaw7;
        "minecraft-23w42a" = _glYwDaw7;
        "minecraft-23w43a" = _glYwDaw7;
        "minecraft-23w43b" = _glYwDaw7;
        "minecraft-23w44a" = _glYwDaw7;
        "minecraft-23w45a" = _glYwDaw7;
        "minecraft-23w46a" = _glYwDaw7;
        "minecraft-1.20.3" = _glYwDaw7;
        "minecraft-1.20.4" = _glYwDaw7;
        "minecraft-24w03a" = _glYwDaw7;
        "minecraft-24w03b" = _glYwDaw7;
        "minecraft-24w04a" = _glYwDaw7;
        "minecraft-24w05a" = _glYwDaw7;
        "minecraft-24w05b" = _glYwDaw7;
        "minecraft-24w06a" = _glYwDaw7;
        "minecraft-24w07a" = _glYwDaw7;
        "minecraft-24w09a" = _glYwDaw7;
        "minecraft-24w10a" = _glYwDaw7;
        "minecraft-24w11a" = _glYwDaw7;
        "minecraft-24w12a" = _glYwDaw7;
        "minecraft-24w13a" = _glYwDaw7;
        "minecraft-24w14potato" = _glYwDaw7;
        "minecraft-24w14a" = _glYwDaw7;
        "minecraft-1.20.5-pre1" = _glYwDaw7;
        "minecraft-1.20.5-pre2" = _glYwDaw7;
        "minecraft-1.20.5-pre3" = _glYwDaw7;
        "minecraft-1.20.5" = _glYwDaw7;
        "minecraft-1.20.6" = _glYwDaw7;
        "minecraft-24w18a" = _glYwDaw7;
        "minecraft-24w19a" = _glYwDaw7;
        "minecraft-24w19b" = _glYwDaw7;
        "minecraft-24w20a" = _glYwDaw7;
        "minecraft-1.21" = _glYwDaw7;
        "minecraft-1.21.1" = _glYwDaw7;
        "minecraft-24w33a" = _glYwDaw7;
        "minecraft-24w34a" = _glYwDaw7;
        "minecraft-24w35a" = _glYwDaw7;
        "minecraft-24w36a" = _glYwDaw7;
        "minecraft-24w37a" = _glYwDaw7;
        "minecraft-24w38a" = _glYwDaw7;
        "minecraft-24w39a" = _glYwDaw7;
        "minecraft-24w40a" = _glYwDaw7;
        "minecraft-1.21.2-pre1" = _glYwDaw7;
        "minecraft-1.21.2-pre2" = _glYwDaw7;
        "minecraft-1.21.2" = _glYwDaw7;
        "minecraft-1.21.3" = _glYwDaw7;
        "minecraft-24w44a" = _glYwDaw7;
        "minecraft-24w45a" = _glYwDaw7;
        "minecraft-24w46a" = _glYwDaw7;
        "minecraft-1.21.4" = _glYwDaw7;
        "minecraft-1.21.5" = _glYwDaw7;
        "minecraft-1.21.6" = _glYwDaw7;
        "minecraft-1.21.7" = _glYwDaw7;
        "minecraft-1.21.8" = _glYwDaw7;
        "minecraft-1.21.9" = _glYwDaw7;
        "minecraft-1.21.10" = _glYwDaw7;
        "minecraft-1.21.11" = _glYwDaw7;
        "minecraft-26.1" = _glYwDaw7;
        "minecraft-26.1-snapshot-1" = _glYwDaw7;
        "minecraft-26.1-snapshot-2" = _glYwDaw7;
        "minecraft-26.1-snapshot-3" = _glYwDaw7;
        "minecraft-26.1-snapshot-4" = _glYwDaw7;
        "minecraft-26.1-snapshot-5" = _glYwDaw7;
        "minecraft-26.1-snapshot-6" = _glYwDaw7;
        "minecraft-26.1-snapshot-7" = _glYwDaw7;
        "minecraft-26.1-snapshot-8" = _glYwDaw7;
        "minecraft-26.1-snapshot-9" = _glYwDaw7;
        "minecraft-26.1-snapshot-10" = _glYwDaw7;
        "minecraft-26.1-snapshot-11" = _glYwDaw7;
        "minecraft-26.1-pre-1" = _glYwDaw7;
        "minecraft-26.1-pre-2" = _glYwDaw7;
        "minecraft-26.1-pre-3" = _glYwDaw7;
        "minecraft-26.1-rc-1" = _glYwDaw7;
        "minecraft-26.1-rc-2" = _glYwDaw7;
        "minecraft-26.1-rc-3" = _glYwDaw7;
        "minecraft-26.1.1-rc-1" = _glYwDaw7;
        "minecraft-26.1.1" = _glYwDaw7;
        "minecraft-26w14a" = _glYwDaw7;
        "minecraft-26.2-snapshot-1" = _glYwDaw7;
        "minecraft-26.1.2-rc-1" = _glYwDaw7;
        "minecraft-26.1.2" = _glYwDaw7;
        "minecraft-26.2-snapshot-2" = _glYwDaw7;
        "minecraft-26.2-snapshot-3" = _glYwDaw7;
        "minecraft-26.2-snapshot-4" = _glYwDaw7;
        "minecraft-26.2-snapshot-5" = _glYwDaw7;
        "minecraft-26.2-snapshot-6" = _glYwDaw7;
        "minecraft-26.2-snapshot-7" = _glYwDaw7;
        "minecraft-26.2-snapshot-8" = _glYwDaw7;
        "minecraft-26.2-pre-1" = _glYwDaw7;
        "minecraft-26.2-pre-2" = _glYwDaw7;
        "minecraft-26.2-pre-3" = _glYwDaw7;
        "minecraft-26.2-pre-4" = _glYwDaw7;
        "minecraft-26.2-pre-5" = _glYwDaw7;
        "minecraft-26.2-pre-6" = _glYwDaw7;
        "minecraft-26.2-rc-1" = _glYwDaw7;
        "minecraft-26.2-rc-2" = _glYwDaw7;
        "minecraft-26.2" = _glYwDaw7;
        "pkg-1.0" = _SajMdCYL;
        "pkg-2" = _vRgbxXcC;
        "pkg-3" = _glYwDaw7;
        "default" = _glYwDaw7;
    });
    fn = lib.prismnix.pkgs.mkVersionedModrinthPkgFn {
        name = "ultimate-bright";
        id = "QBbDimpb";
        type = "resourcepack";
        versions = versions;
        meta = {
            license = lib.getLicenseFromSpdxIdOr "MIT" {
                free = false;
                deprecated = false;
                redistributable = false;
                fullName = "MIT License";
                shortName = "MIT";
                url = null;
            };
        };
    };
in callPackage fn {}