{lib, callPackage, ...}:
let
    versions = (let
        _cw0znnLd = {
            "id" = "cw0znnLd";
            "file" = "Background Relax.zip";
            "hash" = "sha512-z4BZyX14iB3oXIQKcwg/zlNKM7fNq32cxtiKVP6fG+sKI6QGE8wWtsGiiNoLXsZQOOfKGZN85J4XnTbbtq7V1A==";
        };
        _gIpBwZFz = {
            "id" = "gIpBwZFz";
            "file" = "Background Relax.zip";
            "hash" = "sha512-ZDt9qWdgXRm16N7TfsnhTluR4y+EsFth40xsMfJ5hF+k2jFHdL43ZjUrWPhG0YfEVKYPXkal+kHvBjYfF9dGMA==";
        };
    in {
        "cw0znnLd" = _cw0znnLd;
        "gIpBwZFz" = _gIpBwZFz;
        "minecraft-1.15" = _cw0znnLd;
        "minecraft-1.15.1" = _cw0znnLd;
        "minecraft-1.15.2" = _cw0znnLd;
        "minecraft-1.16" = _cw0znnLd;
        "minecraft-1.16.1" = _cw0znnLd;
        "minecraft-1.16.2" = _cw0znnLd;
        "minecraft-1.16.3" = _cw0znnLd;
        "minecraft-1.16.4" = _cw0znnLd;
        "minecraft-1.16.5" = _cw0znnLd;
        "minecraft-1.17" = _cw0znnLd;
        "minecraft-1.17.1" = _cw0znnLd;
        "minecraft-1.18" = _cw0znnLd;
        "minecraft-1.18.1" = _cw0znnLd;
        "minecraft-1.18.2" = _cw0znnLd;
        "minecraft-1.19" = _cw0znnLd;
        "minecraft-1.19.1" = _cw0znnLd;
        "minecraft-1.19.2" = _cw0znnLd;
        "minecraft-1.19.3" = _cw0znnLd;
        "minecraft-1.19.4" = _cw0znnLd;
        "minecraft-1.20" = _gIpBwZFz;
        "minecraft-1.20.1" = _gIpBwZFz;
        "minecraft-1.20.2" = _gIpBwZFz;
        "minecraft-1.20.3" = _gIpBwZFz;
        "minecraft-1.20.4" = _gIpBwZFz;
        "minecraft-1.20.5" = _gIpBwZFz;
        "minecraft-1.20.6" = _gIpBwZFz;
        "minecraft-1.21" = _gIpBwZFz;
        "minecraft-1.21.1" = _gIpBwZFz;
        "minecraft-23w31a" = _gIpBwZFz;
        "minecraft-23w32a" = _gIpBwZFz;
        "minecraft-23w33a" = _gIpBwZFz;
        "minecraft-23w35a" = _gIpBwZFz;
        "minecraft-1.20.2-pre1" = _gIpBwZFz;
        "minecraft-23w42a" = _gIpBwZFz;
        "minecraft-23w43a" = _gIpBwZFz;
        "minecraft-23w43b" = _gIpBwZFz;
        "minecraft-23w44a" = _gIpBwZFz;
        "minecraft-23w45a" = _gIpBwZFz;
        "minecraft-23w46a" = _gIpBwZFz;
        "minecraft-24w03a" = _gIpBwZFz;
        "minecraft-24w03b" = _gIpBwZFz;
        "minecraft-24w04a" = _gIpBwZFz;
        "minecraft-24w05a" = _gIpBwZFz;
        "minecraft-24w05b" = _gIpBwZFz;
        "minecraft-24w06a" = _gIpBwZFz;
        "minecraft-24w07a" = _gIpBwZFz;
        "minecraft-24w09a" = _gIpBwZFz;
        "minecraft-24w10a" = _gIpBwZFz;
        "minecraft-24w11a" = _gIpBwZFz;
        "minecraft-24w12a" = _gIpBwZFz;
        "minecraft-24w13a" = _gIpBwZFz;
        "minecraft-24w14potato" = _gIpBwZFz;
        "minecraft-24w14a" = _gIpBwZFz;
        "minecraft-1.20.5-pre1" = _gIpBwZFz;
        "minecraft-1.20.5-pre2" = _gIpBwZFz;
        "minecraft-1.20.5-pre3" = _gIpBwZFz;
        "minecraft-24w18a" = _gIpBwZFz;
        "minecraft-24w19a" = _gIpBwZFz;
        "minecraft-24w19b" = _gIpBwZFz;
        "minecraft-24w20a" = _gIpBwZFz;
        "minecraft-24w33a" = _gIpBwZFz;
        "minecraft-24w34a" = _gIpBwZFz;
        "minecraft-24w35a" = _gIpBwZFz;
        "minecraft-24w36a" = _gIpBwZFz;
        "minecraft-24w37a" = _gIpBwZFz;
        "minecraft-24w38a" = _gIpBwZFz;
        "minecraft-24w39a" = _gIpBwZFz;
        "minecraft-24w40a" = _gIpBwZFz;
        "minecraft-1.21.2-pre1" = _gIpBwZFz;
        "minecraft-1.21.2-pre2" = _gIpBwZFz;
        "minecraft-1.21.2" = _gIpBwZFz;
        "minecraft-1.21.3" = _gIpBwZFz;
        "minecraft-24w44a" = _gIpBwZFz;
        "minecraft-24w45a" = _gIpBwZFz;
        "minecraft-24w46a" = _gIpBwZFz;
        "minecraft-1.21.4" = _gIpBwZFz;
        "minecraft-1.21.5" = _gIpBwZFz;
        "minecraft-1.21.6" = _gIpBwZFz;
        "minecraft-1.21.7" = _gIpBwZFz;
        "minecraft-1.21.8" = _gIpBwZFz;
        "minecraft-1.21.9" = _gIpBwZFz;
        "minecraft-1.21.10" = _gIpBwZFz;
        "minecraft-1.21.11" = _gIpBwZFz;
        "minecraft-26.1" = _gIpBwZFz;
        "minecraft-26.1.1" = _gIpBwZFz;
        "minecraft-26.1.2" = _gIpBwZFz;
        "minecraft-26.2" = _gIpBwZFz;
        "minecraft-26.3" = _gIpBwZFz;
        "pkg-1.0" = _cw0znnLd;
        "pkg-1.1" = _gIpBwZFz;
        "default" = _gIpBwZFz;
    });
    fn = lib.prismnix.pkgs.mkVersionedModrinthPkgFn {
        name = "background-relax";
        id = "r7P44Vx7";
        type = "resourcepack";
        versions = versions;
        meta = {
            license = lib.getLicenseFromSpdxIdOr "Apache-2.0" {
                free = false;
                deprecated = false;
                redistributable = false;
                fullName = "Apache License 2.0";
                shortName = "Apache-2.0";
                url = null;
            };
        };
    };
in callPackage fn {}