{lib, callPackage, ...}:
let
    versions = (let
        _2TuTU6MZ = {
            "id" = "2TuTU6MZ";
            "file" = "FA+Player_HMIFix.zip";
            "hash" = "sha512-1P+CJK1b1+ckiXkM8qssvqTBC9wF7bAw4cOaBojmbtzB7W/rEQNLm4SADaHgBRSYrIeHWF5stjSCRTHPlpvmQg==";
        };
        _fUXIoIhE = {
            "id" = "fUXIoIhE";
            "file" = "FA+Player_HMIFix2.zip";
            "hash" = "sha512-jpn/JhRF9ouN2NyIZzp7nvybgXfQ7q7S21ArotiBSV1Xh1EO3Uiv9kmLmTFrh8w9cKwa/fDzx3uSD07gjYj9nw==";
        };
        _baqoYrHH = {
            "id" = "baqoYrHH";
            "file" = "FA+Player_HMIFix3.zip";
            "hash" = "sha512-jpn/JhRF9ouN2NyIZzp7nvybgXfQ7q7S21ArotiBSV1Xh1EO3Uiv9kmLmTFrh8w9cKwa/fDzx3uSD07gjYj9nw==";
        };
        _4uAmQy7Z = {
            "id" = "4uAmQy7Z";
            "file" = "FA+Player_HMIFix4.zip";
            "hash" = "sha512-4Ikb4qJkjnvL51eXfanshDHIUJbs4neuNDXhsyMcNWp02FDSQ8ZmsAKQEnFQnUIFrRkcz+4QKcPUduRtuwYHTA==";
        };
        _WlhgicuX = {
            "id" = "WlhgicuX";
            "file" = "FA+Player_HMIFix5.zip";
            "hash" = "sha512-OupY0ssXF3KZEyi/7uIruMNndQ5/xRWJyKLwV+EFHYRjoqi5zKlXkE7L1hFRaBLw5dBsxy0wIeHv5xq/CGHKOw==";
        };
        _OGsNNlUV = {
            "id" = "OGsNNlUV";
            "file" = "FA+Player_HMIFix7.zip";
            "hash" = "sha512-OupY0ssXF3KZEyi/7uIruMNndQ5/xRWJyKLwV+EFHYRjoqi5zKlXkE7L1hFRaBLw5dBsxy0wIeHv5xq/CGHKOw==";
        };
    in {
        "2TuTU6MZ" = _2TuTU6MZ;
        "fUXIoIhE" = _fUXIoIhE;
        "baqoYrHH" = _baqoYrHH;
        "4uAmQy7Z" = _4uAmQy7Z;
        "WlhgicuX" = _WlhgicuX;
        "OGsNNlUV" = _OGsNNlUV;
        "minecraft-1.20" = _OGsNNlUV;
        "minecraft-1.20.1" = _OGsNNlUV;
        "minecraft-23w31a" = _OGsNNlUV;
        "minecraft-23w32a" = _OGsNNlUV;
        "minecraft-23w33a" = _OGsNNlUV;
        "minecraft-23w35a" = _OGsNNlUV;
        "minecraft-1.20.2-pre1" = _OGsNNlUV;
        "minecraft-1.20.2" = _OGsNNlUV;
        "minecraft-23w42a" = _OGsNNlUV;
        "minecraft-23w43a" = _OGsNNlUV;
        "minecraft-23w43b" = _OGsNNlUV;
        "minecraft-23w44a" = _OGsNNlUV;
        "minecraft-23w45a" = _OGsNNlUV;
        "minecraft-23w46a" = _OGsNNlUV;
        "minecraft-1.20.3" = _OGsNNlUV;
        "minecraft-1.20.4" = _OGsNNlUV;
        "minecraft-24w03a" = _OGsNNlUV;
        "minecraft-24w03b" = _OGsNNlUV;
        "minecraft-24w04a" = _OGsNNlUV;
        "minecraft-24w05a" = _OGsNNlUV;
        "minecraft-24w05b" = _OGsNNlUV;
        "minecraft-24w06a" = _OGsNNlUV;
        "minecraft-24w07a" = _OGsNNlUV;
        "minecraft-24w09a" = _OGsNNlUV;
        "minecraft-24w10a" = _OGsNNlUV;
        "minecraft-24w11a" = _OGsNNlUV;
        "minecraft-24w12a" = _OGsNNlUV;
        "minecraft-24w13a" = _OGsNNlUV;
        "minecraft-24w14potato" = _OGsNNlUV;
        "minecraft-24w14a" = _OGsNNlUV;
        "minecraft-1.20.5-pre1" = _OGsNNlUV;
        "minecraft-1.20.5-pre2" = _OGsNNlUV;
        "minecraft-1.20.5-pre3" = _OGsNNlUV;
        "minecraft-1.20.5" = _OGsNNlUV;
        "minecraft-1.20.6" = _OGsNNlUV;
        "minecraft-24w18a" = _OGsNNlUV;
        "minecraft-24w19a" = _OGsNNlUV;
        "minecraft-24w19b" = _OGsNNlUV;
        "minecraft-24w20a" = _OGsNNlUV;
        "minecraft-1.21" = _OGsNNlUV;
        "minecraft-1.21.1" = _OGsNNlUV;
        "minecraft-24w33a" = _OGsNNlUV;
        "minecraft-24w34a" = _OGsNNlUV;
        "minecraft-24w35a" = _OGsNNlUV;
        "minecraft-24w36a" = _OGsNNlUV;
        "minecraft-24w37a" = _OGsNNlUV;
        "minecraft-24w38a" = _OGsNNlUV;
        "minecraft-24w39a" = _OGsNNlUV;
        "minecraft-24w40a" = _OGsNNlUV;
        "minecraft-1.21.2-pre1" = _OGsNNlUV;
        "minecraft-1.21.2-pre2" = _OGsNNlUV;
        "minecraft-1.21.2" = _OGsNNlUV;
        "minecraft-1.21.3" = _OGsNNlUV;
        "minecraft-24w44a" = _OGsNNlUV;
        "minecraft-24w45a" = _OGsNNlUV;
        "minecraft-24w46a" = _OGsNNlUV;
        "minecraft-1.21.4" = _OGsNNlUV;
        "minecraft-1.21.5" = _OGsNNlUV;
        "minecraft-1.21.6" = _OGsNNlUV;
        "minecraft-1.21.7" = _OGsNNlUV;
        "minecraft-1.21.8" = _OGsNNlUV;
        "minecraft-1.21.9" = _OGsNNlUV;
        "minecraft-1.21.10" = _OGsNNlUV;
        "minecraft-1.21.11" = _OGsNNlUV;
        "minecraft-26.1-snapshot-1" = _4uAmQy7Z;
        "minecraft-26.1-snapshot-2" = _4uAmQy7Z;
        "minecraft-26.1-snapshot-3" = _4uAmQy7Z;
        "minecraft-26.1-snapshot-4" = _4uAmQy7Z;
        "minecraft-26.1-snapshot-5" = _4uAmQy7Z;
        "minecraft-26.1-snapshot-6" = _4uAmQy7Z;
        "minecraft-26.1-snapshot-7" = _4uAmQy7Z;
        "minecraft-26.1-snapshot-8" = _4uAmQy7Z;
        "minecraft-26.1-snapshot-9" = _4uAmQy7Z;
        "minecraft-26.1-snapshot-10" = _4uAmQy7Z;
        "minecraft-26.1-snapshot-11" = _4uAmQy7Z;
        "minecraft-26.1-pre-1" = _4uAmQy7Z;
        "minecraft-26.1-pre-2" = _4uAmQy7Z;
        "minecraft-26.1-pre-3" = _4uAmQy7Z;
        "minecraft-26.1-rc-1" = _4uAmQy7Z;
        "minecraft-26.1-rc-2" = _4uAmQy7Z;
        "minecraft-26.1-rc-3" = _4uAmQy7Z;
        "minecraft-26.1" = _OGsNNlUV;
        "minecraft-26.1.1" = _OGsNNlUV;
        "minecraft-26.1.1-rc-1" = _4uAmQy7Z;
        "minecraft-26w14a" = _4uAmQy7Z;
        "minecraft-26.2-snapshot-1" = _4uAmQy7Z;
        "minecraft-26.1.2-rc-1" = _4uAmQy7Z;
        "minecraft-26.1.2" = _OGsNNlUV;
        "minecraft-26.2" = _OGsNNlUV;
        "pkg-v1.0" = _2TuTU6MZ;
        "pkg-v1.0.1" = _fUXIoIhE;
        "pkg-v1.0.2" = _baqoYrHH;
        "pkg-v1.0.3" = _4uAmQy7Z;
        "pkg-v1.0.4" = _WlhgicuX;
        "pkg-v1.0.6" = _OGsNNlUV;
        "default" = _OGsNNlUV;
    });
    fn = lib.prismnix.pkgs.mkVersionedModrinthPkgFn {
        name = "fa-playerhmi";
        id = "rhWt7ALh";
        type = "resourcepack";
        versions = versions;
        meta = {
            license = lib.getLicenseFromSpdxIdOr "MIT" {
                free = false;
                deprecated = false;
                redistributable = false;
                fullName = "MIT License";
                shortName = "MIT";
                url = null;
            };
        };
    };
in callPackage fn {}