{lib, callPackage, ...}:
let
    versions = (let
        _U10w9yqT = {
            "id" = "U10w9yqT";
            "file" = "No_Totem.zip";
            "hash" = "sha512-oFQg7ZU/vDyxXl2Vd8CAwrho+4CJTvnb6zVEMV939ARRmHW3mn6OfNSZXMOjqPDZnh9rngyNCkSglPHj7+HQwA==";
        };
        _XXLbj2fn = {
            "id" = "XXLbj2fn";
            "file" = "No_Totem-1.21.11.zip";
            "hash" = "sha512-oFQg7ZU/vDyxXl2Vd8CAwrho+4CJTvnb6zVEMV939ARRmHW3mn6OfNSZXMOjqPDZnh9rngyNCkSglPHj7+HQwA==";
        };
        _BJKCVZfV = {
            "id" = "BJKCVZfV";
            "file" = "No_Totem-1.16-26.1.zip";
            "hash" = "sha512-0Sl+05bGD+X/m9+klVbIol7UqRlF0gaC3XoTUMU7zptPFPz5V/3FoMxfDz8Z0FQ9V9C7QdjrtZQ85IyAEcojDQ==";
        };
        _aYLCeyqR = {
            "id" = "aYLCeyqR";
            "file" = "No_Totem-1.16-26.3.zip";
            "hash" = "sha512-0Sl+05bGD+X/m9+klVbIol7UqRlF0gaC3XoTUMU7zptPFPz5V/3FoMxfDz8Z0FQ9V9C7QdjrtZQ85IyAEcojDQ==";
        };
    in {
        "U10w9yqT" = _U10w9yqT;
        "XXLbj2fn" = _XXLbj2fn;
        "BJKCVZfV" = _BJKCVZfV;
        "aYLCeyqR" = _aYLCeyqR;
        "minecraft-1.16" = _BJKCVZfV;
        "minecraft-1.16.1" = _BJKCVZfV;
        "minecraft-1.16.2" = _BJKCVZfV;
        "minecraft-1.16.3" = _BJKCVZfV;
        "minecraft-1.16.4" = _BJKCVZfV;
        "minecraft-1.16.5" = _BJKCVZfV;
        "minecraft-1.17" = _aYLCeyqR;
        "minecraft-1.17.1" = _aYLCeyqR;
        "minecraft-1.18" = _aYLCeyqR;
        "minecraft-1.18.1" = _aYLCeyqR;
        "minecraft-1.18.2" = _aYLCeyqR;
        "minecraft-1.19" = _aYLCeyqR;
        "minecraft-1.19.1" = _aYLCeyqR;
        "minecraft-1.19.2" = _aYLCeyqR;
        "minecraft-1.19.3" = _aYLCeyqR;
        "minecraft-1.19.4" = _aYLCeyqR;
        "minecraft-1.20" = _aYLCeyqR;
        "minecraft-1.20.1" = _aYLCeyqR;
        "minecraft-1.20.2" = _aYLCeyqR;
        "minecraft-1.20.3" = _aYLCeyqR;
        "minecraft-1.20.4" = _aYLCeyqR;
        "minecraft-1.20.5" = _aYLCeyqR;
        "minecraft-1.20.6" = _aYLCeyqR;
        "minecraft-1.21" = _aYLCeyqR;
        "minecraft-1.21.1" = _aYLCeyqR;
        "minecraft-1.21.2" = _aYLCeyqR;
        "minecraft-1.21.3" = _aYLCeyqR;
        "minecraft-1.21.4" = _aYLCeyqR;
        "minecraft-1.21.5" = _aYLCeyqR;
        "minecraft-1.21.6" = _aYLCeyqR;
        "minecraft-1.21.7" = _aYLCeyqR;
        "minecraft-1.21.8" = _aYLCeyqR;
        "minecraft-1.21.9" = _aYLCeyqR;
        "minecraft-1.21.10" = _aYLCeyqR;
        "minecraft-1.21.11" = _aYLCeyqR;
        "minecraft-26.1" = _aYLCeyqR;
        "minecraft-22w42a" = _aYLCeyqR;
        "minecraft-22w43a" = _aYLCeyqR;
        "minecraft-22w44a" = _aYLCeyqR;
        "minecraft-23w14a" = _aYLCeyqR;
        "minecraft-23w16a" = _aYLCeyqR;
        "minecraft-23w31a" = _aYLCeyqR;
        "minecraft-23w32a" = _aYLCeyqR;
        "minecraft-23w33a" = _aYLCeyqR;
        "minecraft-23w35a" = _aYLCeyqR;
        "minecraft-1.20.2-pre1" = _aYLCeyqR;
        "minecraft-23w42a" = _aYLCeyqR;
        "minecraft-23w43a" = _aYLCeyqR;
        "minecraft-23w43b" = _aYLCeyqR;
        "minecraft-23w44a" = _aYLCeyqR;
        "minecraft-23w45a" = _aYLCeyqR;
        "minecraft-23w46a" = _aYLCeyqR;
        "minecraft-24w03a" = _aYLCeyqR;
        "minecraft-24w03b" = _aYLCeyqR;
        "minecraft-24w04a" = _aYLCeyqR;
        "minecraft-24w05a" = _aYLCeyqR;
        "minecraft-24w05b" = _aYLCeyqR;
        "minecraft-24w06a" = _aYLCeyqR;
        "minecraft-24w07a" = _aYLCeyqR;
        "minecraft-24w09a" = _aYLCeyqR;
        "minecraft-24w10a" = _aYLCeyqR;
        "minecraft-24w11a" = _aYLCeyqR;
        "minecraft-24w12a" = _aYLCeyqR;
        "minecraft-24w13a" = _aYLCeyqR;
        "minecraft-24w14potato" = _aYLCeyqR;
        "minecraft-24w14a" = _aYLCeyqR;
        "minecraft-1.20.5-pre1" = _aYLCeyqR;
        "minecraft-1.20.5-pre2" = _aYLCeyqR;
        "minecraft-1.20.5-pre3" = _aYLCeyqR;
        "minecraft-24w18a" = _aYLCeyqR;
        "minecraft-24w19a" = _aYLCeyqR;
        "minecraft-24w19b" = _aYLCeyqR;
        "minecraft-24w20a" = _aYLCeyqR;
        "minecraft-24w33a" = _aYLCeyqR;
        "minecraft-24w34a" = _aYLCeyqR;
        "minecraft-24w35a" = _aYLCeyqR;
        "minecraft-24w36a" = _aYLCeyqR;
        "minecraft-24w37a" = _aYLCeyqR;
        "minecraft-24w38a" = _aYLCeyqR;
        "minecraft-24w39a" = _aYLCeyqR;
        "minecraft-24w40a" = _aYLCeyqR;
        "minecraft-1.21.2-pre1" = _aYLCeyqR;
        "minecraft-1.21.2-pre2" = _aYLCeyqR;
        "minecraft-24w44a" = _aYLCeyqR;
        "minecraft-24w45a" = _aYLCeyqR;
        "minecraft-24w46a" = _aYLCeyqR;
        "minecraft-26.1.1" = _aYLCeyqR;
        "minecraft-26.1.2" = _aYLCeyqR;
        "minecraft-26.2" = _aYLCeyqR;
        "minecraft-26.3" = _aYLCeyqR;
        "pkg-1.0" = _aYLCeyqR;
        "default" = _aYLCeyqR;
    });
    fn = lib.prismnix.pkgs.mkVersionedModrinthPkgFn {
        name = "no-totem";
        id = "S2MeIDJB";
        type = "resourcepack";
        versions = versions;
        meta = {
            license = lib.getLicenseFromSpdxIdOr "LicenseRef-All-Rights-Reserved" {
                free = false;
                deprecated = false;
                redistributable = false;
                fullName = "LicenseRef-All-Rights-Reserved";
                shortName = "LicenseRef-All-Rights-Reserved";
                url = null;
            };
        };
    };
in callPackage fn {}