{lib, callPackage, ...}:
let
    versions = (let
        _RX0nACsu = {
            "id" = "RX0nACsu";
            "file" = "Hitori Gotou Totem.zip";
            "hash" = "sha512-pc2T3SK3eUiIHiFUnMtD3iUQPqvnEEZMij9sx94UyO8Gx5QN2M+gdWpwu/2tW3DZwQF1+dasA7AwGO9f7r2rPg==";
        };
        _KtzTwvEu = {
            "id" = "KtzTwvEu";
            "file" = "Hitori_Gotou-1.21.11-Totem.zip";
            "hash" = "sha512-pc2T3SK3eUiIHiFUnMtD3iUQPqvnEEZMij9sx94UyO8Gx5QN2M+gdWpwu/2tW3DZwQF1+dasA7AwGO9f7r2rPg==";
        };
        _janzTdyu = {
            "id" = "janzTdyu";
            "file" = "Hitori_Gotou-1.16-26.1-Totem.zip";
            "hash" = "sha512-CuqBax2WCccG7TD+jdqnTJvoZCb+fuHLeBg3IaVOcSUfqPqLNRy4TZFMBgWv/xKSL1tLhIsycaU8iK3h7iku0g==";
        };
        _sb9MeiQu = {
            "id" = "sb9MeiQu";
            "file" = "Hitori_Gotou-1.16-26.3-Totem.zip";
            "hash" = "sha512-CuqBax2WCccG7TD+jdqnTJvoZCb+fuHLeBg3IaVOcSUfqPqLNRy4TZFMBgWv/xKSL1tLhIsycaU8iK3h7iku0g==";
        };
    in {
        "RX0nACsu" = _RX0nACsu;
        "KtzTwvEu" = _KtzTwvEu;
        "janzTdyu" = _janzTdyu;
        "sb9MeiQu" = _sb9MeiQu;
        "minecraft-1.16" = _janzTdyu;
        "minecraft-1.16.1" = _janzTdyu;
        "minecraft-1.16.2" = _janzTdyu;
        "minecraft-1.16.3" = _janzTdyu;
        "minecraft-1.16.4" = _janzTdyu;
        "minecraft-1.16.5" = _janzTdyu;
        "minecraft-1.17" = _sb9MeiQu;
        "minecraft-1.17.1" = _sb9MeiQu;
        "minecraft-1.18" = _sb9MeiQu;
        "minecraft-1.18.1" = _sb9MeiQu;
        "minecraft-1.18.2" = _sb9MeiQu;
        "minecraft-1.19" = _sb9MeiQu;
        "minecraft-1.19.1" = _sb9MeiQu;
        "minecraft-1.19.2" = _sb9MeiQu;
        "minecraft-1.19.3" = _sb9MeiQu;
        "minecraft-1.19.4" = _sb9MeiQu;
        "minecraft-1.20" = _sb9MeiQu;
        "minecraft-1.20.1" = _sb9MeiQu;
        "minecraft-1.20.2" = _sb9MeiQu;
        "minecraft-1.20.3" = _sb9MeiQu;
        "minecraft-1.20.4" = _sb9MeiQu;
        "minecraft-1.20.5" = _sb9MeiQu;
        "minecraft-1.20.6" = _sb9MeiQu;
        "minecraft-1.21" = _sb9MeiQu;
        "minecraft-1.21.1" = _sb9MeiQu;
        "minecraft-1.21.2" = _sb9MeiQu;
        "minecraft-1.21.3" = _sb9MeiQu;
        "minecraft-1.21.4" = _sb9MeiQu;
        "minecraft-1.21.5" = _sb9MeiQu;
        "minecraft-1.21.6" = _sb9MeiQu;
        "minecraft-1.21.7" = _sb9MeiQu;
        "minecraft-1.21.8" = _sb9MeiQu;
        "minecraft-1.21.9" = _sb9MeiQu;
        "minecraft-1.21.10" = _sb9MeiQu;
        "minecraft-25w41a" = _RX0nACsu;
        "minecraft-1.21.11" = _sb9MeiQu;
        "minecraft-26.1" = _sb9MeiQu;
        "minecraft-22w42a" = _sb9MeiQu;
        "minecraft-22w43a" = _sb9MeiQu;
        "minecraft-22w44a" = _sb9MeiQu;
        "minecraft-23w14a" = _sb9MeiQu;
        "minecraft-23w16a" = _sb9MeiQu;
        "minecraft-23w31a" = _sb9MeiQu;
        "minecraft-23w32a" = _sb9MeiQu;
        "minecraft-23w33a" = _sb9MeiQu;
        "minecraft-23w35a" = _sb9MeiQu;
        "minecraft-1.20.2-pre1" = _sb9MeiQu;
        "minecraft-23w42a" = _sb9MeiQu;
        "minecraft-23w43a" = _sb9MeiQu;
        "minecraft-23w43b" = _sb9MeiQu;
        "minecraft-23w44a" = _sb9MeiQu;
        "minecraft-23w45a" = _sb9MeiQu;
        "minecraft-23w46a" = _sb9MeiQu;
        "minecraft-24w03a" = _sb9MeiQu;
        "minecraft-24w03b" = _sb9MeiQu;
        "minecraft-24w04a" = _sb9MeiQu;
        "minecraft-24w05a" = _sb9MeiQu;
        "minecraft-24w05b" = _sb9MeiQu;
        "minecraft-24w06a" = _sb9MeiQu;
        "minecraft-24w07a" = _sb9MeiQu;
        "minecraft-24w09a" = _sb9MeiQu;
        "minecraft-24w10a" = _sb9MeiQu;
        "minecraft-24w11a" = _sb9MeiQu;
        "minecraft-24w12a" = _sb9MeiQu;
        "minecraft-24w13a" = _sb9MeiQu;
        "minecraft-24w14potato" = _sb9MeiQu;
        "minecraft-24w14a" = _sb9MeiQu;
        "minecraft-1.20.5-pre1" = _sb9MeiQu;
        "minecraft-1.20.5-pre2" = _sb9MeiQu;
        "minecraft-1.20.5-pre3" = _sb9MeiQu;
        "minecraft-24w18a" = _sb9MeiQu;
        "minecraft-24w19a" = _sb9MeiQu;
        "minecraft-24w19b" = _sb9MeiQu;
        "minecraft-24w20a" = _sb9MeiQu;
        "minecraft-24w33a" = _sb9MeiQu;
        "minecraft-24w34a" = _sb9MeiQu;
        "minecraft-24w35a" = _sb9MeiQu;
        "minecraft-24w36a" = _sb9MeiQu;
        "minecraft-24w37a" = _sb9MeiQu;
        "minecraft-24w38a" = _sb9MeiQu;
        "minecraft-24w39a" = _sb9MeiQu;
        "minecraft-24w40a" = _sb9MeiQu;
        "minecraft-1.21.2-pre1" = _sb9MeiQu;
        "minecraft-1.21.2-pre2" = _sb9MeiQu;
        "minecraft-24w44a" = _sb9MeiQu;
        "minecraft-24w45a" = _sb9MeiQu;
        "minecraft-24w46a" = _sb9MeiQu;
        "minecraft-26.1.1" = _sb9MeiQu;
        "minecraft-26.1.2" = _sb9MeiQu;
        "minecraft-26.2" = _sb9MeiQu;
        "minecraft-26.3" = _sb9MeiQu;
        "pkg-1.0" = _sb9MeiQu;
        "default" = _sb9MeiQu;
    });
    fn = lib.prismnix.pkgs.mkVersionedModrinthPkgFn {
        name = "hitori-gotou-totem-(bocchi-the-rock)";
        id = "Sr4dxCaO";
        type = "resourcepack";
        versions = versions;
        meta = {
            license = lib.getLicenseFromSpdxIdOr "LicenseRef-All-Rights-Reserved" {
                free = false;
                deprecated = false;
                redistributable = false;
                fullName = "LicenseRef-All-Rights-Reserved";
                shortName = "LicenseRef-All-Rights-Reserved";
                url = null;
            };
        };
    };
in callPackage fn {}