{lib, callPackage, ...}:
let
    versions = (let
        _j5UoKidN = {
            "id" = "j5UoKidN";
            "file" = "Sonic The Hedgehog Beds.zip";
            "hash" = "sha512-V+/b3cxBVNFK23aW3zb5PiUrBjUYrgifQn62LNnPmAxDnvhCitxwcNxpL4qiKatLsbKp/mG9+scGngq5ZQj3PQ==";
        };
        _9ObVVAbs = {
            "id" = "9ObVVAbs";
            "file" = "Sonic The Hedgehog Beds (pre1-20-2).zip";
            "hash" = "sha512-PUctnPxbJQrHvkN4lc2oihyi5yti3lhXBzTLrmxO+avrq4EHnp4GbLdY8ai8P+xswJYW/lmObCCcjNuhbK/dfg==";
        };
        _9oyGEaM6 = {
            "id" = "9oyGEaM6";
            "file" = "Sonic The Hedgehog Beds 1.0.1.zip";
            "hash" = "sha512-6GMpvfPWeS+BBShL3mCjzAxbgvgQOrmTRdnVphdPsZlJjzgi1m4e8Z+3leA/IxJT3xsMaPaSCPueA6fiLkASFA==";
        };
        _dT1pmtud = {
            "id" = "dT1pmtud";
            "file" = "Sonic The Hedgehog Beds 1.0.2.zip";
            "hash" = "sha512-sOvtgAbEkanS4se54iYYRYQlqJcXUgzIC4DYxg7zNnxf0vhn79ABP06Qg8HDGi+6XpLaWENPLvTxo46/v0AR2g==";
        };
        _edncvtrw = {
            "id" = "edncvtrw";
            "file" = "Sonic The Hedgehog Beds 1.0.3.zip";
            "hash" = "sha512-qQ0QUyr2HQ7s9iiR19t3s0RKYYpPXnAz3MKnL5vywVUzd6TbV2AXBMeHhFtoWaMcQz7JGmO8Ig3bLQZKtCjZSA==";
        };
        _u4LZnCOX = {
            "id" = "u4LZnCOX";
            "file" = "Sonic The Hedgehog Beds 1.0.4.zip";
            "hash" = "sha512-2uaEMXGuL9VMwVTBd0SPfcUU7D7zXCTncOOKfLg8F86IRDz/X85jknuskG4S5GZt9ucWckx2SeBZEs7B55uMyA==";
        };
        _tmFOFUcD = {
            "id" = "tmFOFUcD";
            "file" = "Sonic The Hedgehog Beds 1.0.5.zip";
            "hash" = "sha512-b0JlkE4m/Xx1Gdzi/8GYqkxK0CEbDQm2595pVie3teXNEvWmbRCdSW1TMRlhX8jxZWTWXg/gF+Ffr8bGxkENxg==";
        };
    in {
        "j5UoKidN" = _j5UoKidN;
        "9ObVVAbs" = _9ObVVAbs;
        "9oyGEaM6" = _9oyGEaM6;
        "dT1pmtud" = _dT1pmtud;
        "edncvtrw" = _edncvtrw;
        "u4LZnCOX" = _u4LZnCOX;
        "tmFOFUcD" = _tmFOFUcD;
        "minecraft-1.20.2" = _tmFOFUcD;
        "minecraft-1.20.3" = _tmFOFUcD;
        "minecraft-1.20.4" = _tmFOFUcD;
        "minecraft-1.20.5" = _tmFOFUcD;
        "minecraft-1.20.6" = _tmFOFUcD;
        "minecraft-1.21" = _tmFOFUcD;
        "minecraft-1.21.1" = _tmFOFUcD;
        "minecraft-1.21.2" = _tmFOFUcD;
        "minecraft-1.21.3" = _tmFOFUcD;
        "minecraft-1.21.4" = _tmFOFUcD;
        "minecraft-1.12" = _9ObVVAbs;
        "minecraft-1.12.1" = _9ObVVAbs;
        "minecraft-1.12.2" = _9ObVVAbs;
        "minecraft-1.13" = _9ObVVAbs;
        "minecraft-1.13.1" = _9ObVVAbs;
        "minecraft-1.13.2" = _9ObVVAbs;
        "minecraft-1.14" = _9ObVVAbs;
        "minecraft-1.14.1" = _9ObVVAbs;
        "minecraft-1.14.2" = _9ObVVAbs;
        "minecraft-1.14.3" = _9ObVVAbs;
        "minecraft-1.14.4" = _9ObVVAbs;
        "minecraft-1.15" = _9ObVVAbs;
        "minecraft-1.15.1" = _9ObVVAbs;
        "minecraft-1.15.2" = _9ObVVAbs;
        "minecraft-1.16" = _dT1pmtud;
        "minecraft-1.16.1" = _dT1pmtud;
        "minecraft-1.16.2" = _dT1pmtud;
        "minecraft-1.16.3" = _dT1pmtud;
        "minecraft-1.16.4" = _dT1pmtud;
        "minecraft-1.16.5" = _dT1pmtud;
        "minecraft-1.17" = _dT1pmtud;
        "minecraft-1.17.1" = _dT1pmtud;
        "minecraft-1.18" = _dT1pmtud;
        "minecraft-1.18.1" = _dT1pmtud;
        "minecraft-1.18.2" = _dT1pmtud;
        "minecraft-1.19" = _dT1pmtud;
        "minecraft-1.19.1" = _dT1pmtud;
        "minecraft-1.19.2" = _dT1pmtud;
        "minecraft-1.19.3" = _dT1pmtud;
        "minecraft-1.19.4" = _dT1pmtud;
        "minecraft-1.20" = _tmFOFUcD;
        "minecraft-1.20.1" = _tmFOFUcD;
        "minecraft-23w31a" = _tmFOFUcD;
        "minecraft-1.21.5" = _tmFOFUcD;
        "minecraft-1.21.6" = _tmFOFUcD;
        "minecraft-1.21.7" = _tmFOFUcD;
        "minecraft-1.21.8" = _tmFOFUcD;
        "minecraft-1.21.9" = _tmFOFUcD;
        "minecraft-1.21.10" = _tmFOFUcD;
        "minecraft-1.21.11" = _tmFOFUcD;
        "minecraft-26.1" = _tmFOFUcD;
        "minecraft-23w32a" = _tmFOFUcD;
        "minecraft-23w33a" = _tmFOFUcD;
        "minecraft-23w35a" = _tmFOFUcD;
        "minecraft-1.20.2-pre1" = _tmFOFUcD;
        "minecraft-23w42a" = _tmFOFUcD;
        "minecraft-23w43a" = _tmFOFUcD;
        "minecraft-23w43b" = _tmFOFUcD;
        "minecraft-23w44a" = _tmFOFUcD;
        "minecraft-23w45a" = _tmFOFUcD;
        "minecraft-23w46a" = _tmFOFUcD;
        "minecraft-24w03a" = _tmFOFUcD;
        "minecraft-24w03b" = _tmFOFUcD;
        "minecraft-24w04a" = _tmFOFUcD;
        "minecraft-24w05a" = _tmFOFUcD;
        "minecraft-24w05b" = _tmFOFUcD;
        "minecraft-24w06a" = _tmFOFUcD;
        "minecraft-24w07a" = _tmFOFUcD;
        "minecraft-24w09a" = _tmFOFUcD;
        "minecraft-24w10a" = _tmFOFUcD;
        "minecraft-24w11a" = _tmFOFUcD;
        "minecraft-24w12a" = _tmFOFUcD;
        "minecraft-24w13a" = _tmFOFUcD;
        "minecraft-24w14potato" = _tmFOFUcD;
        "minecraft-24w14a" = _tmFOFUcD;
        "minecraft-1.20.5-pre1" = _tmFOFUcD;
        "minecraft-1.20.5-pre2" = _tmFOFUcD;
        "minecraft-1.20.5-pre3" = _tmFOFUcD;
        "minecraft-24w18a" = _tmFOFUcD;
        "minecraft-24w19a" = _tmFOFUcD;
        "minecraft-24w19b" = _tmFOFUcD;
        "minecraft-24w20a" = _tmFOFUcD;
        "minecraft-24w33a" = _tmFOFUcD;
        "minecraft-24w34a" = _tmFOFUcD;
        "minecraft-24w35a" = _tmFOFUcD;
        "minecraft-24w36a" = _tmFOFUcD;
        "minecraft-24w37a" = _tmFOFUcD;
        "minecraft-24w38a" = _tmFOFUcD;
        "minecraft-24w39a" = _tmFOFUcD;
        "minecraft-24w40a" = _tmFOFUcD;
        "minecraft-1.21.2-pre1" = _tmFOFUcD;
        "minecraft-1.21.2-pre2" = _tmFOFUcD;
        "minecraft-24w44a" = _tmFOFUcD;
        "minecraft-24w45a" = _tmFOFUcD;
        "minecraft-24w46a" = _tmFOFUcD;
        "minecraft-26.1.1" = _tmFOFUcD;
        "minecraft-26.1.2" = _tmFOFUcD;
        "minecraft-26.2" = _tmFOFUcD;
        "minecraft-26.3" = _tmFOFUcD;
        "pkg-1.0" = _9ObVVAbs;
        "pkg-1.0.1" = _9oyGEaM6;
        "pkg-1.0.2" = _dT1pmtud;
        "pkg-1.0.3" = _edncvtrw;
        "pkg-1.0.4" = _u4LZnCOX;
        "pkg-1.0.5" = _tmFOFUcD;
        "default" = _tmFOFUcD;
    });
    fn = lib.prismnix.pkgs.mkVersionedModrinthPkgFn {
        name = "sonic-the-hedgehog-beds";
        id = "uxT4Vq2V";
        type = "resourcepack";
        versions = versions;
        meta = {
            license = lib.getLicenseFromSpdxIdOr "CC-BY-NC-SA-4.0" {
                free = false;
                deprecated = false;
                redistributable = false;
                fullName = "Creative Commons Attribution Non Commercial Share Alike 4.0 International";
                shortName = "CC-BY-NC-SA-4.0";
                url = null;
            };
        };
    };
in callPackage fn {}