{lib, callPackage, ...}:
let
    versions = (let
        _w41jq2cA = {
            "id" = "w41jq2cA";
            "file" = "OhMyVault!_2026.zip";
            "hash" = "sha512-uXyctNe1eo4YixUfI2tVS61uqilULrxvcgOB8ZLHkwbk9pXEN4s/I39qmnw+EyaaxP5RuHsv3F5/16ZsGtL64w==";
        };
        _WUoAErku = {
            "id" = "WUoAErku";
            "file" = "oh-my-vault-1.0.1.jar";
            "hash" = "sha512-NhCXiU+1oTmFcCyDhMBaXktaaVjp9aFNX+V6pSlByUlDi3KrxaTrHwLutKwgaYd6RcgNrqCrgDqIKVFVMcWImw==";
        };
    in {
        "w41jq2cA" = _w41jq2cA;
        "WUoAErku" = _WUoAErku;
        "datapack-1.21.1" = _w41jq2cA;
        "datapack-1.21.2" = _w41jq2cA;
        "datapack-1.21.3" = _w41jq2cA;
        "datapack-1.21.4" = _w41jq2cA;
        "datapack-1.21.5" = _w41jq2cA;
        "datapack-1.21.6" = _w41jq2cA;
        "datapack-1.21.7" = _w41jq2cA;
        "datapack-1.21.8" = _w41jq2cA;
        "datapack-1.21.9" = _w41jq2cA;
        "datapack-1.21.10" = _w41jq2cA;
        "datapack-1.21.11" = _w41jq2cA;
        "datapack-26.1" = _w41jq2cA;
        "datapack-26.1.1" = _w41jq2cA;
        "datapack-26.1.2" = _w41jq2cA;
        "datapack-26.2" = _w41jq2cA;
        "fabric-1.21.1" = _WUoAErku;
        "fabric-1.21.2" = _WUoAErku;
        "fabric-1.21.3" = _WUoAErku;
        "fabric-1.21.4" = _WUoAErku;
        "fabric-1.21.5" = _WUoAErku;
        "fabric-1.21.6" = _WUoAErku;
        "fabric-1.21.7" = _WUoAErku;
        "fabric-1.21.8" = _WUoAErku;
        "fabric-1.21.9" = _WUoAErku;
        "fabric-1.21.10" = _WUoAErku;
        "fabric-1.21.11" = _WUoAErku;
        "fabric-26.1" = _WUoAErku;
        "fabric-26.1.1" = _WUoAErku;
        "fabric-26.1.2" = _WUoAErku;
        "fabric-26.2" = _WUoAErku;
        "forge-1.21.1" = _WUoAErku;
        "forge-1.21.2" = _WUoAErku;
        "forge-1.21.3" = _WUoAErku;
        "forge-1.21.4" = _WUoAErku;
        "forge-1.21.5" = _WUoAErku;
        "forge-1.21.6" = _WUoAErku;
        "forge-1.21.7" = _WUoAErku;
        "forge-1.21.8" = _WUoAErku;
        "forge-1.21.9" = _WUoAErku;
        "forge-1.21.10" = _WUoAErku;
        "forge-1.21.11" = _WUoAErku;
        "forge-26.1" = _WUoAErku;
        "forge-26.1.1" = _WUoAErku;
        "forge-26.1.2" = _WUoAErku;
        "forge-26.2" = _WUoAErku;
        "neoforge-1.21.1" = _WUoAErku;
        "neoforge-1.21.2" = _WUoAErku;
        "neoforge-1.21.3" = _WUoAErku;
        "neoforge-1.21.4" = _WUoAErku;
        "neoforge-1.21.5" = _WUoAErku;
        "neoforge-1.21.6" = _WUoAErku;
        "neoforge-1.21.7" = _WUoAErku;
        "neoforge-1.21.8" = _WUoAErku;
        "neoforge-1.21.9" = _WUoAErku;
        "neoforge-1.21.10" = _WUoAErku;
        "neoforge-1.21.11" = _WUoAErku;
        "neoforge-26.1" = _WUoAErku;
        "neoforge-26.1.1" = _WUoAErku;
        "neoforge-26.1.2" = _WUoAErku;
        "neoforge-26.2" = _WUoAErku;
        "quilt-1.21.1" = _WUoAErku;
        "quilt-1.21.2" = _WUoAErku;
        "quilt-1.21.3" = _WUoAErku;
        "quilt-1.21.4" = _WUoAErku;
        "quilt-1.21.5" = _WUoAErku;
        "quilt-1.21.6" = _WUoAErku;
        "quilt-1.21.7" = _WUoAErku;
        "quilt-1.21.8" = _WUoAErku;
        "quilt-1.21.9" = _WUoAErku;
        "quilt-1.21.10" = _WUoAErku;
        "quilt-1.21.11" = _WUoAErku;
        "quilt-26.1" = _WUoAErku;
        "quilt-26.1.1" = _WUoAErku;
        "quilt-26.1.2" = _WUoAErku;
        "quilt-26.2" = _WUoAErku;
        "pkg-1.0.1" = _w41jq2cA;
        "pkg-1.0.1+mod" = _WUoAErku;
        "default" = _WUoAErku;
    });
    fn = lib.prismnix.pkgs.mkVersionedModrinthPkgFn {
        name = "oh-my-vault";
        id = "ydTFnIwm";
        type = "mod";
        versions = versions;
        meta = {
            license = lib.getLicenseFromSpdxIdOr "LicenseRef-All-Rights-Reserved" {
                free = false;
                deprecated = false;
                redistributable = false;
                fullName = "LicenseRef-All-Rights-Reserved";
                shortName = "LicenseRef-All-Rights-Reserved";
                url = null;
            };
        };
    };
in callPackage fn {}