{lib, callPackage, ...}:
let
    versions = (let
        _I1OK5ol2 = {
            "id" = "I1OK5ol2";
            "file" = "Nakano Itsuki Totem.zip";
            "hash" = "sha512-+ozqvvUH73KGIUWaMihI93EjIhlzbAXpGREIrCld0nKmc021JqQFiyQYqmQ//fIvYW39HY4RTnzAFX91pSKTMg==";
        };
        _ymGCWtto = {
            "id" = "ymGCWtto";
            "file" = "Nakano_Itsuki_Totem-1.21.11.zip";
            "hash" = "sha512-+ozqvvUH73KGIUWaMihI93EjIhlzbAXpGREIrCld0nKmc021JqQFiyQYqmQ//fIvYW39HY4RTnzAFX91pSKTMg==";
        };
        _vIKip6Yd = {
            "id" = "vIKip6Yd";
            "file" = "Nakano_Itsuki_Totem-1.16-26.1.zip";
            "hash" = "sha512-832kI2icUZU4jPdZcb/wlEFBlRkogWB4RqC8BbplAFD1luhkelaU0tue/mSEfuYZJA0yUSJzvUAwuzqGw8zCkQ==";
        };
        _JQQJbEEz = {
            "id" = "JQQJbEEz";
            "file" = "Nakano_Itsuki_Totem-1.16-26.3.zip";
            "hash" = "sha512-832kI2icUZU4jPdZcb/wlEFBlRkogWB4RqC8BbplAFD1luhkelaU0tue/mSEfuYZJA0yUSJzvUAwuzqGw8zCkQ==";
        };
    in {
        "I1OK5ol2" = _I1OK5ol2;
        "ymGCWtto" = _ymGCWtto;
        "vIKip6Yd" = _vIKip6Yd;
        "JQQJbEEz" = _JQQJbEEz;
        "minecraft-1.16" = _vIKip6Yd;
        "minecraft-1.16.1" = _vIKip6Yd;
        "minecraft-1.16.2" = _vIKip6Yd;
        "minecraft-1.16.3" = _vIKip6Yd;
        "minecraft-1.16.4" = _vIKip6Yd;
        "minecraft-1.16.5" = _vIKip6Yd;
        "minecraft-1.17" = _JQQJbEEz;
        "minecraft-1.17.1" = _JQQJbEEz;
        "minecraft-1.18" = _JQQJbEEz;
        "minecraft-1.18.1" = _JQQJbEEz;
        "minecraft-1.18.2" = _JQQJbEEz;
        "minecraft-1.19" = _JQQJbEEz;
        "minecraft-1.19.1" = _JQQJbEEz;
        "minecraft-1.19.2" = _JQQJbEEz;
        "minecraft-1.19.3" = _JQQJbEEz;
        "minecraft-1.19.4" = _JQQJbEEz;
        "minecraft-1.20" = _JQQJbEEz;
        "minecraft-1.20.1" = _JQQJbEEz;
        "minecraft-1.20.2" = _JQQJbEEz;
        "minecraft-1.20.3" = _JQQJbEEz;
        "minecraft-1.20.4" = _JQQJbEEz;
        "minecraft-1.20.5" = _JQQJbEEz;
        "minecraft-1.20.6" = _JQQJbEEz;
        "minecraft-1.21" = _JQQJbEEz;
        "minecraft-1.21.1" = _JQQJbEEz;
        "minecraft-1.21.2" = _JQQJbEEz;
        "minecraft-1.21.3" = _JQQJbEEz;
        "minecraft-1.21.4" = _JQQJbEEz;
        "minecraft-1.21.5" = _JQQJbEEz;
        "minecraft-1.21.6" = _JQQJbEEz;
        "minecraft-1.21.7" = _JQQJbEEz;
        "minecraft-1.21.8" = _JQQJbEEz;
        "minecraft-1.21.9" = _JQQJbEEz;
        "minecraft-1.21.10" = _JQQJbEEz;
        "minecraft-1.21.11" = _JQQJbEEz;
        "minecraft-26.1" = _JQQJbEEz;
        "minecraft-22w42a" = _JQQJbEEz;
        "minecraft-22w43a" = _JQQJbEEz;
        "minecraft-22w44a" = _JQQJbEEz;
        "minecraft-23w14a" = _JQQJbEEz;
        "minecraft-23w16a" = _JQQJbEEz;
        "minecraft-23w31a" = _JQQJbEEz;
        "minecraft-23w32a" = _JQQJbEEz;
        "minecraft-23w33a" = _JQQJbEEz;
        "minecraft-23w35a" = _JQQJbEEz;
        "minecraft-1.20.2-pre1" = _JQQJbEEz;
        "minecraft-23w42a" = _JQQJbEEz;
        "minecraft-23w43a" = _JQQJbEEz;
        "minecraft-23w43b" = _JQQJbEEz;
        "minecraft-23w44a" = _JQQJbEEz;
        "minecraft-23w45a" = _JQQJbEEz;
        "minecraft-23w46a" = _JQQJbEEz;
        "minecraft-24w03a" = _JQQJbEEz;
        "minecraft-24w03b" = _JQQJbEEz;
        "minecraft-24w04a" = _JQQJbEEz;
        "minecraft-24w05a" = _JQQJbEEz;
        "minecraft-24w05b" = _JQQJbEEz;
        "minecraft-24w06a" = _JQQJbEEz;
        "minecraft-24w07a" = _JQQJbEEz;
        "minecraft-24w09a" = _JQQJbEEz;
        "minecraft-24w10a" = _JQQJbEEz;
        "minecraft-24w11a" = _JQQJbEEz;
        "minecraft-24w12a" = _JQQJbEEz;
        "minecraft-24w13a" = _JQQJbEEz;
        "minecraft-24w14potato" = _JQQJbEEz;
        "minecraft-24w14a" = _JQQJbEEz;
        "minecraft-1.20.5-pre1" = _JQQJbEEz;
        "minecraft-1.20.5-pre2" = _JQQJbEEz;
        "minecraft-1.20.5-pre3" = _JQQJbEEz;
        "minecraft-24w18a" = _JQQJbEEz;
        "minecraft-24w19a" = _JQQJbEEz;
        "minecraft-24w19b" = _JQQJbEEz;
        "minecraft-24w20a" = _JQQJbEEz;
        "minecraft-24w33a" = _JQQJbEEz;
        "minecraft-24w34a" = _JQQJbEEz;
        "minecraft-24w35a" = _JQQJbEEz;
        "minecraft-24w36a" = _JQQJbEEz;
        "minecraft-24w37a" = _JQQJbEEz;
        "minecraft-24w38a" = _JQQJbEEz;
        "minecraft-24w39a" = _JQQJbEEz;
        "minecraft-24w40a" = _JQQJbEEz;
        "minecraft-1.21.2-pre1" = _JQQJbEEz;
        "minecraft-1.21.2-pre2" = _JQQJbEEz;
        "minecraft-24w44a" = _JQQJbEEz;
        "minecraft-24w45a" = _JQQJbEEz;
        "minecraft-24w46a" = _JQQJbEEz;
        "minecraft-26.1.1" = _JQQJbEEz;
        "minecraft-26.1.2" = _JQQJbEEz;
        "minecraft-26.2" = _JQQJbEEz;
        "minecraft-26.3" = _JQQJbEEz;
        "pkg-1.0" = _JQQJbEEz;
        "default" = _JQQJbEEz;
    });
    fn = lib.prismnix.pkgs.mkVersionedModrinthPkgFn {
        name = "nakano-itsuki-(the-quintessential-quintuplets)";
        id = "YupIfPkB";
        type = "resourcepack";
        versions = versions;
        meta = {
            license = lib.getLicenseFromSpdxIdOr "LicenseRef-All-Rights-Reserved" {
                free = false;
                deprecated = false;
                redistributable = false;
                fullName = "LicenseRef-All-Rights-Reserved";
                shortName = "LicenseRef-All-Rights-Reserved";
                url = null;
            };
        };
    };
in callPackage fn {}