{lib, callPackage, ...}:
let
    versions = (let
        _FaUrwaJ4 = {
            "id" = "FaUrwaJ4";
            "file" = "Gravity Enchantment v1.0.0 [1.21-1.21.8].zip";
            "hash" = "sha512-vlwf9jsgesfSsvbYSqTKPbDrOT622l8V1Eh5DC+KlSAD7ceKbvRFU0ejWA6ZEjInc+ZX5Vq8Mmrvwu4FEBShtw==";
        };
        _owoEWmOJ = {
            "id" = "owoEWmOJ";
            "file" = "gravity-enchantment-v1.0.0.jar";
            "hash" = "sha512-hG/nXNdn8Ctnv/+DPCfA4lW3/XLI6sL/MomLUnwu87mFegdwZ/xgxqD4JdagbRcb9xW1t/UWuFf0cvmcFLxy3Q==";
        };
        _OqsjHMw5 = {
            "id" = "OqsjHMw5";
            "file" = "Gravity Enchantment v1.0.0 [26.3].zip";
            "hash" = "sha512-5rr4EjOssSobU7DSsEKI0c1KgX03j2zWWERH6H9jLw0iH1Y55GIdrh+gDSPOGzf90OFOocqztEvL0ecOhJLc0A==";
        };
        _UFybHRaE = {
            "id" = "UFybHRaE";
            "file" = "gravity-enchantment-1.0.0.jar";
            "hash" = "sha512-sfwgP90l2Vepl7Q/oBZ3Qu5aDK07H9KCtt6AnhSUiV/lf5myTxIq9Hm/HP7Es8esSUpT2DgTQ7P6hpNiUoa4YA==";
        };
    in {
        "FaUrwaJ4" = _FaUrwaJ4;
        "owoEWmOJ" = _owoEWmOJ;
        "OqsjHMw5" = _OqsjHMw5;
        "UFybHRaE" = _UFybHRaE;
        "datapack-1.21" = _FaUrwaJ4;
        "datapack-1.21.1" = _FaUrwaJ4;
        "datapack-1.21.2" = _FaUrwaJ4;
        "datapack-1.21.3" = _FaUrwaJ4;
        "datapack-1.21.4" = _FaUrwaJ4;
        "datapack-1.21.5" = _FaUrwaJ4;
        "datapack-1.21.6" = _FaUrwaJ4;
        "datapack-1.21.7" = _FaUrwaJ4;
        "datapack-1.21.8" = _FaUrwaJ4;
        "datapack-1.21.9" = _FaUrwaJ4;
        "datapack-1.21.10" = _FaUrwaJ4;
        "datapack-1.21.11" = _FaUrwaJ4;
        "datapack-26.1" = _FaUrwaJ4;
        "datapack-26.1.1" = _FaUrwaJ4;
        "datapack-26.1.2" = _FaUrwaJ4;
        "datapack-26.2" = _FaUrwaJ4;
        "datapack-26.3" = _OqsjHMw5;
        "fabric-1.21" = _owoEWmOJ;
        "fabric-1.21.1" = _owoEWmOJ;
        "fabric-1.21.2" = _owoEWmOJ;
        "fabric-1.21.3" = _owoEWmOJ;
        "fabric-1.21.4" = _owoEWmOJ;
        "fabric-1.21.5" = _owoEWmOJ;
        "fabric-1.21.6" = _owoEWmOJ;
        "fabric-1.21.7" = _owoEWmOJ;
        "fabric-1.21.8" = _owoEWmOJ;
        "fabric-1.21.9" = _owoEWmOJ;
        "fabric-1.21.10" = _owoEWmOJ;
        "fabric-1.21.11" = _owoEWmOJ;
        "fabric-26.1" = _owoEWmOJ;
        "fabric-26.1.1" = _owoEWmOJ;
        "fabric-26.1.2" = _owoEWmOJ;
        "fabric-26.2" = _owoEWmOJ;
        "fabric-26.3" = _UFybHRaE;
        "forge-1.21" = _owoEWmOJ;
        "forge-1.21.1" = _owoEWmOJ;
        "forge-1.21.2" = _owoEWmOJ;
        "forge-1.21.3" = _owoEWmOJ;
        "forge-1.21.4" = _owoEWmOJ;
        "forge-1.21.5" = _owoEWmOJ;
        "forge-1.21.6" = _owoEWmOJ;
        "forge-1.21.7" = _owoEWmOJ;
        "forge-1.21.8" = _owoEWmOJ;
        "forge-1.21.9" = _owoEWmOJ;
        "forge-1.21.10" = _owoEWmOJ;
        "forge-1.21.11" = _owoEWmOJ;
        "forge-26.1" = _owoEWmOJ;
        "forge-26.1.1" = _owoEWmOJ;
        "forge-26.1.2" = _owoEWmOJ;
        "forge-26.2" = _owoEWmOJ;
        "forge-26.3" = _UFybHRaE;
        "neoforge-1.21" = _owoEWmOJ;
        "neoforge-1.21.1" = _owoEWmOJ;
        "neoforge-1.21.2" = _owoEWmOJ;
        "neoforge-1.21.3" = _owoEWmOJ;
        "neoforge-1.21.4" = _owoEWmOJ;
        "neoforge-1.21.5" = _owoEWmOJ;
        "neoforge-1.21.6" = _owoEWmOJ;
        "neoforge-1.21.7" = _owoEWmOJ;
        "neoforge-1.21.8" = _owoEWmOJ;
        "neoforge-1.21.9" = _owoEWmOJ;
        "neoforge-1.21.10" = _owoEWmOJ;
        "neoforge-1.21.11" = _owoEWmOJ;
        "neoforge-26.1" = _owoEWmOJ;
        "neoforge-26.1.1" = _owoEWmOJ;
        "neoforge-26.1.2" = _owoEWmOJ;
        "neoforge-26.2" = _owoEWmOJ;
        "neoforge-26.3" = _UFybHRaE;
        "quilt-1.21" = _owoEWmOJ;
        "quilt-1.21.1" = _owoEWmOJ;
        "quilt-1.21.2" = _owoEWmOJ;
        "quilt-1.21.3" = _owoEWmOJ;
        "quilt-1.21.4" = _owoEWmOJ;
        "quilt-1.21.5" = _owoEWmOJ;
        "quilt-1.21.6" = _owoEWmOJ;
        "quilt-1.21.7" = _owoEWmOJ;
        "quilt-1.21.8" = _owoEWmOJ;
        "quilt-1.21.9" = _owoEWmOJ;
        "quilt-1.21.10" = _owoEWmOJ;
        "quilt-1.21.11" = _owoEWmOJ;
        "quilt-26.1" = _owoEWmOJ;
        "quilt-26.1.1" = _owoEWmOJ;
        "quilt-26.1.2" = _owoEWmOJ;
        "quilt-26.2" = _owoEWmOJ;
        "quilt-26.3" = _UFybHRaE;
        "pkg-v1.0.0" = _FaUrwaJ4;
        "pkg-v1.0.0+mod" = _owoEWmOJ;
        "pkg-1.0.0" = _OqsjHMw5;
        "pkg-1.0.0+mod" = _UFybHRaE;
        "default" = _UFybHRaE;
    });
    fn = lib.prismnix.pkgs.mkVersionedModrinthPkgFn {
        name = "gravity-enchantment";
        id = "zE7HoPwE";
        type = "mod";
        versions = versions;
        meta = {
            license = lib.getLicenseFromSpdxIdOr "GPL-3.0-or-later" {
                free = false;
                deprecated = false;
                redistributable = false;
                fullName = "GNU General Public License v3.0 or later";
                shortName = "GPL-3.0-or-later";
                url = "https://github.com/lullaby6/data-packs/blob/main/LICENSE";
            };
        };
    };
in callPackage fn {}