{lib, callPackage, ...}:
let
    versions = (let
        _geV1L2BV = {
            "id" = "geV1L2BV";
            "file" = "Smaller Crosshair.zip";
            "hash" = "sha512-UUBG8sCzGhYWAJbBVLcF1jsZhruLrnVRgnbGRyElbHA0llslVwGswUYtCmIvnob5ty7tuO1aklQVN1a4cXsTOA==";
        };
        _tMQbgvLW = {
            "id" = "tMQbgvLW";
            "file" = "Smaller Crosshair.zip";
            "hash" = "sha512-HWQ6d1q7ZtbPXlKXl2IsHEERQiCCGcLr/N0LeyhqFPdHWkdFo1JZG33w+bVsvox3Tx707oNPx+vHqVtkPAVpOQ==";
        };
        _MEHNYGlf = {
            "id" = "MEHNYGlf";
            "file" = "Smaller Crosshair.zip";
            "hash" = "sha512-5vjvjTyG4ha+wyhalZs08RL4nAX46WoPyZx/VmdhqUpEc8bl4dsTgDYwYIagV7Da5uJ37utp5gxFweVQcjXSTQ==";
        };
        _3cIaK3Hc = {
            "id" = "3cIaK3Hc";
            "file" = "Smaller Crosshai 46r.zip";
            "hash" = "sha512-ByouzoovijJKI2bjkuuDbB5XtucD33emyEAgpjGj2HdFMEnO2e96rSSHV3rhaO9nzJ9IuF4NJ5N/EJrrg1nB0w==";
        };
        _1dLBk4x6 = {
            "id" = "1dLBk4x6";
            "file" = "Smaller Crosshair.zip";
            "hash" = "sha512-ZPe+EHkDf6wK5Rc+rJZQHLCflvNzZj3Xle6QDOtjUKrfQwgC/BNq7+1fcMkyrt45F4s9uh67CArION+JN1rhsg==";
        };
        _MMXYcpY8 = {
            "id" = "MMXYcpY8";
            "file" = "Smaller Crosshair.zip";
            "hash" = "sha512-fudbuDi5Sf/ycZcoNVwFcOaSZ/Vcj5SexnARwigtZBmCcnodu83CVWppj0yOxB5XG2OXfhCKHIjn0JLg0WZ3jQ==";
        };
        _5IvqNwrg = {
            "id" = "5IvqNwrg";
            "file" = "Smaller Crosshair.zip";
            "hash" = "sha512-fudbuDi5Sf/ycZcoNVwFcOaSZ/Vcj5SexnARwigtZBmCcnodu83CVWppj0yOxB5XG2OXfhCKHIjn0JLg0WZ3jQ==";
        };
        _oFtaZsJo = {
            "id" = "oFtaZsJo";
            "file" = "Smaller Crosshair.zip";
            "hash" = "sha512-axsQJGMPIK5iXtVNPerw33JwYDYG6VAPtZpf3RZcQuW4v0Ot7pJl2QMaMrNnYCq0tGWV0MvcDpMfYu1k63UYjQ==";
        };
        _quPyARNg = {
            "id" = "quPyARNg";
            "file" = "Smaller Crosshair.zip";
            "hash" = "sha512-rEcvPUD70EOaxzJG4DkYsx+wE7espyO5VVaNmhZhKOkItmFdomh2UMmHVHsEmHtff4Ac5HByGZMYl75GrjL7hA==";
        };
        _M8uiPWMT = {
            "id" = "M8uiPWMT";
            "file" = "Smaller Crosshair.zip";
            "hash" = "sha512-+5fPLg+zbl3KB3IdZ5Hgazcu3Y1l1atsoqvY+TWrZOO0TqPFQhGTOZwVYodM/QmBLEqjQmk0dbbqz5HUfMWEbQ==";
        };
    in {
        "geV1L2BV" = _geV1L2BV;
        "tMQbgvLW" = _tMQbgvLW;
        "MEHNYGlf" = _MEHNYGlf;
        "3cIaK3Hc" = _3cIaK3Hc;
        "1dLBk4x6" = _1dLBk4x6;
        "MMXYcpY8" = _MMXYcpY8;
        "5IvqNwrg" = _5IvqNwrg;
        "oFtaZsJo" = _oFtaZsJo;
        "quPyARNg" = _quPyARNg;
        "M8uiPWMT" = _M8uiPWMT;
        "minecraft-1.21" = _M8uiPWMT;
        "minecraft-1.21.1" = _M8uiPWMT;
        "minecraft-1.21.2" = _M8uiPWMT;
        "minecraft-1.21.3" = _M8uiPWMT;
        "minecraft-1.21.4" = _M8uiPWMT;
        "minecraft-1.21.5" = _M8uiPWMT;
        "minecraft-1.21.6" = _M8uiPWMT;
        "minecraft-1.21.7" = _M8uiPWMT;
        "minecraft-1.21.8" = _M8uiPWMT;
        "minecraft-1.21.9" = _M8uiPWMT;
        "minecraft-1.21.10" = _M8uiPWMT;
        "minecraft-1.21.11" = _M8uiPWMT;
        "minecraft-1.13" = _quPyARNg;
        "minecraft-1.13.1" = _quPyARNg;
        "minecraft-1.13.2" = _quPyARNg;
        "minecraft-1.14" = _quPyARNg;
        "minecraft-1.14.1" = _quPyARNg;
        "minecraft-1.14.2" = _quPyARNg;
        "minecraft-1.14.3" = _quPyARNg;
        "minecraft-1.14.4" = _quPyARNg;
        "minecraft-1.15" = _quPyARNg;
        "minecraft-1.15.1" = _quPyARNg;
        "minecraft-1.15.2" = _quPyARNg;
        "minecraft-1.16" = _M8uiPWMT;
        "minecraft-1.16.1" = _M8uiPWMT;
        "minecraft-1.16.2" = _M8uiPWMT;
        "minecraft-1.16.3" = _M8uiPWMT;
        "minecraft-1.16.4" = _M8uiPWMT;
        "minecraft-1.16.5" = _M8uiPWMT;
        "minecraft-1.17" = _M8uiPWMT;
        "minecraft-1.17.1" = _M8uiPWMT;
        "minecraft-1.18" = _M8uiPWMT;
        "minecraft-1.18.1" = _M8uiPWMT;
        "minecraft-1.18.2" = _M8uiPWMT;
        "minecraft-1.19" = _M8uiPWMT;
        "minecraft-1.19.1" = _M8uiPWMT;
        "minecraft-1.19.2" = _M8uiPWMT;
        "minecraft-22w42a" = _quPyARNg;
        "minecraft-22w43a" = _quPyARNg;
        "minecraft-22w44a" = _quPyARNg;
        "minecraft-1.19.3" = _M8uiPWMT;
        "minecraft-1.19.4" = _M8uiPWMT;
        "minecraft-23w14a" = _quPyARNg;
        "minecraft-23w16a" = _quPyARNg;
        "minecraft-1.20" = _M8uiPWMT;
        "minecraft-1.20.1" = _M8uiPWMT;
        "minecraft-23w31a" = _M8uiPWMT;
        "minecraft-23w32a" = _M8uiPWMT;
        "minecraft-23w33a" = _M8uiPWMT;
        "minecraft-23w35a" = _M8uiPWMT;
        "minecraft-1.20.2-pre1" = _M8uiPWMT;
        "minecraft-1.20.2" = _M8uiPWMT;
        "minecraft-23w42a" = _M8uiPWMT;
        "minecraft-23w43a" = _M8uiPWMT;
        "minecraft-23w43b" = _M8uiPWMT;
        "minecraft-23w44a" = _M8uiPWMT;
        "minecraft-23w45a" = _M8uiPWMT;
        "minecraft-23w46a" = _M8uiPWMT;
        "minecraft-1.20.3" = _M8uiPWMT;
        "minecraft-1.20.4" = _M8uiPWMT;
        "minecraft-24w03a" = _M8uiPWMT;
        "minecraft-24w03b" = _M8uiPWMT;
        "minecraft-24w04a" = _M8uiPWMT;
        "minecraft-24w05a" = _M8uiPWMT;
        "minecraft-24w05b" = _M8uiPWMT;
        "minecraft-24w06a" = _M8uiPWMT;
        "minecraft-24w07a" = _M8uiPWMT;
        "minecraft-24w09a" = _M8uiPWMT;
        "minecraft-24w10a" = _M8uiPWMT;
        "minecraft-24w11a" = _M8uiPWMT;
        "minecraft-24w12a" = _M8uiPWMT;
        "minecraft-24w13a" = _M8uiPWMT;
        "minecraft-24w14potato" = _M8uiPWMT;
        "minecraft-24w14a" = _M8uiPWMT;
        "minecraft-1.20.5-pre1" = _M8uiPWMT;
        "minecraft-1.20.5-pre2" = _M8uiPWMT;
        "minecraft-1.20.5-pre3" = _M8uiPWMT;
        "minecraft-1.20.5" = _M8uiPWMT;
        "minecraft-1.20.6" = _M8uiPWMT;
        "minecraft-24w18a" = _M8uiPWMT;
        "minecraft-24w19a" = _M8uiPWMT;
        "minecraft-24w19b" = _M8uiPWMT;
        "minecraft-24w20a" = _M8uiPWMT;
        "minecraft-24w33a" = _M8uiPWMT;
        "minecraft-24w34a" = _M8uiPWMT;
        "minecraft-24w35a" = _M8uiPWMT;
        "minecraft-24w36a" = _M8uiPWMT;
        "minecraft-24w37a" = _M8uiPWMT;
        "minecraft-24w38a" = _M8uiPWMT;
        "minecraft-24w39a" = _M8uiPWMT;
        "minecraft-24w40a" = _M8uiPWMT;
        "minecraft-1.21.2-pre1" = _M8uiPWMT;
        "minecraft-1.21.2-pre2" = _M8uiPWMT;
        "minecraft-24w44a" = _M8uiPWMT;
        "minecraft-24w45a" = _M8uiPWMT;
        "minecraft-24w46a" = _M8uiPWMT;
        "minecraft-26.1-snapshot-1" = _quPyARNg;
        "minecraft-26.1-snapshot-2" = _quPyARNg;
        "minecraft-26.1-snapshot-3" = _quPyARNg;
        "minecraft-26.1-snapshot-4" = _quPyARNg;
        "minecraft-26.1-snapshot-5" = _quPyARNg;
        "minecraft-26.1-snapshot-6" = _quPyARNg;
        "minecraft-26.1-snapshot-7" = _quPyARNg;
        "minecraft-26.1-snapshot-8" = _quPyARNg;
        "minecraft-26.1-snapshot-9" = _quPyARNg;
        "minecraft-26.1-snapshot-10" = _quPyARNg;
        "minecraft-26.1-snapshot-11" = _quPyARNg;
        "minecraft-26.1-pre-1" = _quPyARNg;
        "minecraft-26.1-pre-2" = _quPyARNg;
        "minecraft-26.1-pre-3" = _quPyARNg;
        "minecraft-26.1-rc-1" = _quPyARNg;
        "minecraft-26.1-rc-2" = _quPyARNg;
        "minecraft-26.1-rc-3" = _quPyARNg;
        "minecraft-26.1" = _M8uiPWMT;
        "minecraft-26.1.1-rc-1" = _quPyARNg;
        "minecraft-26.1.1" = _M8uiPWMT;
        "minecraft-26w14a" = _quPyARNg;
        "minecraft-26.2-snapshot-1" = _quPyARNg;
        "minecraft-26.1.2-rc-1" = _quPyARNg;
        "minecraft-26.1.2" = _M8uiPWMT;
        "minecraft-26.2-snapshot-2" = _quPyARNg;
        "minecraft-26.2-snapshot-3" = _quPyARNg;
        "minecraft-26.2-snapshot-4" = _quPyARNg;
        "minecraft-26.2-snapshot-5" = _quPyARNg;
        "minecraft-26.2-snapshot-6" = _oFtaZsJo;
        "minecraft-26.2-snapshot-7" = _oFtaZsJo;
        "minecraft-1.21.11-pre5" = _quPyARNg;
        "minecraft-1.21.11-rc1" = _quPyARNg;
        "minecraft-1.21.11-rc2" = _quPyARNg;
        "minecraft-1.21.11-rc3" = _quPyARNg;
        "minecraft-26.2-pre-1" = _quPyARNg;
        "minecraft-26.2-pre-2" = _quPyARNg;
        "minecraft-26.2-pre-3" = _quPyARNg;
        "minecraft-26.2-pre-4" = _quPyARNg;
        "minecraft-26.2-pre-5" = _quPyARNg;
        "minecraft-26.2-pre-6" = _quPyARNg;
        "minecraft-26.2-rc-1" = _quPyARNg;
        "minecraft-26.2-rc-2" = _quPyARNg;
        "minecraft-26.2" = _M8uiPWMT;
        "minecraft-26.3-snapshot-1" = _M8uiPWMT;
        "minecraft-26.3-snapshot-2" = _M8uiPWMT;
        "minecraft-26.3-snapshot-7" = _M8uiPWMT;
        "minecraft-26.3-snapshot-3" = _M8uiPWMT;
        "minecraft-26.3-snapshot-4" = _M8uiPWMT;
        "minecraft-26.3-snapshot-5" = _M8uiPWMT;
        "minecraft-26.3-snapshot-6" = _M8uiPWMT;
        "minecraft-26.3-snapshot-8" = _M8uiPWMT;
        "pkg-v1" = _geV1L2BV;
        "pkg-v1.1" = _tMQbgvLW;
        "pkg-1.1.1" = _MEHNYGlf;
        "pkg-1.1.2" = _3cIaK3Hc;
        "pkg-1.1.3" = _1dLBk4x6;
        "pkg-1.1.4" = _MMXYcpY8;
        "pkg-1.1.5" = _5IvqNwrg;
        "pkg-1.2" = _oFtaZsJo;
        "pkg-1.2.1" = _quPyARNg;
        "pkg-1.2.2" = _M8uiPWMT;
        "default" = _M8uiPWMT;
    });
    fn = lib.prismnix.pkgs.mkVersionedModrinthPkgFn {
        name = "smallercrosshair";
        id = "ZztOAazk";
        type = "resourcepack";
        versions = versions;
        meta = {
            license = lib.getLicenseFromSpdxIdOr "LicenseRef-Custom-License---see-terms-" {
                free = false;
                deprecated = false;
                redistributable = false;
                fullName = "LicenseRef-Custom-License---see-terms-";
                shortName = "LicenseRef-Custom-License---see-terms-";
                url = "https://license.cre.ooo/modrinth";
            };
        };
    };
in callPackage fn {}